// RFC-239 — AI change narrative ("变更导读"): the manually-triggered, disk-cached
// summary layer over the structural-change view. One narrative per task
// (task scope only in v1), generated by a zero-tool system agent from the
// change-group statistics; the static grouping must render fine without it.
//
// Parsing is deliberately LENIENT on the collection fields (model output):
// malformed group / readingOrder entries are dropped instead of failing the
// whole document — but a missing/empty `overview` rejects, because a narrative
// with no overview has nothing to show.

import { z } from 'zod'

export const changeNarrativeGroupSchema = z.object({
  /** ChangeGroup.key this sentence belongs to; unknown keys are dropped by the
   *  consumer (group set may have shifted since generation). */
  key: z.string().min(1),
  /** One plain-language sentence for the group. */
  summary: z.string().min(1),
})
export type ChangeNarrativeGroup = z.infer<typeof changeNarrativeGroupSchema>

export const changeNarrativeReadingStepSchema = z.object({
  /** A ChangeGroup.key or a repo-relative filePath — where to look. */
  ref: z.string().min(1),
  /** Why this step comes at this position. */
  why: z.string().min(1),
})
export type ChangeNarrativeReadingStep = z.infer<typeof changeNarrativeReadingStepSchema>

/** Drop-invalid array: keeps elements that parse, silently discards the rest. */
function lenientArray<T extends z.ZodTypeAny>(element: T) {
  return z
    .array(z.unknown())
    .default([])
    .transform((items) =>
      items.flatMap((it) => {
        const parsed = element.safeParse(it)
        return parsed.success ? [parsed.data as z.infer<T>] : []
      }),
    )
}

export const changeNarrativeSchema = z.object({
  version: z.literal(1),
  /** 1–3 sentence overall story of the change. Required — reject without it. */
  overview: z.string().min(1),
  groups: lenientArray(changeNarrativeGroupSchema),
  readingOrder: lenientArray(changeNarrativeReadingStepSchema),
  /** Backend-stamped at persist time (NOT model output). */
  generatedAt: z.number().int().nonnegative(),
  /** The StructuralDiff.contentDigest observed at generation time. The frontend
   *  compares this against the CURRENT response's contentDigest (two backend
   *  values — it never recomputes a digest itself). */
  inputDigest: z.string().min(1),
})
export type ChangeNarrative = z.infer<typeof changeNarrativeSchema>

/** GET /api/tasks/:id/change-narrative response body. */
export const changeNarrativeStatusSchema = z.discriminatedUnion('status', [
  z.object({ status: z.literal('ready'), narrative: changeNarrativeSchema }),
  z.object({ status: z.literal('generating'), startedAt: z.number().int().nonnegative() }),
  z.object({ status: z.literal('failed'), message: z.string() }),
])
export type ChangeNarrativeStatus = z.infer<typeof changeNarrativeStatusSchema>
