// RFC-349 — one logical schema surface backed by two concrete Drizzle table
// projections. Existing application code keeps the strongly typed SQLite
// declarations while the process-wide provider fence swaps the runtime table
// and column objects to a separately constructed pgTable projection.

import { is, SQL, sql } from 'drizzle-orm'
import {
  bigint,
  bigserial,
  boolean,
  customType,
  doublePrecision,
  PgColumn,
  pgSchema,
  text,
  type AnyPgTable,
  type PgColumnBuilderBase,
} from 'drizzle-orm/pg-core'
import {
  getTableConfig,
  SQLiteColumn,
  SQLiteSyncDialect,
  type AnySQLiteColumn,
  type SQLiteTableFn,
} from 'drizzle-orm/sqlite-core'
import type { DatabaseProvider } from '@/platform/persistence/schemaContract'

const applicationSchema = pgSchema('agent_workflow')
const pgBytea = customType<{ data: Uint8Array; driverData: Uint8Array }>({
  dataType: () => 'bytea',
})
const sqliteDialect = new SQLiteSyncDialect()
let activeProvider: DatabaseProvider = 'sqlite'

interface TableProjection {
  readonly sqlite: object
  readonly postgresql: AnyPgTable
  /** 按属性名缓存的列 facade：同一列在两个 provider 下是同一个对象，身份稳定。 */
  readonly columns: Map<string, object>
}

const projectionByFacade = new WeakMap<object, TableProjection>()
const facadeByConcrete = new WeakMap<object, object>()

interface PgColumnBuilderFacade {
  notNull(): PgColumnBuilderFacade
  default(value: unknown): PgColumnBuilderFacade
  primaryKey(): PgColumnBuilderFacade
  unique(name?: string): PgColumnBuilderFacade
}

function renderSqliteDefault(value: SQL): string {
  return sqliteDialect.sqlToQuery(value).sql.replaceAll(/\s+/g, ' ').trim()
}

export function renderPostgresqlDatabaseDefault(value: SQL): string {
  const expression = renderSqliteDefault(value)
  if (/^\(?unixepoch\(\) \* 1000\)?$/i.test(expression)) {
    return '(extract(epoch from clock_timestamp()) * 1000)::bigint'
  }
  if (/^\(?lower\(hex\(randomblob\(16\)\)\)\)?$/i.test(expression)) {
    return 'md5(random()::text || clock_timestamp()::text)'
  }
  // Remaining committed defaults are literal/provider-neutral expressions.
  // The baseline projector independently validates this allowlist before DDL.
  return expression
}

function postgresqlDefaultExpression(value: SQL): SQL {
  return sql.raw(renderPostgresqlDatabaseDefault(value))
}

function pgBuilder(column: AnySQLiteColumn): PgColumnBuilderFacade {
  if ((column as AnySQLiteColumn & { readonly autoIncrement?: boolean }).autoIncrement) {
    // `.default(sql`default`)` is an INSERT-rendering concern, not DDL: the
    // PostgreSQL DDL for this column is produced by the RFC-349 schema
    // projector straight from the SQLite declaration (`schemaContract.ts`
    // marks it `identity`), never from this builder. Drizzle's SQLite dialect
    // — the one that renders every business statement — fills a column that
    // was omitted from `.values()` and carries no default with the literal
    // `null`. SQLite reads that as "assign the next rowid"; PostgreSQL rejects
    // it against `GENERATED BY DEFAULT AS IDENTITY NOT NULL`, which used to
    // fail every `node_run_events` insert (the hottest write in the product).
    // Emitting the DEFAULT keyword instead restores identical semantics on
    // both providers. See rfc349-identity-column-insert-default.test.ts.
    return bigserial(column.name, { mode: 'number' }).default(
      sql`default`,
    ) as unknown as PgColumnBuilderFacade
  }
  if (column.dataType === 'boolean') {
    return boolean(column.name) as unknown as PgColumnBuilderFacade
  }
  if (column.dataType === 'number') {
    return (column.columnType === 'SQLiteReal'
      ? doublePrecision(column.name)
      : bigint(column.name, { mode: 'number' })) as unknown as PgColumnBuilderFacade
  }
  if (column.dataType === 'buffer') {
    return pgBytea(column.name) as unknown as PgColumnBuilderFacade
  }
  return (column.enumValues?.length
    ? text(column.name, { enum: column.enumValues as [string, ...string[]] })
    : text(column.name)) as unknown as PgColumnBuilderFacade
}

function projectColumn(column: AnySQLiteColumn): PgColumnBuilderFacade {
  let builder = pgBuilder(column)
  if (column.notNull) builder = builder.notNull()
  if (column.primary) builder = builder.primaryKey()
  if (column.isUnique) builder = builder.unique(column.uniqueName)
  if (
    column.hasDefault &&
    !(column as AnySQLiteColumn & { readonly autoIncrement?: boolean }).autoIncrement
  ) {
    builder = builder.default(
      is(column.default, SQL) ? postgresqlDefaultExpression(column.default) : column.default,
    )
  }
  return builder
}

function buildPostgresqlTable(sqliteTable: object): AnyPgTable {
  const config = getTableConfig(sqliteTable as Parameters<typeof getTableConfig>[0])
  const columns = Object.fromEntries(
    Object.entries(sqliteTable)
      .filter((entry): entry is [string, AnySQLiteColumn] => is(entry[1], SQLiteColumn))
      .map(([property, column]) => [property, projectColumn(column)]),
  )
  return applicationSchema.table(
    config.name,
    columns as unknown as Record<string, PgColumnBuilderBase>,
  ) as AnyPgTable
}

function projectionFor(value: object): TableProjection | undefined {
  const facade = projectionByFacade.has(value) ? value : facadeByConcrete.get(value)
  return facade === undefined ? undefined : projectionByFacade.get(facade)
}

export function concreteDatabaseTable<T extends object>(table: T, provider: DatabaseProvider): T {
  const projection = projectionFor(table)
  if (projection === undefined) return table
  return projection[provider] as T
}

export function concreteDatabaseColumn<T extends object>(column: T, provider: DatabaseProvider): T {
  const table = (column as { readonly table?: object }).table
  if (table === undefined) return column
  const projection = projectionFor(table)
  if (projection === undefined) return column
  const name = (column as { readonly name?: string }).name
  if (name === undefined) return column
  const concreteTable = projection[provider] as unknown as Record<string, unknown>
  const concreteColumns = Object.values(concreteTable).filter(
    (value): value is PgColumn | AnySQLiteColumn =>
      provider === 'postgresql' ? is(value, PgColumn) : is(value, SQLiteColumn),
  )
  return (concreteColumns.find((candidate) => candidate.name === name) ?? column) as T
}

/**
 * Set once during provider bootstrap. The returned disposer exists for isolated
 * unit tests; production treats a second, different selection as a fence error.
 */
export function selectDatabaseSchemaProvider(provider: DatabaseProvider): () => void {
  const previous = activeProvider
  activeProvider = provider
  return () => {
    activeProvider = previous
  }
}

export function currentDatabaseSchemaProvider(): DatabaseProvider {
  return activeProvider
}

/**
 * 列 facade。表 facade 只在**访问时**解析到当前 provider 的具体表，但业务模块常在模块加载期就把列对象捕获进
 * 常量（`const COLUMNS = { createdAt: table.createdAt }`）——那时进程还没选 provider（默认 sqlite），捕获到的是
 * SQLite 列；在 PostgreSQL 上用它解码就绕开了 pg 投影的 `bigint → number` 映射，游标 / 计数原样回成字符串
 * （RFC-359 W4-D10 在 mission 列表页游标上实撞）。列同样做成访问时解析的 facade 之后，无论何时捕获，drizzle
 * 取到的原型、`mapFromDriverValue` / `mapToDriverValue`、所属表都是当前 provider 的。
 */
function columnFacadeFor(projection: TableProjection, property: string): object {
  const cached = projection.columns.get(property)
  if (cached !== undefined) return cached
  const concrete = (): object =>
    (projection[activeProvider] as unknown as Record<string, object>)[property]!
  const facade: object = new Proxy((projection.sqlite as Record<string, object>)[property]!, {
    get: (_target, key) => Reflect.get(concrete(), key),
    set: (_target, key, value) => Reflect.set(concrete(), key, value),
    has: (_target, key) => Reflect.has(concrete(), key),
    getPrototypeOf: () => Reflect.getPrototypeOf(concrete()),
    ownKeys: () => Reflect.ownKeys(concrete()),
    getOwnPropertyDescriptor: (_target, key) => Reflect.getOwnPropertyDescriptor(concrete(), key),
  })
  projection.columns.set(property, facade)
  return facade
}

export function providerAwareSqliteTable(physicalSqliteTable: SQLiteTableFn): SQLiteTableFn {
  return ((...args: Parameters<SQLiteTableFn>) => {
    const sqliteTable = physicalSqliteTable(...args)
    const postgresqlTable = buildPostgresqlTable(sqliteTable)
    const facade: object = new Proxy(sqliteTable, {
      get(_target, property, receiver) {
        const projection = projectionByFacade.get(facade)!
        const value: unknown = Reflect.get(projection[activeProvider], property, receiver)
        if (typeof property === 'string' && (is(value, SQLiteColumn) || is(value, PgColumn))) {
          return columnFacadeFor(projection, property)
        }
        return value
      },
      getPrototypeOf() {
        const projection = projectionByFacade.get(facade)!
        return Reflect.getPrototypeOf(projection[activeProvider])
      },
    })
    const projection: TableProjection = {
      sqlite: sqliteTable,
      postgresql: postgresqlTable,
      columns: new Map(),
    }
    projectionByFacade.set(facade, projection)
    facadeByConcrete.set(sqliteTable, facade)
    facadeByConcrete.set(postgresqlTable, facade)
    return facade
  }) as SQLiteTableFn
}
