// RFC-092 §5-7 — S-1 端到端验收（修复后正确语义锁定）。
//
// 锁定 design/RFC-092-scheduler-p0-stopgap/design.md §1.2 的 pending 锚点行
// 一次性豁免（deriveFrontier 的 pendingAnchorReleasable + runScope 的
// dispatchedPendingRowIds）在【真实 runTask + 真实 autoDispatchClarifyRound 入口】
// 下的端到端效果。对应调研报告 design/scheduler-audit-2026-06-10.md S-1：
// 修复前，mid-run 答题铸出的 pending rerun 行被 `dispatchedThisInvocation`
// 永久屏蔽，sibling 收尾后 runScope 静默块四个出口全不命中，任务以
// `'scheduler stalled'` 假失败收场。修复后正确语义：
//
//   菱形 in → {asker, slow}。asker 发 <workflow-clarify> 停泊；slow 仍在跑时
//   用户经 autoDispatchClarifyRound（真实服务入口，seal 双表镜像由它自己完成）
//   答题 → 活调度循环在下一 tick（slow settle 触发）经 pending-bypass 自取
//   rerun 行 → asker 带 Q&A 重跑 done → 任务 done。slow 恰好跑一次、不受扰。
//
// 时序确定性：slow 走「gate 文件」慢 mock（轮询 gate 出现才放行，等价于
// fixtures/mock-opencode.ts 的 MOCK_OPENCODE_DELAY_MS 但窗口由测试显式关闭，
// 不赌固定 sleep）；测试侧一律轮询具体 DB 状态（参考
// scheduler-clarify-dispatch.test.ts 的等待模式）。prompt 证据走 mock 落盘
// argv（参考 scheduler-audit-s05 的 MOCK_OPENCODE_CAPTURE_ARGV_TO 模式：
// argv[1] 即渲染后的完整 user prompt）。

import type { ClarifyAnswer, WorkflowDefinition, WorkflowNode } from '@agent-workflow/shared'
import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { and, eq } from 'drizzle-orm'
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { monotonicFactory } from 'ulid'
const ulid = monotonicFactory() // 同毫秒插入仍保 id 单调（pure-id freshness）
import { createInMemoryDb, type DbClient } from '../src/db/client'
import { agents, clarifySessions, nodeRuns, tasks, workflows } from '../src/db/schema'
// RFC-132 (PR-C): answer via the real PR-B path (autoDispatchClarifyRound = seal + auto-dispatch +
// mint the 承接 rerun) so the unified flat injector has a DISPATCHED entry to inject; the legacy
// immediate mint created none.
import { autoDispatchClarifyRound } from '../src/services/clarifyAutoDispatch'
import { runTask } from '../src/services/scheduler'
import { runGit } from '../src/util/git'

const actor = { userId: 'u1', role: 'owner' as const }

const MIGRATIONS = resolve(import.meta.dir, '..', 'db', 'migrations')

// ---------------------------------------------------------------------------
// gate 慢 mock：plan/state/gate 路径全部在生成时烘焙进脚本（零 process.env
// 依赖，杜绝并发测试间串扰）。带 gate 的 agent 在发 envelope 前轮询 gate 文件
// 出现（25ms 间隔、20s 上限兜底，超时 exit 1 让失败显形）；其余 agent 按
// per-agent 调用计数走 plan（同 fixtures/scenario-opencode.ts 的步进语义：
// 越界重复最后一步）。每次被调起 append 一行 {agent, callIndex, argv} 到
// state 目录的 argv.jsonl。
// ---------------------------------------------------------------------------
function gateMockSource(paths: {
  planFile: string
  stateDir: string
  gates: Record<string, string>
}): string {
  return `// generated by rfc092-midrun-clarify-dispatch.test.ts — gate-driven mock opencode
import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
const PLAN_FILE = ${JSON.stringify(paths.planFile)}
const STATE_DIR = ${JSON.stringify(paths.stateDir)}
const GATES: Record<string, string> = ${JSON.stringify(paths.gates)}
const argv = process.argv.slice(2)
if (argv.includes('--version')) { process.stdout.write('midrun-gate-mock 1.14.99\\n'); process.exit(0) }
if (argv[0] !== 'run') { process.stderr.write('midrun-gate-mock: expected run\\n'); process.exit(2) }
const nonce = /\\bnonce="([^"]+)"/.exec(argv[1] ?? '')?.[1]
const outputOpen = nonce === undefined ? '<workflow-output>' : '<workflow-output nonce="' + nonce + '">'
const clarifyOpen = nonce === undefined ? '<workflow-clarify>' : '<workflow-clarify nonce="' + nonce + '">'
const ai = argv.indexOf('--agent')
const agent = ai >= 0 ? (argv[ai + 1] ?? '') : ''
if (agent === '') { process.stderr.write('midrun-gate-mock: missing --agent\\n'); process.exit(2) }
mkdirSync(STATE_DIR, { recursive: true })
const counterFile = join(STATE_DIR, 'count-' + agent)
let n = 0
if (existsSync(counterFile)) n = Number(readFileSync(counterFile, 'utf-8').trim()) || 0
const callIndex = n
writeFileSync(counterFile, String(n + 1))
appendFileSync(join(STATE_DIR, 'argv.jsonl'), JSON.stringify({ agent, callIndex, argv }) + '\\n')
const gate = GATES[agent]
if (gate !== undefined) {
  const deadline = Date.now() + 20000
  while (!existsSync(gate)) {
    if (Date.now() > deadline) { process.stderr.write('midrun-gate-mock: gate timeout\\n'); process.exit(1) }
    await Bun.sleep(25)
  }
}
const plan = JSON.parse(readFileSync(PLAN_FILE, 'utf-8')) as Record<string, Array<Record<string, unknown>>>
const steps = plan[agent] ?? []
const step = steps.length > 0 ? steps[Math.min(callIndex, steps.length - 1)]! : { output: { out: 'default-' + agent } }
function emit(text: string): void {
  process.stdout.write(JSON.stringify({ type: 'text', timestamp: Date.now(), part: { type: 'text', text } }) + '\\n')
}
if (step.clarify !== undefined) {
  emit(clarifyOpen + JSON.stringify(step.clarify) + '</workflow-clarify>')
  process.exit(0)
}
const outputs = (step.output ?? {}) as Record<string, string>
let envelope = outputOpen + '\\n'
for (const [p, c] of Object.entries(outputs)) envelope += '  <port name="' + p + '">' + c + '</port>\\n'
envelope += '</workflow-output>'
emit(envelope)
process.exit(0)
`
}

interface Harness {
  db: DbClient
  appHome: string
  repoPath: string
  worktreePath: string
  stateDir: string
  planFile: string
  gateFile: string
  mockPath: string
  cleanup: () => void
}

async function buildHarness(): Promise<Harness> {
  const appHome = mkdtempSync(join(tmpdir(), 'aw-rfc092-clarify-'))
  const repoPath = join(appHome, 'repo')
  const worktreePath = join(appHome, 'wt')
  const stateDir = join(appHome, 'mock-state')
  const planFile = join(appHome, 'plan.json')
  const gateFile = join(appHome, 'slow-gate')
  const mockPath = join(appHome, 'gate-mock.ts')
  mkdirSync(repoPath, { recursive: true })
  mkdirSync(worktreePath, { recursive: true })
  mkdirSync(stateDir, { recursive: true })
  // 真实 git：调度器要对 worktree 取 pre_snapshot，autoDispatchClarifyRound 的
  // self 回滚也要在真实仓上执行（同 scheduler-clarify-dispatch.test.ts）。
  await runGit(repoPath, ['init', '-b', 'main'])
  await runGit(repoPath, ['config', 'user.email', 't@t.test'])
  await runGit(repoPath, ['config', 'user.name', 't'])
  writeFileSync(join(repoPath, 'README.md'), '# r\n')
  await runGit(repoPath, ['add', '.'])
  await runGit(repoPath, ['commit', '-m', 'init'])
  await runGit(worktreePath, ['init', '-b', 'main'])
  await runGit(worktreePath, ['config', 'user.email', 't@t.test'])
  await runGit(worktreePath, ['config', 'user.name', 't'])
  writeFileSync(join(worktreePath, 'r.md'), '# r\n')
  await runGit(worktreePath, ['add', '.'])
  await runGit(worktreePath, ['commit', '-m', 'init'])
  writeFileSync(mockPath, gateMockSource({ planFile, stateDir, gates: { slow: gateFile } }))
  const db = createInMemoryDb(MIGRATIONS)
  return {
    db,
    appHome,
    repoPath,
    worktreePath,
    stateDir,
    planFile,
    gateFile,
    mockPath,
    cleanup: () => rmSync(appHome, { recursive: true, force: true }),
  }
}

async function seedAgent(db: DbClient, name: string, outputs: string[]): Promise<void> {
  await db.insert(agents).values({
    id: ulid(),
    name,
    description: 'test',
    outputs: JSON.stringify(outputs),
    permission: '{}',
    skills: '[]',
    frontmatterExtra: '{}',
    bodyMd: '',
  })
}

async function seedWorkflowAndTask(
  h: Harness,
  definition: WorkflowDefinition,
  inputs: Record<string, string>,
): Promise<string> {
  const workflowId = ulid()
  const taskId = ulid()
  await h.db.insert(workflows).values({
    id: workflowId,
    name: 'wf-rfc092-s1',
    definition: JSON.stringify(definition),
  })
  await h.db.insert(tasks).values({
    name: 'rfc092-midrun-clarify',
    id: taskId,
    workflowId,
    workflowSnapshot: JSON.stringify(definition),
    repoPath: h.repoPath,
    worktreePath: h.worktreePath,
    baseBranch: 'main',
    branch: `agent-workflow/${taskId}`,
    status: 'pending',
    inputs: JSON.stringify(inputs),
    startedAt: Date.now(),
  })
  return taskId
}

// 有限次轮询等待（25ms 间隔），等不到抛错 —— 绝不裸 sleep 赌时机。
async function waitFor<T>(
  probe: () => Promise<T | undefined>,
  what: string,
  timeoutMs = 10_000,
): Promise<T> {
  const deadline = Date.now() + timeoutMs
  for (;;) {
    const v = await probe()
    if (v !== undefined) return v
    if (Date.now() > deadline) throw new Error(`timed out waiting for ${what}`)
    await Bun.sleep(25)
  }
}

async function topLevelRuns(db: DbClient, taskId: string, nodeId: string) {
  const rows = await db
    .select()
    .from(nodeRuns)
    .where(and(eq(nodeRuns.taskId, taskId), eq(nodeRuns.nodeId, nodeId)))
  return rows.filter((r) => r.parentNodeRunId === null)
}

function readSpawns(stateDir: string): Array<{ agent: string; callIndex: number; prompt: string }> {
  const raw = readFileSync(join(stateDir, 'argv.jsonl'), 'utf-8')
  return raw
    .split('\n')
    .filter((l) => l.trim().length > 0)
    .map((l) => {
      const row = JSON.parse(l) as { agent: string; callIndex: number; argv: string[] }
      // runner 以 `run "<prompt>" --agent NAME ...` 调起 mock；argv 已 slice(2)，
      // 所以 argv[1] 即渲染后的完整 user prompt（同 scheduler-audit-s05）。
      return { agent: row.agent, callIndex: row.callIndex, prompt: row.argv[1] ?? '' }
    })
}

const CLARIFY_BODY = {
  questions: [
    {
      id: 'q1',
      title: 'Which database?',
      kind: 'single',
      recommended: false,
      options: [
        { label: 'Postgres', description: '', recommended: true, recommendationReason: '' },
        { label: 'MySQL', description: '', recommended: false, recommendationReason: '' },
      ],
    },
  ],
}
const CLARIFY_ANSWER: ClarifyAnswer = {
  questionId: 'q1',
  selectedOptionIndices: [0],
  selectedOptionLabels: ['Postgres'],
  customText: '',
}

// 菱形 in → {asker, slow}；asker 挂 clarify 节点（问/答双通道边）。
function diamondDef(): WorkflowDefinition {
  return {
    $schema_version: 3,
    inputs: [{ kind: 'text', key: 'req', label: 'r' }],
    nodes: [
      { id: 'in1', kind: 'input', inputKey: 'req' } as WorkflowNode,
      { id: 'asker', kind: 'agent-single', agentName: 'asker' } as WorkflowNode,
      { id: 'c', kind: 'clarify', title: 'Clarify me' } as WorkflowNode,
      { id: 'slow', kind: 'agent-single', agentName: 'slow' } as WorkflowNode,
    ],
    edges: [
      {
        id: 'e_in_a',
        source: { nodeId: 'in1', portName: 'req' },
        target: { nodeId: 'asker', portName: 'req' },
      },
      {
        id: 'e_in_s',
        source: { nodeId: 'in1', portName: 'req' },
        target: { nodeId: 'slow', portName: 'req' },
      },
      {
        id: 'e_ask',
        source: { nodeId: 'asker', portName: '__clarify__' },
        target: { nodeId: 'c', portName: 'questions' },
      },
      {
        id: 'e_ans',
        source: { nodeId: 'c', portName: 'answers' },
        target: { nodeId: 'asker', portName: '__clarify_response__' },
      },
    ],
  }
}

describe('RFC-092 S-1 端到端 — mid-run clarify 答题由活调度循环自取（不再 scheduler stalled）', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h.cleanup())

  test('slow sibling 仍在跑时答题（autoDispatchClarifyRound）→ 任务 done、rerun 行被自取且 prompt 带答案、slow 恰跑一次', async () => {
    await seedAgent(h.db, 'asker', ['design'])
    await seedAgent(h.db, 'slow', ['out'])
    // asker：第 1 次发 clarify、第 2 次（rerun）出正常 envelope；slow：gate 放行后出 envelope。
    writeFileSync(
      h.planFile,
      JSON.stringify({
        asker: [{ clarify: CLARIFY_BODY }, { output: { design: 'design-after-answer' } }],
        slow: [{ output: { out: 'slow-done' } }],
      }),
    )
    const taskId = await seedWorkflowAndTask(h, diamondDef(), { req: 'go' })

    const runPromise = runTask({
      taskId,
      db: h.db,
      appHome: h.appHome,
      opencodeCmd: ['bun', 'run', h.mockPath],
    })

    let rerunNodeRunId = ''
    try {
      // 等到「clarify 会话已停泊 ∧ slow 仍 running」——这是 S-1 的提交窗口。
      const session = await waitFor(async () => {
        const s = (
          await h.db
            .select()
            .from(clarifySessions)
            .where(
              and(eq(clarifySessions.taskId, taskId), eq(clarifySessions.status, 'awaiting_human')),
            )
        )[0]
        if (s === undefined) return undefined
        const slowRuns = await topLevelRuns(h.db, taskId, 'slow')
        if (slowRuns.length !== 1 || slowRuns[0]!.status !== 'running') return undefined
        return s
      }, 'open clarify session while slow sibling is still running')

      // 窗口证据：任务整体仍 running（不是停泊后再答的 resume 路径）。
      const midTask = (await h.db.select().from(tasks).where(eq(tasks.id, taskId)))[0]!
      expect(midTask.status).toBe('running')

      // 真实入口提交答案（内部自带 RFC-058 clarify_rounds 双表镜像 + rerun 铸行）。
      const res = await autoDispatchClarifyRound({
        db: h.db,
        originNodeRunId: session.clarifyNodeRunId,
        answers: [CLARIFY_ANSWER],
        directive: 'stop', // RFC-100: finalize round → the rerun's <workflow-output> is accepted
        actor,
      })
      rerunNodeRunId = res.dispatch.reruns[0]!.nodeRunId

      // 提交瞬间 rerun 行是 pending、slow 仍在跑——确认答案确实落在窗口内。
      const rerunRow = (
        await h.db.select().from(nodeRuns).where(eq(nodeRuns.id, rerunNodeRunId))
      )[0]!
      expect(rerunRow.status).toBe('pending')
      const slowAtSubmit = (await topLevelRuns(h.db, taskId, 'slow'))[0]!
      expect(slowAtSubmit.status).toBe('running')
    } finally {
      // 无论上面成败都放行 slow，避免 mock 等满 20s 才退出。
      writeFileSync(h.gateFile, 'go\n')
      await runPromise.catch(() => {})
    }
    await runPromise

    // 正确语义（RFC-092 §1.2）：活调度循环在 slow settle 后的 tick 经
    // pending-bypass 自取 rerun 行 → 任务 done，绝不是 'scheduler stalled' 假失败。
    const taskRow = (await h.db.select().from(tasks).where(eq(tasks.id, taskId)))[0]!
    expect(taskRow.errorMessage ?? '').not.toContain('scheduler stalled')
    expect(taskRow.status).toBe('done')

    // rerun 行（统一 dispatch 铸的那一行，被 runOneNode pendingExisting
    // 复用）跑到 done，prompt 注入了 Q&A。
    const rerun = (await h.db.select().from(nodeRuns).where(eq(nodeRuns.id, rerunNodeRunId)))[0]!
    expect(rerun.status).toBe('done')
    expect(rerun.promptText ?? '').toContain('Clarify Q&A')
    expect(rerun.promptText ?? '').toContain('Postgres')

    // asker 顶层恰两行：发问的 done + rerun done（无多余铸行）。
    const askerRuns = await topLevelRuns(h.db, taskId, 'asker')
    expect(askerRuns.length).toBe(2)
    expect(askerRuns.every((r) => r.status === 'done')).toBe(true)

    // mock 落盘 argv：asker 恰被调起两次，第二次（rerun）的 prompt 含答案文本。
    const spawns = readSpawns(h.stateDir)
    const askerSpawns = spawns
      .filter((s) => s.agent === 'asker')
      .sort((a, b) => a.callIndex - b.callIndex)
    expect(askerSpawns.length).toBe(2)
    expect(askerSpawns[1]!.prompt).toContain('Clarify Q&A')
    expect(askerSpawns[1]!.prompt).toContain('Postgres')

    // slow 不受扰：恰好一次 spawn、一行 done。
    expect(spawns.filter((s) => s.agent === 'slow').length).toBe(1)
    const slowRuns = await topLevelRuns(h.db, taskId, 'slow')
    expect(slowRuns.length).toBe(1)
    expect(slowRuns[0]!.status).toBe('done')

    // 会话闭环：answered（不再有 open session）。
    const sessions = await h.db
      .select()
      .from(clarifySessions)
      .where(eq(clarifySessions.taskId, taskId))
    expect(sessions.length).toBe(1)
    expect(sessions[0]!.status).toBe('answered')
  }, 20_000)
})
