// RFC-095 — wrapper canceled 复活：续跑而非重启（audit S-22 连带决策）。
// design/RFC-095-scope-outcome-exhaustive/design.md §1（爆炸半径核查第 3 条）/ §5-6。
//
// 锁定的三件套（任一回归即红）：
//   1. isDispatchable(canceled 无标记)=true —— 取消任务复活后，top-level wrapper 的
//      canceled 行重新进入 ready（dispatchFrontier.ts）。
//   2. findResumableWrapperRun 不再把 canceled 列为 terminal —— 复活走「同一行 id
//      复用 + 持久化 progress 续跑」，而不是铸新 wrapper 行从 iteration 0 重走
//      （旧行为会让 loop 重绕、git 重取错误 baseline）。
//   3. wrapper-resume 的 setNodeRunStatus allowedFrom 含 'canceled'（allowTerminal）
//      —— canceled→running 合法，与 interrupted 续跑语义对齐
//      （先例：scheduler-boundary-wrapper-resume-interrupted.test.ts）。
//
// 场景（loop 路线；取消时序确定性构造）：wrapper-loop(maxIterations=3, 退出条件
// port-equals inner1.out=='EXIT')。自写 invocation-counter mock：第 1 次调用（迭代 0）
// 输出 CONTINUE；第 2 次调用（迭代 1）先写 marker 文件再阻塞——测试等到 marker 出现后
// controller.abort()（与 cancelTask 同一机制：共享 AbortSignal → runner SIGTERM 子进程
// → inner 行翻 canceled → wrapper 行经 markWrapperTerminal 翻 canceled，progress 已在
// 迭代 1 开头持久化）；第 3 次调用（复活重跑迭代 1）输出 EXIT。全程无 sleep 竞态：
// 每一步都由文件 marker / DB 终态轮询闸出。

import type { WorkflowDefinition } from '@agent-workflow/shared'
import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { eq } from 'drizzle-orm'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { ulid } from 'ulid'
import { createInMemoryDb, type DbClient } from '../src/db/client'
import { agents, nodeRuns, tasks, workflows } from '../src/db/schema'
import { runTask } from '../src/services/scheduler'
import { retryNode } from '../src/services/task'
import { decodeWrapperProgress } from '../src/services/wrapperProgress'

const MIGRATIONS = resolve(import.meta.dir, '..', 'db', 'migrations')

// 自写 mock opencode：行为只由 ctrl 目录里的调用计数决定（env 全局态零依赖，
// 跨 runTask 两阶段也确定）。输出事件形状复刻 fixtures/mock-opencode.ts 的
// text-event + <workflow-output> 封皮。
function buildMockScript(ctrlDir: string): string {
  return `// generated by rfc095-wrapper-canceled-revival.test.ts — invocation-counter mock.
import { readFileSync, writeFileSync } from 'node:fs'

const CTRL = ${JSON.stringify(ctrlDir)}
let n = 0
try {
  n = Number(readFileSync(CTRL + '/count', 'utf-8').trim()) || 0
} catch {}
n += 1
writeFileSync(CTRL + '/count', String(n))

function emit(text: string): void {
  process.stdout.write(
    JSON.stringify({ type: 'text', timestamp: Date.now(), part: { type: 'text', text } }) + '\\n',
  )
}
const envelope = (v: string): string =>
  '<workflow-output>\\n  <port name="out">' + v + '</port>\\n</workflow-output>'

if (n === 1) {
  // loop 迭代 0：不满足退出条件，继续循环。
  emit(envelope('CONTINUE'))
} else if (n === 2) {
  // loop 迭代 1：先给测试发"我已起跑"的 marker，再阻塞等待 SIGTERM（任务取消）。
  writeFileSync(CTRL + '/iter1-started', '1')
  await Bun.sleep(120000)
  process.exit(1)
} else {
  // 复活后重跑迭代 1：满足退出条件。
  emit(envelope('EXIT'))
}
process.exit(0)
`
}

interface Harness {
  db: DbClient
  appHome: string
  worktreePath: string
  ctrlDir: string
  mockPath: string
  cleanup: () => void
}

function buildHarness(): Harness {
  const appHome = mkdtempSync(join(tmpdir(), 'aw-rfc095-wrapres-'))
  const worktreePath = join(appHome, 'wt')
  const ctrlDir = join(appHome, 'ctrl')
  mkdirSync(worktreePath, { recursive: true }) // readonly agent ⇒ 纯目录即可（非 git）
  mkdirSync(ctrlDir, { recursive: true })
  const mockPath = join(ctrlDir, 'mock-opencode-counter.ts')
  writeFileSync(mockPath, buildMockScript(ctrlDir))
  const db = createInMemoryDb(MIGRATIONS)
  return {
    db,
    appHome,
    worktreePath,
    ctrlDir,
    mockPath,
    cleanup: () => rmSync(appHome, { recursive: true, force: true }),
  }
}

async function seedWorkflowAndTask(h: Harness, definition: WorkflowDefinition): Promise<string> {
  await h.db.insert(agents).values({
    id: ulid(),
    name: 'worker',
    description: 'test',
    outputs: JSON.stringify(['out']),
    permission: '{}',
    skills: '[]',
    frontmatterExtra: '{}',
    bodyMd: '',
  })
  const workflowId = ulid()
  const taskId = ulid()
  await h.db.insert(workflows).values({
    id: workflowId,
    name: 'wf-rfc095-revival',
    definition: JSON.stringify(definition),
  })
  await h.db.insert(tasks).values({
    name: 'fixture-task',
    id: taskId,
    workflowId,
    workflowSnapshot: JSON.stringify(definition),
    repoPath: '/nonexistent-rfc095-repo',
    worktreePath: h.worktreePath,
    baseBranch: 'main',
    branch: `agent-workflow/${taskId}`,
    status: 'pending',
    inputs: '{}',
    startedAt: Date.now(),
  })
  return taskId
}

async function waitFor(cond: () => boolean, what: string): Promise<void> {
  for (let i = 0; i < 400; i++) {
    if (cond()) return
    await Bun.sleep(25)
  }
  throw new Error(`timeout waiting for ${what}`)
}

async function waitForTerminalTask(
  db: DbClient,
  taskId: string,
): Promise<typeof tasks.$inferSelect> {
  for (let i = 0; i < 400; i++) {
    const t = (await db.select().from(tasks).where(eq(tasks.id, taskId)))[0]
    if (t !== undefined && t.status !== 'pending' && t.status !== 'running') return t
    await Bun.sleep(25)
  }
  throw new Error(`task ${taskId} did not reach a terminal status within budget`)
}

describe('RFC-095 — canceled wrapper-loop 经 retryNode 复活后续跑（同行复用 + 持久化 iteration）', () => {
  let h: Harness
  beforeEach(() => {
    h = buildHarness()
  })
  afterEach(() => {
    h.cleanup()
  })

  test('取消于迭代 1 → wrapper 行 canceled 且 progress 持久化 iteration=1；retryNode 复活 → 同一 wrapper 行续跑至 done，迭代 0 不重走', async () => {
    const def: WorkflowDefinition = {
      $schema_version: 3,
      inputs: [],
      nodes: [
        {
          id: 'lw',
          kind: 'wrapper-loop',
          nodeIds: ['inner1'],
          maxIterations: 3,
          exitCondition: { kind: 'port-equals', nodeId: 'inner1', portName: 'out', value: 'EXIT' },
          outputBindings: [{ name: 'final', bind: { nodeId: 'inner1', portName: 'out' } }],
        },
        { id: 'inner1', kind: 'agent-single', agentName: 'worker' },
      ] as unknown as WorkflowDefinition['nodes'],
      edges: [],
    }
    const taskId = await seedWorkflowAndTask(h, def)

    // ---- 阶段 1：跑到迭代 1 的 inner 起跑 marker，然后取消（cancelTask 的同一
    // 机制：abort 共享 signal；cancelTask 自身只是 controller.abort() + 等调度器
    // 落账，见 task.ts cancelTask）。
    const controller = new AbortController()
    const running = runTask({
      taskId,
      db: h.db,
      appHome: h.appHome,
      opencodeCmd: ['bun', 'run', h.mockPath],
      signal: controller.signal,
    })
    await waitFor(() => existsSync(join(h.ctrlDir, 'iter1-started')), 'iteration-1 inner spawn')
    controller.abort()
    await running

    const afterCancel = (await h.db.select().from(tasks).where(eq(tasks.id, taskId)))[0]!
    expect(afterCancel.status).toBe('canceled')

    const midRows = await h.db.select().from(nodeRuns).where(eq(nodeRuns.taskId, taskId))
    const lwAfterCancel = midRows.filter((r) => r.nodeId === 'lw')
    expect(lwAfterCancel).toHaveLength(1)
    const wrapperRunId = lwAfterCancel[0]!.id
    expect(lwAfterCancel[0]!.status).toBe('canceled')
    // progress 在迭代 1 开头持久化（markWrapperTerminal 不清除）——复活的续跑锚点。
    const midProgress = decodeWrapperProgress(lwAfterCancel[0]!.wrapperProgressJson, () => {})
    expect(midProgress?.kind).toBe('loop')
    expect(midProgress?.iteration).toBe(1)

    // inner1：迭代 0 done、迭代 1 被 SIGTERM 翻 canceled（无 supersede 标记 ⇒
    // 是普通取消行，不落 isDispatchable 的停泊例外）。
    const innerCanceled = midRows.find(
      (r) => r.nodeId === 'inner1' && r.iteration === 1 && r.status === 'canceled',
    )
    expect(innerCanceled).toBeDefined()
    // RFC-145：非 supersede 的普通取消行——结构化列必为 NULL。
    expect(innerCanceled!.supersededByReview !== null).toBe(false)
    const innerDone0 = midRows.filter(
      (r) => r.nodeId === 'inner1' && r.iteration === 0 && r.status === 'done',
    )
    expect(innerDone0).toHaveLength(1)

    // ---- 阶段 2：用户对被取消的 inner 行 retryNode（前端 canRetryNodeRun 把
    // canceled 列为可重试）。lw 自身不在 inner1 的 edges 下游 ⇒ 不会被铸 failed
    // 占位行，其 canceled 行保持 latest——复活路径完整经过 isDispatchable(canceled)
    // → findResumableWrapperRun(canceled 可复活) → canceled→running（allowedFrom）。
    const next = await retryNode(h.db, taskId, innerCanceled!.id, {
      cascade: true,
      deps: { db: h.db, appHome: h.appHome, opencodeCmd: ['bun', 'run', h.mockPath] },
    })
    expect(next.status).toBe('pending')
    const final = await waitForTerminalTask(h.db, taskId)
    expect(`${final.status}:${final.errorSummary ?? ''}`).toBe('done:')

    const after = await h.db.select().from(nodeRuns).where(eq(nodeRuns.taskId, taskId))

    // 续跑而非重启 #1：wrapper 行没有铸新——同一行 id 复用、终态 done。
    const lwRows = after.filter((r) => r.nodeId === 'lw')
    expect(lwRows).toHaveLength(1)
    expect(lwRows[0]!.id).toBe(wrapperRunId)
    expect(lwRows[0]!.status).toBe('done')

    // 续跑而非重启 #2：loop 从持久化 iteration=1 继续并在该迭代满足退出条件
    // （progress payload 终值仍指向迭代 1，而非重绕后的其他值）。
    const finalProgress = decodeWrapperProgress(lwRows[0]!.wrapperProgressJson, () => {})
    expect(finalProgress?.kind).toBe('loop')
    expect(finalProgress?.iteration).toBe(1)

    // 续跑而非重启 #3：迭代 0 没有被重走——inner1 在迭代 0 仍只有原 done 行；
    // 复活只补跑了被取消的迭代 1（canceled + retryNode 占位 failed + 新 done）。
    const innerAt0 = after.filter((r) => r.nodeId === 'inner1' && r.iteration === 0)
    expect(innerAt0).toHaveLength(1)
    expect(innerAt0[0]!.status).toBe('done')
    const innerAt1 = after.filter((r) => r.nodeId === 'inner1' && r.iteration === 1)
    expect(innerAt1.map((r) => r.status).sort()).toEqual(['canceled', 'done', 'failed'])

    // 续跑而非重启 #4：inner agent 总调用次数恒 3（迭代 0 一次、被取消一次、
    // 复活重跑一次）——除被取消的迭代 1 外没有任何多余派发。
    expect(readFileSync(join(h.ctrlDir, 'count'), 'utf-8').trim()).toBe('3')
  }, 30000)

  // RFC-098 B3（audit ⑥-11）：以 wrapper **自身** 的 canceled 行为 retryNode
  // 目标也必须走续跑——修复前 retryNode 对 target 无条件铸 failed 占位行，
  // 占位行成为 latest → findResumableWrapperRun 返回 null → 铸新 wrapper 行从
  // iteration 0 重启（本用例落档时为 RED，⑥-11 方案 A 落地后转绿）。
  // 修复后：target 为 wrapper kind ∧ status ∈ {canceled, interrupted} 时不铸
  // 占位行，canceled 行保持 latest，复活三件套全程同前一用例。
  test('⑥-11：以 wrapper 自身 canceled 行为 retry 目标 → 不铸占位行、同行续跑至 done', async () => {
    const def: WorkflowDefinition = {
      $schema_version: 3,
      inputs: [],
      nodes: [
        {
          id: 'lw',
          kind: 'wrapper-loop',
          nodeIds: ['inner1'],
          maxIterations: 3,
          exitCondition: { kind: 'port-equals', nodeId: 'inner1', portName: 'out', value: 'EXIT' },
          outputBindings: [{ name: 'final', bind: { nodeId: 'inner1', portName: 'out' } }],
        },
        { id: 'inner1', kind: 'agent-single', agentName: 'worker' },
      ] as unknown as WorkflowDefinition['nodes'],
      edges: [],
    }
    const taskId = await seedWorkflowAndTask(h, def)

    // 阶段 1：同前一用例——迭代 1 起跑后取消。
    const controller = new AbortController()
    const running = runTask({
      taskId,
      db: h.db,
      appHome: h.appHome,
      opencodeCmd: ['bun', 'run', h.mockPath],
      signal: controller.signal,
    })
    await waitFor(() => existsSync(join(h.ctrlDir, 'iter1-started')), 'iteration-1 inner spawn')
    controller.abort()
    await running

    const midRows = await h.db.select().from(nodeRuns).where(eq(nodeRuns.taskId, taskId))
    const lwCanceled = midRows.filter((r) => r.nodeId === 'lw')
    expect(lwCanceled).toHaveLength(1)
    expect(lwCanceled[0]!.status).toBe('canceled')
    const wrapperRunId = lwCanceled[0]!.id

    // 阶段 2：retry 目标 = wrapper 自身的 canceled 行（前端 canRetryNodeRun 把
    // canceled 列为可重试——这正是 UI 上点 wrapper 行 retry 的入口）。
    const next = await retryNode(h.db, taskId, wrapperRunId, {
      cascade: true,
      deps: { db: h.db, appHome: h.appHome, opencodeCmd: ['bun', 'run', h.mockPath] },
    })
    expect(next.status).toBe('pending')
    const final = await waitForTerminalTask(h.db, taskId)
    expect(`${final.status}:${final.errorSummary ?? ''}`).toBe('done:')

    const after = await h.db.select().from(nodeRuns).where(eq(nodeRuns.taskId, taskId))

    // ⑥-11 核心：wrapper 节点全程恒一行（没有 failed 占位行、没有新铸 wrapper
    // 行），同一行 id 终态 done。
    const lwRows = after.filter((r) => r.nodeId === 'lw')
    expect(lwRows).toHaveLength(1)
    expect(lwRows[0]!.id).toBe(wrapperRunId)
    expect(lwRows[0]!.status).toBe('done')
    expect(after.filter((r) => r.errorMessage === 'queued for retry')).toHaveLength(0)

    // 续跑语义：progress 终值指向迭代 1；迭代 0 不重走；inner 总调用恒 3。
    const finalProgress = decodeWrapperProgress(lwRows[0]!.wrapperProgressJson, () => {})
    expect(finalProgress?.kind).toBe('loop')
    expect(finalProgress?.iteration).toBe(1)
    const innerAt0 = after.filter((r) => r.nodeId === 'inner1' && r.iteration === 0)
    expect(innerAt0).toHaveLength(1)
    expect(innerAt0[0]!.status).toBe('done')
    const innerAt1 = after.filter((r) => r.nodeId === 'inner1' && r.iteration === 1)
    expect(innerAt1.map((r) => r.status).sort()).toEqual(['canceled', 'done'])
    expect(readFileSync(join(h.ctrlDir, 'count'), 'utf-8').trim()).toBe('3')
  }, 30000)
})
