import { rimrafDir } from './helpers/cleanup'
// RFC-092 §5-8 — S-1 端到端验收（review iterate 形态，修复后正确语义锁定）。
//
// 锁定 design/RFC-092-scheduler-p0-stopgap/design.md §1.2 的 pending 锚点行
// 一次性豁免在【真实 runTask + 真实 submitReviewDecision 入口】下的端到端
// 效果。对应调研报告 design/scheduler-audit-2026-06-10.md S-1：review
// iterate/reject（review.ts）给本调用已派发过的节点铸 pending rerun 行 +
// 把 review 行原地翻回 pending；修复前这两个 pending 行都被
// `dispatchedThisInvocation` 永久屏蔽，sibling 收尾后任务以
// `'scheduler stalled'` 假失败收场。修复后正确语义：
//
//   in → {author → review, slow}。review 停泊 awaiting_review；slow 仍在跑时
//   用户经 submitReviewDecision(iterated)（真实服务入口）打回 → 活调度循环在
//   slow settle 后的 tick 经 pending-bypass 依次自取：author 的 rerun 行
//   （retryIndex+1 新铸行）先跑 done，review 行（原行翻 pending、
//   reviewIteration+1）随后重派、铸 v2 doc_version 再次停泊 → 任务以
//   awaiting_review（真实状态）收场而非 stalled。随后 approve + resume
//   把任务推到 done，确认全链路推进。
//
// 时序确定性：slow 走「gate 文件」慢 mock（同 rfc092-midrun-clarify-dispatch
// .test.ts；窗口由测试显式关闭，不赌固定 sleep）；测试侧一律轮询具体 DB
// 状态。prompt 证据走 mock 落盘 argv（scheduler-audit-s05 的
// MOCK_OPENCODE_CAPTURE_ARGV_TO 模式：argv[1] 即完整 user prompt）。

import type { WorkflowDefinition, WorkflowNode } from '@agent-workflow/shared'
import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { and, eq } from 'drizzle-orm'
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { monotonicFactory } from 'ulid'
const ulid = monotonicFactory() // 同毫秒插入仍保 id 单调（pure-id freshness）
import { createInMemoryDb, type DbClient } from '../src/db/client'
import { agents, docVersions, nodeRuns, tasks, workflows } from '../src/db/schema'
import { addReviewComment, submitReviewDecision } from '../src/services/review'
import { runTask } from '../src/services/scheduler'
import { runGit } from '../src/util/git'
import { reenterScheduler } from './reenter-scheduler'

const MIGRATIONS = resolve(import.meta.dir, '..', 'db', 'migrations')

// gate 慢 mock —— 同 rfc092-midrun-clarify-dispatch.test.ts（路径烘焙、零 env）。
function gateMockSource(paths: {
  planFile: string
  stateDir: string
  gates: Record<string, string>
}): string {
  return `// generated by rfc092-midrun-review-iterate.test.ts — gate-driven mock opencode
import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
const PLAN_FILE = ${JSON.stringify(paths.planFile)}
const STATE_DIR = ${JSON.stringify(paths.stateDir)}
const GATES: Record<string, string> = ${JSON.stringify(paths.gates)}
const argv = process.argv.slice(2)
if (argv.includes('--version')) { process.stdout.write('midrun-gate-mock 1.14.99\\n'); process.exit(0) }
if (argv[0] !== 'run') { process.stderr.write('midrun-gate-mock: expected run\\n'); process.exit(2) }
const ai = argv.indexOf('--agent')
const agent = ai >= 0 ? (argv[ai + 1] ?? '') : ''
if (agent === '') { process.stderr.write('midrun-gate-mock: missing --agent\\n'); process.exit(2) }
mkdirSync(STATE_DIR, { recursive: true })
const counterFile = join(STATE_DIR, 'count-' + agent)
let n = 0
if (existsSync(counterFile)) n = Number(readFileSync(counterFile, 'utf-8').trim()) || 0
const callIndex = n
writeFileSync(counterFile, String(n + 1))
const capturedArgv = process.platform === 'win32' ? [argv[0] ?? 'run', (function () { try { return readFileSync(0, 'utf-8') } catch { return '' } })(), ...argv.slice(1)] : argv
appendFileSync(join(STATE_DIR, 'argv.jsonl'), JSON.stringify({ agent, callIndex, argv: capturedArgv }) + '\\n')
const gate = GATES[agent]
if (gate !== undefined) {
  const deadline = Date.now() + 20000
  while (!existsSync(gate)) {
    if (Date.now() > deadline) { process.stderr.write('midrun-gate-mock: gate timeout\\n'); process.exit(1) }
    await Bun.sleep(25)
  }
}
const plan = JSON.parse(readFileSync(PLAN_FILE, 'utf-8')) as Record<string, Array<Record<string, unknown>>>
const steps = plan[agent] ?? []
const step = steps.length > 0 ? steps[Math.min(callIndex, steps.length - 1)]! : { output: { out: 'default-' + agent } }
function emit(text: string): void {
  process.stdout.write(JSON.stringify({ type: 'text', timestamp: Date.now(), part: { type: 'text', text } }) + '\\n')
}
if (step.clarify !== undefined) {
  emit('<workflow-clarify>' + JSON.stringify(step.clarify) + '</workflow-clarify>')
  process.exit(0)
}
const outputs = (step.output ?? {}) as Record<string, string>
let envelope = '<workflow-output>\\n'
for (const [p, c] of Object.entries(outputs)) envelope += '  <port name="' + p + '">' + c + '</port>\\n'
envelope += '</workflow-output>'
emit(envelope)
process.exit(0)
`
}

interface Harness {
  db: DbClient
  appHome: string
  repoPath: string
  worktreePath: string
  stateDir: string
  planFile: string
  gateFile: string
  mockPath: string
  cleanup: () => void
}

async function buildHarness(): Promise<Harness> {
  const appHome = mkdtempSync(join(tmpdir(), 'aw-rfc092-review-'))
  const repoPath = join(appHome, 'repo')
  const worktreePath = join(appHome, 'wt')
  const stateDir = join(appHome, 'mock-state')
  const planFile = join(appHome, 'plan.json')
  const gateFile = join(appHome, 'slow-gate')
  const mockPath = join(appHome, 'gate-mock.ts')
  mkdirSync(repoPath, { recursive: true })
  mkdirSync(worktreePath, { recursive: true })
  mkdirSync(stateDir, { recursive: true })
  await runGit(repoPath, ['init', '-b', 'main'])
  await runGit(repoPath, ['config', 'user.email', 't@t.test'])
  await runGit(repoPath, ['config', 'user.name', 't'])
  writeFileSync(join(repoPath, 'README.md'), '# r\n')
  await runGit(repoPath, ['add', '.'])
  await runGit(repoPath, ['commit', '-m', 'init'])
  await runGit(worktreePath, ['init', '-b', 'main'])
  await runGit(worktreePath, ['config', 'user.email', 't@t.test'])
  await runGit(worktreePath, ['config', 'user.name', 't'])
  writeFileSync(join(worktreePath, 'r.md'), '# r\n')
  await runGit(worktreePath, ['add', '.'])
  await runGit(worktreePath, ['commit', '-m', 'init'])
  writeFileSync(mockPath, gateMockSource({ planFile, stateDir, gates: { slow: gateFile } }))
  const db = createInMemoryDb(MIGRATIONS)
  return {
    db,
    appHome,
    repoPath,
    worktreePath,
    stateDir,
    planFile,
    gateFile,
    mockPath,
    cleanup: () => rimrafDir(appHome),
  }
}

async function seedAgent(db: DbClient, name: string, outputs: string[]): Promise<void> {
  await db.insert(agents).values({
    id: ulid(),
    name,
    description: 'test',
    outputs: JSON.stringify(outputs),
    permission: '{}',
    skills: '[]',
    frontmatterExtra: '{}',
    bodyMd: '',
  })
}

async function seedWorkflowAndTask(
  h: Harness,
  definition: WorkflowDefinition,
  inputs: Record<string, string>,
): Promise<string> {
  const workflowId = ulid()
  const taskId = ulid()
  await h.db.insert(workflows).values({
    id: workflowId,
    name: 'wf-rfc092-s1-review',
    definition: JSON.stringify(definition),
  })
  await h.db.insert(tasks).values({
    name: 'rfc092-midrun-review-iterate',
    id: taskId,
    workflowId,
    workflowSnapshot: JSON.stringify(definition),
    repoPath: h.repoPath,
    worktreePath: h.worktreePath,
    baseBranch: 'main',
    branch: `agent-workflow/${taskId}`,
    status: 'pending',
    inputs: JSON.stringify(inputs),
    startedAt: Date.now(),
  })
  return taskId
}

async function waitFor<T>(
  probe: () => Promise<T | undefined>,
  what: string,
  timeoutMs = 10_000,
): Promise<T> {
  const deadline = Date.now() + timeoutMs
  for (;;) {
    const v = await probe()
    if (v !== undefined) return v
    if (Date.now() > deadline) throw new Error(`timed out waiting for ${what}`)
    await Bun.sleep(25)
  }
}

async function topLevelRuns(db: DbClient, taskId: string, nodeId: string) {
  const rows = await db
    .select()
    .from(nodeRuns)
    .where(and(eq(nodeRuns.taskId, taskId), eq(nodeRuns.nodeId, nodeId)))
  return rows.filter((r) => r.parentNodeRunId === null)
}

function readSpawns(stateDir: string): Array<{ agent: string; callIndex: number; prompt: string }> {
  const raw = readFileSync(join(stateDir, 'argv.jsonl'), 'utf-8')
  return raw
    .split('\n')
    .filter((l) => l.trim().length > 0)
    .map((l) => {
      const row = JSON.parse(l) as { agent: string; callIndex: number; argv: string[] }
      return { agent: row.agent, callIndex: row.callIndex, prompt: row.argv[1] ?? '' }
    })
}

const ITERATE_COMMENT = 'midrun-iterate-feedback: tighten the intro'

// in → {author → review, slow}。review 经 inputSource 读 author.draft。
function reviewDiamondDef(): WorkflowDefinition {
  return {
    $schema_version: 3,
    inputs: [{ kind: 'text', key: 'req', label: 'r' }],
    nodes: [
      { id: 'in1', kind: 'input', inputKey: 'req' } as WorkflowNode,
      { id: 'author', kind: 'agent-single', agentName: 'author' } as WorkflowNode,
      {
        id: 'rev',
        kind: 'review',
        inputSource: { nodeId: 'author', portName: 'draft' },
        rerunnableOnIterate: ['author'],
        rerunnableOnReject: ['author'],
      } as unknown as WorkflowNode,
      { id: 'slow', kind: 'agent-single', agentName: 'slow' } as WorkflowNode,
    ],
    edges: [
      {
        id: 'e_in_a',
        source: { nodeId: 'in1', portName: 'req' },
        target: { nodeId: 'author', portName: 'req' },
      },
      {
        id: 'e_in_s',
        source: { nodeId: 'in1', portName: 'req' },
        target: { nodeId: 'slow', portName: 'req' },
      },
      {
        id: 'e_rev',
        source: { nodeId: 'author', portName: 'draft' },
        target: { nodeId: 'rev', portName: '__review_input__' },
      },
    ],
  }
}

describe('RFC-092 S-1 端到端 — mid-run review iterate 由活调度循环自取（不再 scheduler stalled）', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h.cleanup())

  test('slow sibling 仍在跑时 iterate → author 重跑 done、review 铸 v2 再停泊；随后 approve 推到 done', async () => {
    await seedAgent(h.db, 'author', ['draft'])
    await seedAgent(h.db, 'slow', ['out'])
    // author：第 1 次出 V1、iterate 重跑出 V2；slow：gate 放行后出 envelope。
    writeFileSync(
      h.planFile,
      JSON.stringify({
        author: [{ output: { draft: 'AUTHOR_V1' } }, { output: { draft: 'AUTHOR_V2' } }],
        slow: [{ output: { out: 'slow-done' } }],
      }),
    )
    const taskId = await seedWorkflowAndTask(h, reviewDiamondDef(), { req: 'go' })

    const runPromise = runTask({
      taskId,
      db: h.db,
      appHome: h.appHome,
      opencodeCmd: ['bun', 'run', h.mockPath],
    })

    let revRunId = ''
    try {
      // 等到「review 已停泊 awaiting_review ∧ slow 仍 running」——S-1 的提交窗口。
      const revRun = await waitFor(async () => {
        const revs = await topLevelRuns(h.db, taskId, 'rev')
        const parked = revs.find((r) => r.status === 'awaiting_review')
        if (parked === undefined) return undefined
        const slowRuns = await topLevelRuns(h.db, taskId, 'slow')
        if (slowRuns.length !== 1 || slowRuns[0]!.status !== 'running') return undefined
        return parked
      }, 'parked review while slow sibling is still running')
      revRunId = revRun.id

      // 窗口证据：任务整体仍 running（不是停泊后 resume 的旧路径）。
      const midTask = (await h.db.select().from(tasks).where(eq(tasks.id, taskId)))[0]!
      expect(midTask.status).toBe('running')

      // 真实入口：先落一条行内评论，再 iterate 打回。
      await addReviewComment({
        db: h.db,
        appHome: h.appHome,
        nodeRunId: revRunId,
        anchor: {
          sectionPath: '#',
          paragraphIdx: 0,
          offsetStart: 0,
          offsetEnd: 3,
          selectedText: 'AUT',
          contextBefore: '',
          contextAfter: '',
          occurrenceIndex: 1,
        },
        commentText: ITERATE_COMMENT,
      })
      await submitReviewDecision({
        db: h.db,
        appHome: h.appHome,
        nodeRunId: revRunId,
        decision: 'iterated',
        expectedReviewIteration: 0,
      })

      // 提交瞬间：author 的 rerun 行 pending（retryIndex+1 新铸行）、review 行
      // 原地翻回 pending（reviewIteration=1）、slow 仍在跑——确认落在窗口内。
      const authorRuns = await topLevelRuns(h.db, taskId, 'author')
      expect(authorRuns.some((r) => r.status === 'pending' && r.retryIndex === 1)).toBe(true)
      const revAfterIterate = (
        await h.db.select().from(nodeRuns).where(eq(nodeRuns.id, revRunId))
      )[0]!
      expect(revAfterIterate.status).toBe('pending')
      expect(revAfterIterate.reviewIteration).toBe(1)
      const slowAtSubmit = (await topLevelRuns(h.db, taskId, 'slow'))[0]!
      expect(slowAtSubmit.status).toBe('running')
    } finally {
      // 无论上面成败都放行 slow，避免 mock 等满 20s 才退出。
      writeFileSync(h.gateFile, 'go\n')
      await runPromise.catch(() => {})
    }
    await runPromise

    // 正确语义（RFC-092 §1.2）：slow settle 后的 tick 经 pending-bypass 先自取
    // author 的 rerun 行、再自取翻回 pending 的 review 行 → 新一轮 review 停泊。
    // 任务以真实的 awaiting_review 收场，绝不是 'scheduler stalled' 假失败。
    const taskRow = (await h.db.select().from(tasks).where(eq(tasks.id, taskId)))[0]!
    expect(taskRow.errorMessage ?? '').not.toContain('scheduler stalled')
    expect(taskRow.status).toBe('awaiting_review')

    // author：旧 done 行被 supersede（canceled），rerun 行（retryIndex=1）done，
    // 且 rerun prompt 注入了 iterate 评论。
    const authorRuns = await topLevelRuns(h.db, taskId, 'author')
    expect(authorRuns.length).toBe(2)
    const superseded = authorRuns.find((r) => r.retryIndex === 0)!
    expect(superseded.status).toBe('canceled')
    expect(superseded.errorMessage ?? '').toContain('superseded-by-review-iterated')
    const rerun = authorRuns.find((r) => r.retryIndex === 1)!
    expect(rerun.status).toBe('done')
    expect(rerun.promptText ?? '').toContain(ITERATE_COMMENT)

    // mock 落盘 argv：author 恰被调起两次，第二次 prompt 含评论文本；slow 恰一次。
    const spawns = readSpawns(h.stateDir)
    const authorSpawns = spawns
      .filter((s) => s.agent === 'author')
      .sort((a, b) => a.callIndex - b.callIndex)
    expect(authorSpawns.length).toBe(2)
    expect(authorSpawns[1]!.prompt).toContain(ITERATE_COMMENT)
    expect(spawns.filter((s) => s.agent === 'slow').length).toBe(1)
    const slowRuns = await topLevelRuns(h.db, taskId, 'slow')
    expect(slowRuns.length).toBe(1)
    expect(slowRuns[0]!.status).toBe('done')

    // 新一轮 review：同一 node_run 行再次停泊 awaiting_review（reviewIteration=1），
    // 且铸出了 v2 doc_version（pending、内容为 AUTHOR_V2）；v1 已 iterated。
    const revFinal = (await h.db.select().from(nodeRuns).where(eq(nodeRuns.id, revRunId)))[0]!
    expect(revFinal.status).toBe('awaiting_review')
    expect(revFinal.reviewIteration).toBe(1)
    const dvs = await h.db
      .select()
      .from(docVersions)
      .where(eq(docVersions.reviewNodeRunId, revRunId))
    expect(dvs.length).toBe(2)
    const v1 = dvs.find((d) => d.versionIndex === 1)!
    const v2 = dvs.find((d) => d.versionIndex === 2)!
    expect(v1.decision).toBe('iterated')
    expect(v2.decision).toBe('pending')
    expect(readFileSync(join(h.appHome, v2.bodyPath), 'utf-8')).toContain('AUTHOR_V2')

    // 全链路推进收尾：approve v2 + 重新进调度 → 任务 done（author 不再重跑）。
    await submitReviewDecision({
      db: h.db,
      appHome: h.appHome,
      nodeRunId: revRunId,
      decision: 'approved',
      expectedReviewIteration: 1,
    })
    // RFC-097: runTask's entry CAS only claims pending tasks — reset first
    // (test stand-in for resumeTask).
    await reenterScheduler(h.db, taskId)
    await runTask({
      taskId,
      db: h.db,
      appHome: h.appHome,
      opencodeCmd: ['bun', 'run', h.mockPath],
    })
    const finalTask = (await h.db.select().from(tasks).where(eq(tasks.id, taskId)))[0]!
    expect(finalTask.status).toBe('done')
    const revDone = (await h.db.select().from(nodeRuns).where(eq(nodeRuns.id, revRunId)))[0]!
    expect(revDone.status).toBe('done')
    // approve 后没有任何 agent 被再次调起（author 仍 2 次、slow 仍 1 次）。
    const spawnsAfter = readSpawns(h.stateDir)
    expect(spawnsAfter.filter((s) => s.agent === 'author').length).toBe(2)
    expect(spawnsAfter.filter((s) => s.agent === 'slow').length).toBe(1)
  }, 20_000)
})
