import { rimrafDir } from './helpers/cleanup'
// RFC-097 — resume/retry 任务级互斥竞态 oracle（design/RFC-097-task-status-cas/design.md §3 / §7.3）。
//
// 锁定的合同（任一回归即红）：
//   1. 真并发双 resumeTask：pending CAS 前移为所有权锁（task.ts resumeTask），恰一个
//      赢者继续回滚 + kick；输者 409 code='task-not-resumable'，零副作用——node_runs
//      不出现双份新行、agent 只被派发一次、任务收敛到单一终态。
//   2. retryNode 同型：CAS 翻 pending 前移到回滚与铸占位行之前——输者不再向
//      node_runs 污染 'queued for retry' 占位行（旧顺序下双 retry 会铸两份）。
//   3. 残余语义（设计 §3 明示不修、本文件锁定意图）：CAS 单胜只保证同一状态纪元。
//      胜者 kick 的 runTask 速败（任务回到 failed）之后，第二次 resume 看到
//      from=failed 合法再胜——等价于用户连按两次 Resume，无双写者，是允许的。
//   4. isTaskActive 入口拒（audit S-8）：调度器在跑（activeTasks 持有 controller）时
//      resumeTask → 409 task-not-resumable（message 注明 actively running，证明是
//      入口闸而非状态门）；retryNode → 409 task-still-running。
//
// 确定性论证：双 resume 在同一 tick 内发起；赢者的 CAS 落账后立即进入真实 git
// 回滚（预置真实 stash sha → reset/clean/stash-apply 三次子进程 await），输者在任何
// 子进程完成之前就走完自己的 getTask + 状态门/CAS——要么 fast-path 读到 pending 409，
// 要么 CAS affected=0 ConcurrentTaskTransition 409，两条路映射同一 code。

import type { WorkflowDefinition } from '@agent-workflow/shared'
import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { eq } from 'drizzle-orm'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { ulid } from 'ulid'
import { createInMemoryDb, type DbClient } from '../src/db/client'
import { agents, nodeRuns, tasks, workflows } from '../src/db/schema'
import { cancelTask, resumeTask, retryNode } from '../src/services/task'
import { runGit } from '../src/util/git'

const MIGRATIONS = resolve(import.meta.dir, '..', 'db', 'migrations')

// ---- 自写 mock opencode（复刻 rfc095-wrapper-canceled-revival 的 text-event +
// <workflow-output> 封皮；零 env 依赖，行为只由脚本本体决定）。每次调用向
// ctrl/count-* 追加一个字符——「agent 实际被派发几次」的原子计数 oracle。

function buildDoneMock(ctrlDir: string): string {
  return `// generated by rfc097-resume-mutex.test.ts — fast-done mock.
import { appendFileSync } from 'node:fs'
appendFileSync(${JSON.stringify(ctrlDir)} + '/count-done', 'x')
const text =
  '<workflow-output>\\n  <port name="out">OK</port>\\n</workflow-output>'
process.stdout.write(
  JSON.stringify({ type: 'text', timestamp: Date.now(), part: { type: 'text', text } }) + '\\n',
)
process.exit(0)
`
}

function buildFailMock(ctrlDir: string): string {
  return `// generated by rfc097-resume-mutex.test.ts — fast-fail mock (no envelope, exit 1).
import { appendFileSync } from 'node:fs'
appendFileSync(${JSON.stringify(ctrlDir)} + '/count-fail', 'x')
process.exit(1)
`
}

function buildSlowMock(ctrlDir: string): string {
  return `// generated by rfc097-resume-mutex.test.ts — slow mock (marker + hang until SIGTERM).
import { writeFileSync } from 'node:fs'
writeFileSync(${JSON.stringify(ctrlDir)} + '/slow-started', '1')
await Bun.sleep(120000)
process.exit(1)
`
}

interface Harness {
  db: DbClient
  appHome: string
  worktreePath: string
  ctrlDir: string
  taskId: string
  failedRunId: string
  doneMock: string
  failMock: string
  slowMock: string
  cleanup: () => void
}

/**
 * 可恢复任务现场：failed 任务 + 带【真实 stash sha】preSnapshot 的 failed 行 +
 * 真实 git worktree——resume/retry 的回滚走完整 reset/clean/stash-apply 子进程
 * 链，让赢者在 CAS 之后真实地悬挂在 await 上（并发窗口为真）。
 */
async function buildHarness(): Promise<Harness> {
  const appHome = mkdtempSync(join(tmpdir(), 'aw-rfc097-mutex-'))
  const worktreePath = join(appHome, 'wt')
  const ctrlDir = join(appHome, 'ctrl')
  mkdirSync(worktreePath, { recursive: true })
  mkdirSync(ctrlDir, { recursive: true })
  await runGit(worktreePath, ['init', '-q', '-b', 'main'])
  await runGit(worktreePath, ['config', 'user.email', 't@t.test'])
  await runGit(worktreePath, ['config', 'user.name', 't'])
  writeFileSync(join(worktreePath, 'README.md'), '# r\n')
  await runGit(worktreePath, ['add', '.'])
  await runGit(worktreePath, ['commit', '-q', '-m', 'init'])
  // 真实 stash sha 作为 preSnapshot：修改已跟踪文件 → stash create → 复原。
  writeFileSync(join(worktreePath, 'README.md'), '# r\nnode-was-running\n')
  const stash = await runGit(worktreePath, ['stash', 'create', 'rfc097-pre-snapshot'])
  const stashSha = stash.stdout.trim()
  if (stashSha === '') throw new Error('harness: git stash create produced no sha')
  await runGit(worktreePath, ['checkout', '--', 'README.md'])

  const doneMock = join(ctrlDir, 'mock-done.ts')
  const failMock = join(ctrlDir, 'mock-fail.ts')
  const slowMock = join(ctrlDir, 'mock-slow.ts')
  writeFileSync(doneMock, buildDoneMock(ctrlDir))
  writeFileSync(failMock, buildFailMock(ctrlDir))
  writeFileSync(slowMock, buildSlowMock(ctrlDir))

  const db = createInMemoryDb(MIGRATIONS)
  await db.insert(agents).values({
    id: ulid(),
    name: 'worker',
    description: 'test',
    outputs: JSON.stringify(['out']),
    permission: '{}',
    skills: '[]',
    frontmatterExtra: '{}',
    bodyMd: '',
  })
  const definition: WorkflowDefinition = {
    $schema_version: 3,
    inputs: [],
    // RFC-115: retry budget via StartTaskDeps (was node.retries: 0) — fail-mock
    // 一次即败，避免调度器默认 3 次重试拖慢失败路径。预算 0 由 deps() 透传
    // defaultNodeRetries: 0 进 resumeTask / retryNode（见下）。
    nodes: [
      { id: 'work', kind: 'agent-single', agentName: 'worker' },
    ] as unknown as WorkflowDefinition['nodes'],
    edges: [],
  }
  const workflowId = ulid()
  const taskId = ulid()
  await db.insert(workflows).values({
    id: workflowId,
    name: 'wf-rfc097-mutex',
    definition: JSON.stringify(definition),
  })
  await db.insert(tasks).values({
    id: taskId,
    name: 'rfc097-mutex-task',
    workflowId,
    workflowSnapshot: JSON.stringify(definition),
    repoPath: worktreePath,
    worktreePath,
    baseBranch: 'main',
    branch: `agent-workflow/${taskId}`,
    status: 'failed',
    inputs: '{}',
    startedAt: Date.now() - 60_000,
    finishedAt: Date.now() - 30_000,
    errorSummary: 'boom',
    errorMessage: 'node work failed',
    failedNodeId: 'work',
  })
  const failedRunId = ulid()
  await db.insert(nodeRuns).values({
    id: failedRunId,
    taskId,
    nodeId: 'work',
    status: 'failed',
    retryIndex: 0,
    iteration: 0,
    preSnapshot: stashSha,
    startedAt: Date.now() - 60_000,
    finishedAt: Date.now() - 30_000,
    errorMessage: 'boom',
  })
  return {
    db,
    appHome,
    worktreePath,
    ctrlDir,
    taskId,
    failedRunId,
    doneMock,
    failMock,
    slowMock,
    cleanup: () => rimrafDir(appHome),
  }
}

function deps(h: Harness, mockPath: string) {
  // RFC-115: retry budget via StartTaskDeps (was node.retries: 0). Threaded
  // through both resumeTask and retryNode so fail-mock stays one-shot — without
  // it the scheduler's default budget (3) would inflate the count-* oracles.
  return {
    db: h.db,
    appHome: h.appHome,
    opencodeCmd: ['bun', 'run', mockPath],
    defaultNodeRetries: 0,
  }
}

async function waitFor(cond: () => boolean, what: string): Promise<void> {
  for (let i = 0; i < 400; i++) {
    if (cond()) return
    await Bun.sleep(25)
  }
  throw new Error(`timeout waiting for ${what}`)
}

async function waitForTerminalTask(
  db: DbClient,
  taskId: string,
): Promise<typeof tasks.$inferSelect> {
  for (let i = 0; i < 400; i++) {
    const t = (await db.select().from(tasks).where(eq(tasks.id, taskId)))[0]
    if (t !== undefined && t.status !== 'pending' && t.status !== 'running') return t
    await Bun.sleep(25)
  }
  throw new Error(`task ${taskId} did not reach a terminal status within budget`)
}

function rejectionOf(results: PromiseSettledResult<unknown>[]): {
  code?: string
  status?: number
  message?: string
} {
  const r = results.find((x) => x.status === 'rejected') as PromiseRejectedResult
  const err = r.reason as { code?: string; status?: number; message?: string }
  return { code: err.code, status: err.status, message: err.message }
}

describe('RFC-097 — resume/retry 任务级互斥（并发恰一胜 + 零污染 + 残余语义）', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h.cleanup())

  test('真并发双 resumeTask：恰一个 fulfilled、一个 409 task-not-resumable；无双铸行、单次派发、单一终态', async () => {
    const results = await Promise.allSettled([
      resumeTask(h.db, h.taskId, deps(h, h.doneMock)),
      resumeTask(h.db, h.taskId, deps(h, h.doneMock)),
    ])

    expect(results.filter((r) => r.status === 'fulfilled')).toHaveLength(1)
    expect(results.filter((r) => r.status === 'rejected')).toHaveLength(1)
    const loser = rejectionOf(results)
    expect(loser.code).toBe('task-not-resumable')
    expect(loser.status).toBe(409)

    // 赢者跑完整个生命周期 → 单一终态 done（错误字段被 resume 清空后未再写入）。
    const final = await waitForTerminalTask(h.db, h.taskId)
    expect(`${final.status}:${final.errorSummary ?? ''}`).toBe('done:')

    // node_runs 无双份新行：seed failed(retryIndex 0) + 调度器恰一份新行，
    // retryIndex 不重复——若两个调度器都被 kick，这里会出现重复 retryIndex / 第三行。
    const rows = await h.db.select().from(nodeRuns).where(eq(nodeRuns.taskId, h.taskId))
    const workRows = rows.filter((r) => r.nodeId === 'work')
    expect(workRows).toHaveLength(2)
    expect(workRows.map((r) => r.retryIndex).sort()).toEqual([0, 1])
    expect(workRows.filter((r) => r.status === 'done')).toHaveLength(1)

    // agent 实际只被派发一次（mock 调用计数 oracle）。
    expect(readFileSync(join(h.ctrlDir, 'count-done'), 'utf-8')).toBe('x')
  }, 30000)

  test('真并发双 retryNode：恰一胜（409 task-still-running）；输者零占位行污染', async () => {
    const opts = (mock: string) => ({ cascade: true, deps: deps(h, mock) })
    const results = await Promise.allSettled([
      retryNode(h.db, h.taskId, h.failedRunId, opts(h.doneMock)),
      retryNode(h.db, h.taskId, h.failedRunId, opts(h.doneMock)),
    ])

    expect(results.filter((r) => r.status === 'fulfilled')).toHaveLength(1)
    expect(results.filter((r) => r.status === 'rejected')).toHaveLength(1)
    const loser = rejectionOf(results)
    expect(loser.code).toBe('task-still-running')
    expect(loser.status).toBe(409)

    const final = await waitForTerminalTask(h.db, h.taskId)
    expect(`${final.status}:${final.errorSummary ?? ''}`).toBe('done:')

    // 占位行 oracle：retryNode 赢者恰铸 1 行 errorMessage='queued for retry'；
    // 输者在 CAS 处出局（回滚与铸行都在 CAS 之后），不得多铸。
    const rows = await h.db.select().from(nodeRuns).where(eq(nodeRuns.taskId, h.taskId))
    const placeholders = rows.filter((r) => r.errorMessage === 'queued for retry')
    expect(placeholders).toHaveLength(1)
    // retryIndex 全局不重复（双调度器的另一种污染形态）。
    const indexes = rows.filter((r) => r.nodeId === 'work').map((r) => r.retryIndex)
    expect(new Set(indexes).size).toBe(indexes.length)
    expect(readFileSync(join(h.ctrlDir, 'count-done'), 'utf-8')).toBe('x')
  }, 30000)

  test('残余语义锁定：胜者速败（任务回到 failed）之后，顺序第二次 resume 合法再胜', async () => {
    // 第一次 resume：fail-mock 速败 → 任务完整生命周期收敛回 failed。
    await resumeTask(h.db, h.taskId, deps(h, h.failMock))
    const afterFirst = await waitForTerminalTask(h.db, h.taskId)
    expect(afterFirst.status).toBe('failed')
    expect(readFileSync(join(h.ctrlDir, 'count-fail'), 'utf-8')).toBe('x')

    // 第二次 resume（非并发，胜者生命周期已结束）：from=failed 合法——CAS 单胜
    // 只保证同一状态纪元，这等价于用户连按两次 Resume，设计 §3 明示允许。
    const second = await resumeTask(h.db, h.taskId, deps(h, h.doneMock))
    expect(second.status).toBe('pending')
    const final = await waitForTerminalTask(h.db, h.taskId)
    expect(`${final.status}:${final.errorSummary ?? ''}`).toBe('done:')
  }, 30000)

  test('isTaskActive 入口拒：调度器挂起期间 resumeTask → 409（actively running）；retryNode → 409 task-still-running', async () => {
    await resumeTask(h.db, h.taskId, deps(h, h.slowMock))
    await waitFor(() => existsSync(join(h.ctrlDir, 'slow-started')), 'slow mock spawn')

    // resume 入口闸：message 注明 actively running——证明拒绝来自 isTaskActive
    // 入口（status 此刻是 running，状态门也会拒，但 message 不同）。
    let resumeErr: { code?: string; message?: string } | undefined
    try {
      await resumeTask(h.db, h.taskId, deps(h, h.doneMock))
    } catch (err) {
      resumeErr = err as { code?: string; message?: string }
    }
    expect(resumeErr?.code).toBe('task-not-resumable')
    expect(resumeErr?.message ?? '').toContain('actively running')

    let retryErr: { code?: string; message?: string } | undefined
    try {
      await retryNode(h.db, h.taskId, h.failedRunId, { cascade: true, deps: deps(h, h.doneMock) })
    } catch (err) {
      retryErr = err as { code?: string; message?: string }
    }
    expect(retryErr?.code).toBe('task-still-running')
    expect(retryErr?.message ?? '').toContain('active scheduler')

    // 收尾：取消挂起的调度器，等它真正落终态（避免后台 runTask 泄漏到下个用例）。
    await cancelTask(h.db, h.taskId)
    const final = await waitForTerminalTask(h.db, h.taskId)
    expect(final.status).toBe('canceled')
  }, 30000)
})
