// RFC-097 — pending 孤儿任务的 boot 收割 + 恢复（design/RFC-097-task-status-cas/
// design.md §3「崩溃窗口补偿」）。
//
// 背景：resumeTask/retryNode 的 pending CAS 前移为所有权锁之后，「回滚中途 daemon
// 崩溃」会留下 status='pending' 但无人认领的任务（boot 前 activeTasks 为空，旧收割
// 只翻 running）。补偿：reapOrphanRuns 增加 pending→interrupted 任务收割分支——
// boot 在 HTTP listen 之前运行（src/cli/start.ts:138，步骤 5b 早于 token/serve），
// 彼刻一切 pending 任务必为孤儿：startTask 是 insert 后同进程立即 kick，不存在
// 「boot 时合法存活的 pending 任务」窗口，零误伤（design §3）。
//
// 锁定的合同：
//   1. pending 残留 → reap 翻 interrupted（errorSummary='daemon-restart'）→
//      resumeTask 从 interrupted 合法恢复并跑到终态——崩溃自愈闭环。
//   2. 对照：boot 收割之后经 startTask 正常发起的任务完全不受影响（其 pending
//      窗口在 boot 之后、同进程内，收割摸不到它），照常跑到 done。

import type { WorkflowDefinition } from '@agent-workflow/shared'
import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { eq } from 'drizzle-orm'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { ulid } from 'ulid'
import { createInMemoryDb, type DbClient } from '../src/db/client'
import { agents, nodeRuns, tasks, workflows } from '../src/db/schema'
import { reapOrphanRuns } from '../src/services/orphans'
import { resumeTask, startTaskWithLocalRepo } from '../src/services/task'
import { runGit } from '../src/util/git'

const MIGRATIONS = resolve(import.meta.dir, '..', 'db', 'migrations')

function buildDoneMock(): string {
  return `// generated by rfc097-pending-orphan-reap.test.ts — fast-done mock.
const __awArgv = process.argv.slice(2)
const prompt = __awArgv.includes('--') ? __awArgv.slice(__awArgv.indexOf('--') + 1).join(' ') : (__awArgv[1] ?? '')
const nonce = /\\bnonce="([^"]+)"/.exec(prompt)?.[1]
const outputOpen =
  nonce === undefined ? '<workflow-output>' : '<workflow-output nonce="' + nonce + '">'
const text =
  outputOpen + '\\n  <port name="out">OK</port>\\n</workflow-output>'
process.stdout.write(
  JSON.stringify({ type: 'text', timestamp: Date.now(), part: { type: 'text', text } }) + '\\n',
)
process.exit(0)
`
}

interface Harness {
  db: DbClient
  appHome: string
  repoPath: string
  workflowId: string
  doneMock: string
  cleanup: () => void
}

async function buildHarness(): Promise<Harness> {
  const appHome = mkdtempSync(join(tmpdir(), 'aw-rfc097-reap-'))
  const repoPath = join(appHome, 'repo')
  mkdirSync(repoPath, { recursive: true })
  await runGit(repoPath, ['init', '-q', '-b', 'main'])
  await runGit(repoPath, ['config', 'user.email', 't@t.test'])
  await runGit(repoPath, ['config', 'user.name', 't'])
  writeFileSync(join(repoPath, 'README.md'), '# r\n')
  await runGit(repoPath, ['add', '.'])
  await runGit(repoPath, ['commit', '-q', '-m', 'init'])

  const doneMock = join(appHome, 'mock-done.ts')
  writeFileSync(doneMock, buildDoneMock())

  const db = createInMemoryDb(MIGRATIONS)
  await db.insert(agents).values({
    id: ulid(),
    name: 'worker',
    description: 'test',
    outputs: JSON.stringify(['out']),
    permission: '{}',
    skills: '[]',
    frontmatterExtra: '{}',
    bodyMd: '',
  })
  const definition: WorkflowDefinition = {
    $schema_version: 3,
    inputs: [],
    nodes: [
      { id: 'work', kind: 'agent-single', agentName: 'worker' },
    ] as unknown as WorkflowDefinition['nodes'],
    edges: [],
  }
  const workflowId = ulid()
  await db.insert(workflows).values({
    id: workflowId,
    name: 'wf-rfc097-reap',
    definition: JSON.stringify(definition),
  })
  return {
    db,
    appHome,
    repoPath,
    workflowId,
    doneMock,
    cleanup: () => rmSync(appHome, { recursive: true, force: true }),
  }
}

/** 模拟「resume 已 CAS 翻 pending、回滚中途 daemon 崩溃」的残留现场：任务 pending
 *  且错误四元组已被 resume 清空，节点行仍是历史 failed（resumeTask 不改行状态）。 */
async function seedCrashedResumeResidue(h: Harness): Promise<{ taskId: string; runId: string }> {
  const taskId = ulid()
  const def = (await h.db.select().from(workflows).where(eq(workflows.id, h.workflowId)))[0]!
    .definition
  await h.db.insert(tasks).values({
    id: taskId,
    name: 'rfc097-crashed-resume',
    workflowId: h.workflowId,
    workflowSnapshot: def,
    repoPath: h.repoPath,
    worktreePath: h.repoPath,
    baseBranch: 'main',
    branch: `agent-workflow/${taskId}`,
    status: 'pending',
    inputs: '{}',
    startedAt: Date.now() - 60_000,
    finishedAt: null,
    errorSummary: null,
    errorMessage: null,
  })
  const runId = ulid()
  await h.db.insert(nodeRuns).values({
    id: runId,
    taskId,
    nodeId: 'work',
    status: 'failed',
    retryIndex: 0,
    iteration: 0,
    startedAt: Date.now() - 60_000,
    finishedAt: Date.now() - 30_000,
    errorMessage: 'boom',
  })
  return { taskId, runId }
}

async function waitForTerminalTask(
  db: DbClient,
  taskId: string,
): Promise<typeof tasks.$inferSelect> {
  for (let i = 0; i < 400; i++) {
    const t = (await db.select().from(tasks).where(eq(tasks.id, taskId)))[0]
    if (t !== undefined && t.status !== 'pending' && t.status !== 'running') return t
    await Bun.sleep(25)
  }
  throw new Error(`task ${taskId} did not reach a terminal status within budget`)
}

describe('RFC-097 — pending 孤儿任务收割 → interrupted → resume 自愈闭环', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h.cleanup())

  test('resume 中途崩溃残留的 pending 任务：reap 翻 interrupted(daemon-restart)，resumeTask 恢复跑到终态', async () => {
    const { taskId, runId } = await seedCrashedResumeResidue(h)

    const r = await reapOrphanRuns(h.db)
    expect(r.tasks).toBe(1)
    // 节点行是历史 failed（不在 running/pending 收割集）→ 行侧零收割。
    expect(r.runs).toBe(0)

    const reaped = (await h.db.select().from(tasks).where(eq(tasks.id, taskId)))[0]!
    expect(reaped.status).toBe('interrupted')
    expect(reaped.errorSummary).toBe('daemon-restart')
    expect(reaped.errorMessage ?? '').toContain('daemon restarted')
    expect(reaped.finishedAt).not.toBeNull()
    const failedRow = (await h.db.select().from(nodeRuns).where(eq(nodeRuns.id, runId)))[0]!
    expect(failedRow.status).toBe('failed') // 历史行原样保留

    // 自愈闭环：interrupted 在 resumeTask 的可恢复集里——用户（或修复工具）一次
    // Resume 即可把崩溃残留任务跑到终态。
    const resumed = await resumeTask(h.db, taskId, {
      db: h.db,
      appHome: h.appHome,
      opencodeCmd: ['bun', 'run', h.doneMock],
      // RFC-115: retry budget via StartTaskDeps (was node.retries: 0).
      defaultNodeRetries: 0,
    })
    expect(resumed.status).toBe('pending')
    const final = await waitForTerminalTask(h.db, taskId)
    expect(`${final.status}:${final.errorSummary ?? ''}`).toBe('done:')
  }, 30000)

  test('对照：boot 收割之后 startTask 的正常路径不受影响（pending 窗口在 boot 后、同进程内）', async () => {
    // boot 时库里没有任何任务 → 收割零命中（design §3：boot 在 HTTP listen 之前，
    // 彼刻不可能存在合法 pending 任务；startTask 的 pending 窗口只出现在 boot 之后
    // 且 insert 后同进程立即 kick，收割永远摸不到它）。
    const boot = await reapOrphanRuns(h.db)
    expect(boot).toEqual({ tasks: 0, runs: 0 })

    const task = await startTaskWithLocalRepo(
      {
        workflowId: h.workflowId,
        name: 'rfc097-normal-launch',
        repoPath: h.repoPath,
        baseBranch: 'main',
        inputs: {},
      },
      {
        db: h.db,
        appHome: h.appHome,
        opencodeCmd: ['bun', 'run', h.doneMock],
        awaitScheduler: true,
        // RFC-115: retry budget via StartTaskDeps (was node.retries: 0).
        defaultNodeRetries: 0,
      },
    )
    expect(`${task.status}:${task.errorSummary ?? ''}`).toBe('done:')
  }, 30000)
})
