// RFC-098 B3（audit S-3 + RFC-092 已知限制解除）端到端验收 — 修复后正确语义锁定。
//
// 三个场景（修复前全部 RED）：
//
//   1. approve-inside-loop：loop ∋ {designer, review}。review approve 后只
//      resume 一次任务即自动推进到 done。修复前 approve 不铸任何 pending 行，
//      wrapper awaiting_review 行的唯一放行通道 wrapperHasFreshInnerWork 只认
//      pending → 无论 resume 多少次都弹回 awaiting_review（双 resume 也救不
//      回）。修复后 wrapperRevivalEvidence 认「窗口内 review done∧fresh 行」
//      为复活证据。
//
//   2. approve-inside-git：wrapper-git 同型 + git_diff 恰写一次。
//
//   3. mid-run：菱形 in → {loop ∋ {asker, clarify}, slow}。slow sibling 仍在
//      跑时答 clarify → 活调度循环自取 → 任务自动 done，**不需要手动 resume**。
//      这正是 design/RFC-092-…/design.md §「已知限制」记录的形态：bypass 只
//      豁免 pending 行不豁免 wrapper awaiting_* 行 → 修复前任务停泊
//      awaiting_human（inbox 已空）等人工 resume。修复 = deriveFrontier 的
//      wrapperAnchorReleasable（证据行 id 一次性豁免，scheduler.ts）。
//
// 时序确定性：gate 文件慢 mock（同 rfc092-midrun-clarify-dispatch.test.ts），
// 测试侧轮询 DB 状态，绝不裸 sleep 赌时机。

import type { ClarifyAnswer, WorkflowDefinition, WorkflowNode } from '@agent-workflow/shared'
import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { and, eq } from 'drizzle-orm'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { monotonicFactory } from 'ulid'
const ulid = monotonicFactory()
import { createInMemoryDb, type DbClient } from '../src/db/client'
import {
  agents,
  clarifySessions,
  nodeRunOutputs,
  nodeRuns,
  tasks,
  workflows,
} from '../src/db/schema'
import { submitClarifyAnswers } from '../src/services/clarify'
import { submitReviewDecision } from '../src/services/review'
import { runTask } from '../src/services/scheduler'
import { runGit } from '../src/util/git'
import { reenterScheduler } from './reenter-scheduler'

const MIGRATIONS = resolve(import.meta.dir, '..', 'db', 'migrations')

// gate 慢 mock（生成式，plan/state/gate 路径烘焙进脚本——同
// rfc092-midrun-clarify-dispatch.test.ts 的形态，零 process.env 串扰）。
function gateMockSource(paths: {
  planFile: string
  stateDir: string
  gates: Record<string, string>
}): string {
  return `// generated by rfc098-wrapper-revival-e2e.test.ts — gate-driven mock opencode
import { appendFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
const PLAN_FILE = ${JSON.stringify(paths.planFile)}
const STATE_DIR = ${JSON.stringify(paths.stateDir)}
const GATES: Record<string, string> = ${JSON.stringify(paths.gates)}
const argv = process.argv.slice(2)
if (argv.includes('--version')) { process.stdout.write('rfc098-gate-mock 1.14.99\\n'); process.exit(0) }
if (argv[0] !== 'run') { process.stderr.write('rfc098-gate-mock: expected run\\n'); process.exit(2) }
const ai = argv.indexOf('--agent')
const agent = ai >= 0 ? (argv[ai + 1] ?? '') : ''
if (agent === '') { process.stderr.write('rfc098-gate-mock: missing --agent\\n'); process.exit(2) }
mkdirSync(STATE_DIR, { recursive: true })
const counterFile = join(STATE_DIR, 'count-' + agent)
let n = 0
if (existsSync(counterFile)) n = Number(readFileSync(counterFile, 'utf-8').trim()) || 0
const callIndex = n
writeFileSync(counterFile, String(n + 1))
appendFileSync(join(STATE_DIR, 'argv.jsonl'), JSON.stringify({ agent, callIndex }) + '\\n')
const gate = GATES[agent]
if (gate !== undefined) {
  const deadline = Date.now() + 20000
  while (!existsSync(gate)) {
    if (Date.now() > deadline) { process.stderr.write('rfc098-gate-mock: gate timeout\\n'); process.exit(1) }
    await Bun.sleep(25)
  }
}
const plan = JSON.parse(readFileSync(PLAN_FILE, 'utf-8')) as Record<string, Array<Record<string, unknown>>>
const steps = plan[agent] ?? []
const step = steps.length > 0 ? steps[Math.min(callIndex, steps.length - 1)]! : { output: { out: 'default-' + agent } }
function emit(text: string): void {
  process.stdout.write(JSON.stringify({ type: 'text', timestamp: Date.now(), part: { type: 'text', text } }) + '\\n')
}
if (step.clarify !== undefined) {
  emit('<workflow-clarify>' + JSON.stringify(step.clarify) + '</workflow-clarify>')
  process.exit(0)
}
const outputs = (step.output ?? {}) as Record<string, string>
let envelope = '<workflow-output>\\n'
for (const [p, c] of Object.entries(outputs)) envelope += '  <port name="' + p + '">' + c + '</port>\\n'
envelope += '</workflow-output>'
emit(envelope)
process.exit(0)
`
}

interface Harness {
  db: DbClient
  appHome: string
  repoPath: string
  worktreePath: string
  stateDir: string
  planFile: string
  gateFile: string
  mockPath: string
  cleanup: () => void
}

async function buildHarness(): Promise<Harness> {
  const appHome = mkdtempSync(join(tmpdir(), 'aw-rfc098-revival-'))
  const repoPath = join(appHome, 'repo')
  const worktreePath = join(appHome, 'wt')
  const stateDir = join(appHome, 'mock-state')
  const planFile = join(appHome, 'plan.json')
  const gateFile = join(appHome, 'slow-gate')
  const mockPath = join(appHome, 'gate-mock.ts')
  mkdirSync(repoPath, { recursive: true })
  mkdirSync(worktreePath, { recursive: true })
  mkdirSync(stateDir, { recursive: true })
  await runGit(repoPath, ['init', '-b', 'main'])
  await runGit(repoPath, ['config', 'user.email', 't@t.test'])
  await runGit(repoPath, ['config', 'user.name', 't'])
  writeFileSync(join(repoPath, 'README.md'), '# r\n')
  await runGit(repoPath, ['add', '.'])
  await runGit(repoPath, ['commit', '-m', 'init'])
  await runGit(worktreePath, ['init', '-b', 'main'])
  await runGit(worktreePath, ['config', 'user.email', 't@t.test'])
  await runGit(worktreePath, ['config', 'user.name', 't'])
  writeFileSync(join(worktreePath, 'r.md'), '# r\n')
  await runGit(worktreePath, ['add', '.'])
  await runGit(worktreePath, ['commit', '-m', 'init'])
  writeFileSync(mockPath, gateMockSource({ planFile, stateDir, gates: { slow: gateFile } }))
  const db = createInMemoryDb(MIGRATIONS)
  return {
    db,
    appHome,
    repoPath,
    worktreePath,
    stateDir,
    planFile,
    gateFile,
    mockPath,
    cleanup: () => rmSync(appHome, { recursive: true, force: true }),
  }
}

async function seedAgent(db: DbClient, name: string, outputs: string[]): Promise<void> {
  await db.insert(agents).values({
    id: ulid(),
    name,
    description: 'test',
    outputs: JSON.stringify(outputs),
    permission: '{}',
    skills: '[]',
    frontmatterExtra: '{}',
    bodyMd: '',
  })
}

async function seedWorkflowAndTask(
  h: Harness,
  definition: WorkflowDefinition,
  inputs: Record<string, string>,
): Promise<string> {
  const workflowId = ulid()
  const taskId = ulid()
  await h.db.insert(workflows).values({
    id: workflowId,
    name: 'wf-rfc098-revival',
    definition: JSON.stringify(definition),
  })
  await h.db.insert(tasks).values({
    name: 'rfc098-wrapper-revival',
    id: taskId,
    workflowId,
    workflowSnapshot: JSON.stringify(definition),
    repoPath: h.repoPath,
    worktreePath: h.worktreePath,
    baseBranch: 'main',
    branch: `agent-workflow/${taskId}`,
    status: 'pending',
    inputs: JSON.stringify(inputs),
    startedAt: Date.now(),
  })
  return taskId
}

async function waitFor<T>(
  probe: () => Promise<T | undefined>,
  what: string,
  timeoutMs = 10_000,
): Promise<T> {
  const deadline = Date.now() + timeoutMs
  for (;;) {
    const v = await probe()
    if (v !== undefined) return v
    if (Date.now() > deadline) throw new Error(`timed out waiting for ${what}`)
    await Bun.sleep(25)
  }
}

async function nodeRows(db: DbClient, taskId: string, nodeId: string) {
  const rows = await db
    .select()
    .from(nodeRuns)
    .where(and(eq(nodeRuns.taskId, taskId), eq(nodeRuns.nodeId, nodeId)))
  return rows.filter((r) => r.parentNodeRunId === null)
}

async function taskStatus(db: DbClient, taskId: string): Promise<string> {
  return (await db.select().from(tasks).where(eq(tasks.id, taskId)))[0]!.status
}

// loop ∋ {designer, rev}：review 通过即退出循环并导出 approved_doc。
function approveInLoopDef(): WorkflowDefinition {
  return {
    $schema_version: 3,
    inputs: [{ kind: 'text', key: 'topic', label: 't' }],
    nodes: [
      { id: 'in1', kind: 'input', inputKey: 'topic' } as WorkflowNode,
      { id: 'designer', kind: 'agent-single', agentName: 'designer' } as WorkflowNode,
      {
        id: 'rev',
        kind: 'review',
        inputSource: { nodeId: 'designer', portName: 'design' },
        rerunnableOnIterate: ['designer'],
        rerunnableOnReject: ['designer'],
      } as unknown as WorkflowNode,
      {
        id: 'loop',
        kind: 'wrapper-loop',
        nodeIds: ['designer', 'rev'],
        maxIterations: 3,
        exitCondition: { kind: 'port-not-empty', nodeId: 'rev', portName: 'approved_doc' },
        outputBindings: [{ name: 'final', bind: { nodeId: 'rev', portName: 'approved_doc' } }],
      } as unknown as WorkflowNode,
    ],
    edges: [
      {
        id: 'e_in',
        source: { nodeId: 'in1', portName: 'topic' },
        target: { nodeId: 'designer', portName: 'topic' },
      },
      {
        id: 'e_rev',
        source: { nodeId: 'designer', portName: 'design' },
        target: { nodeId: 'rev', portName: '__review_input__' },
      },
    ],
  }
}

describe('RFC-098 B3 — approve-inside-wrapper 复活（S-3 端到端）', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h.cleanup())

  test('approve-inside-loop：approve 后单次 resume 即自动推进到 done（不需要双 resume）', async () => {
    await seedAgent(h.db, 'designer', ['design'])
    writeFileSync(h.planFile, JSON.stringify({ designer: [{ output: { design: 'DESIGN_V1' } }] }))
    const taskId = await seedWorkflowAndTask(h, approveInLoopDef(), { topic: 'x' })

    // 第一遍：designer 出稿 → review 在 loop 计数器 0 停泊 → wrapper 翻
    // awaiting_review → 任务 awaiting_review。
    await runTask({ taskId, db: h.db, appHome: h.appHome, opencodeCmd: ['bun', 'run', h.mockPath] })
    expect(await taskStatus(h.db, taskId)).toBe('awaiting_review')
    const loopBefore = await nodeRows(h.db, taskId, 'loop')
    expect(loopBefore).toHaveLength(1)
    expect(loopBefore[0]!.status).toBe('awaiting_review')
    const wrapperRunId = loopBefore[0]!.id
    const rev = (await nodeRows(h.db, taskId, 'rev')).find((r) => r.status === 'awaiting_review')
    expect(rev).toBeDefined()

    // approve（不铸任何 pending 行——done∧fresh 的 review 行本身就是复活证据）。
    await submitReviewDecision({
      db: h.db,
      appHome: h.appHome,
      nodeRunId: rev!.id,
      decision: 'approved',
      expectedReviewIteration: rev!.reviewIteration,
    })

    // 单次 resume（reenterScheduler + runTask = resumeTask 的测试替身）。
    // 修复前这一遍恒弹回 awaiting_review（wrapperHasFreshInnerWork 只认
    // pending）；修复后 review done∧fresh 证据放行 wrapper → 续跑 → done。
    await reenterScheduler(h.db, taskId)
    await runTask({ taskId, db: h.db, appHome: h.appHome, opencodeCmd: ['bun', 'run', h.mockPath] })
    expect(await taskStatus(h.db, taskId)).toBe('done')

    // wrapper 行同行复用、终态 done，outputBinding 导出 approved_doc。
    const loopAfter = await nodeRows(h.db, taskId, 'loop')
    expect(loopAfter).toHaveLength(1)
    expect(loopAfter[0]!.id).toBe(wrapperRunId)
    expect(loopAfter[0]!.status).toBe('done')
    const outs = await h.db
      .select()
      .from(nodeRunOutputs)
      .where(eq(nodeRunOutputs.nodeRunId, wrapperRunId))
    expect(outs.find((o) => o.portName === 'final')?.content).toContain('DESIGN_V1')

    // designer 不被多余重跑：恰一次 spawn（approve 不应触发 stale 重派）。
    const designerRuns = await nodeRows(h.db, taskId, 'designer')
    expect(designerRuns).toHaveLength(1)
    expect(designerRuns[0]!.status).toBe('done')
  }, 20_000)

  test('approve-inside-git：approve 后单次 resume → done，git_diff 恰写一次', async () => {
    await seedAgent(h.db, 'designer', ['design'])
    writeFileSync(h.planFile, JSON.stringify({ designer: [{ output: { design: 'DESIGN_V1' } }] }))
    const def: WorkflowDefinition = {
      $schema_version: 3,
      inputs: [{ kind: 'text', key: 'topic', label: 't' }],
      nodes: [
        { id: 'in1', kind: 'input', inputKey: 'topic' } as WorkflowNode,
        { id: 'designer', kind: 'agent-single', agentName: 'designer' } as WorkflowNode,
        {
          id: 'rev',
          kind: 'review',
          inputSource: { nodeId: 'designer', portName: 'design' },
          rerunnableOnIterate: ['designer'],
          rerunnableOnReject: ['designer'],
        } as unknown as WorkflowNode,
        { id: 'gw', kind: 'wrapper-git', nodeIds: ['designer', 'rev'] } as WorkflowNode,
      ],
      edges: [
        {
          id: 'e_in',
          source: { nodeId: 'in1', portName: 'topic' },
          target: { nodeId: 'designer', portName: 'topic' },
        },
        {
          id: 'e_rev',
          source: { nodeId: 'designer', portName: 'design' },
          target: { nodeId: 'rev', portName: '__review_input__' },
        },
      ],
    }
    const taskId = await seedWorkflowAndTask(h, def, { topic: 'x' })

    await runTask({ taskId, db: h.db, appHome: h.appHome, opencodeCmd: ['bun', 'run', h.mockPath] })
    expect(await taskStatus(h.db, taskId)).toBe('awaiting_review')
    const gwBefore = await nodeRows(h.db, taskId, 'gw')
    expect(gwBefore).toHaveLength(1)
    expect(gwBefore[0]!.status).toBe('awaiting_review')
    const gwRunId = gwBefore[0]!.id
    const rev = (await nodeRows(h.db, taskId, 'rev')).find((r) => r.status === 'awaiting_review')
    expect(rev).toBeDefined()

    await submitReviewDecision({
      db: h.db,
      appHome: h.appHome,
      nodeRunId: rev!.id,
      decision: 'approved',
      expectedReviewIteration: rev!.reviewIteration,
    })

    await reenterScheduler(h.db, taskId)
    await runTask({ taskId, db: h.db, appHome: h.appHome, opencodeCmd: ['bun', 'run', h.mockPath] })
    expect(await taskStatus(h.db, taskId)).toBe('done')

    // 同行复用 + git_diff 恰写一次（resume 不重抓 baseline 的既有闸由
    // scheduler-rfc040-wrapper-await 锁定；这里锁 approve 复活路径同款收敛）。
    const gwAfter = await nodeRows(h.db, taskId, 'gw')
    expect(gwAfter).toHaveLength(1)
    expect(gwAfter[0]!.id).toBe(gwRunId)
    expect(gwAfter[0]!.status).toBe('done')
    const outs = await h.db
      .select()
      .from(nodeRunOutputs)
      .where(eq(nodeRunOutputs.nodeRunId, gwRunId))
    expect(outs.filter((o) => o.portName === 'git_diff')).toHaveLength(1)
  }, 20_000)
})

const CLARIFY_BODY = {
  questions: [
    {
      id: 'q1',
      title: 'Which database?',
      kind: 'single',
      recommended: false,
      options: [
        { label: 'Postgres', description: '', recommended: true, recommendationReason: '' },
        { label: 'MySQL', description: '', recommended: false, recommendationReason: '' },
      ],
    },
  ],
}
const CLARIFY_ANSWER: ClarifyAnswer = {
  questionId: 'q1',
  selectedOptionIndices: [0],
  selectedOptionLabels: ['Postgres'],
  customText: '',
}

describe('RFC-098 B3 — RFC-092 已知限制解除：wrapper 内 clarify mid-run 答复自动续跑', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h.cleanup())

  test('slow sibling 仍在跑时答 wrapper 内 clarify → 任务自动 done，不需要手动 resume', async () => {
    await seedAgent(h.db, 'asker', ['design'])
    await seedAgent(h.db, 'slow', ['out'])
    writeFileSync(
      h.planFile,
      JSON.stringify({
        asker: [{ clarify: CLARIFY_BODY }, { output: { design: 'design-after-answer' } }],
        slow: [{ output: { out: 'slow-done' } }],
      }),
    )
    // 菱形：in → {loop ∋ {asker, clarify}, slow}。wrapper park 时 loop 节点已
    // 进 dispatchedThisInvocation——这正是 RFC-092 限制的触发面。
    const def: WorkflowDefinition = {
      $schema_version: 3,
      inputs: [{ kind: 'text', key: 'req', label: 'r' }],
      nodes: [
        { id: 'in1', kind: 'input', inputKey: 'req' } as WorkflowNode,
        { id: 'asker', kind: 'agent-single', agentName: 'asker' } as WorkflowNode,
        { id: 'c', kind: 'clarify', title: 'Clarify me' } as WorkflowNode,
        {
          id: 'loop',
          kind: 'wrapper-loop',
          nodeIds: ['asker', 'c'],
          maxIterations: 3,
          exitCondition: { kind: 'port-not-empty', nodeId: 'asker', portName: 'design' },
          outputBindings: [{ name: 'final', bind: { nodeId: 'asker', portName: 'design' } }],
        } as unknown as WorkflowNode,
        { id: 'slow', kind: 'agent-single', agentName: 'slow' } as WorkflowNode,
      ],
      edges: [
        {
          id: 'e_in_a',
          source: { nodeId: 'in1', portName: 'req' },
          target: { nodeId: 'asker', portName: 'req' },
        },
        {
          id: 'e_in_s',
          source: { nodeId: 'in1', portName: 'req' },
          target: { nodeId: 'slow', portName: 'req' },
        },
        {
          id: 'e_ask',
          source: { nodeId: 'asker', portName: '__clarify__' },
          target: { nodeId: 'c', portName: 'questions' },
        },
        {
          id: 'e_ans',
          source: { nodeId: 'c', portName: 'answers' },
          target: { nodeId: 'asker', portName: '__clarify_response__' },
        },
      ],
    }
    const taskId = await seedWorkflowAndTask(h, def, { req: 'go' })

    const runPromise = runTask({
      taskId,
      db: h.db,
      appHome: h.appHome,
      opencodeCmd: ['bun', 'run', h.mockPath],
    })

    try {
      // 提交窗口：clarify 已停泊（wrapper 行 awaiting_human）∧ slow 仍 running。
      const session = await waitFor(async () => {
        const s = (
          await h.db
            .select()
            .from(clarifySessions)
            .where(
              and(eq(clarifySessions.taskId, taskId), eq(clarifySessions.status, 'awaiting_human')),
            )
        )[0]
        if (s === undefined) return undefined
        const slowRuns = await nodeRows(h.db, taskId, 'slow')
        if (slowRuns.length !== 1 || slowRuns[0]!.status !== 'running') return undefined
        const loopRuns = await nodeRows(h.db, taskId, 'loop')
        if (loopRuns.length !== 1 || loopRuns[0]!.status !== 'awaiting_human') return undefined
        return s
      }, 'parked wrapper clarify while slow sibling is still running')

      expect(await taskStatus(h.db, taskId)).toBe('running')

      await submitClarifyAnswers({
        db: h.db,
        clarifyNodeRunId: session.clarifyNodeRunId,
        answers: [CLARIFY_ANSWER],
        directive: 'stop', // RFC-100: finalize round → wrapper-inner agent's <workflow-output> accepted
      })
    } finally {
      writeFileSync(h.gateFile, 'go\n')
      await runPromise.catch(() => {})
    }
    await runPromise

    // RFC-092 限制解除主证：同一次 runTask 内任务直接收敛 done——修复前这里
    // 是 awaiting_human（wrapper 在 dispatchedThisInvocation 里被挡，inbox 已
    // 空、等人工 resume）。
    const taskRow = (await h.db.select().from(tasks).where(eq(tasks.id, taskId)))[0]!
    expect(`${taskRow.status}:${taskRow.errorSummary ?? ''}`).toBe('done:')

    // wrapper 行同行复用、done，导出答后产物。
    const loopRuns = await nodeRows(h.db, taskId, 'loop')
    expect(loopRuns).toHaveLength(1)
    expect(loopRuns[0]!.status).toBe('done')
    const outs = await h.db
      .select()
      .from(nodeRunOutputs)
      .where(eq(nodeRunOutputs.nodeRunId, loopRuns[0]!.id))
    expect(outs.find((o) => o.portName === 'final')?.content).toBe('design-after-answer')

    // asker 两次（问 + 答后 rerun）；slow 恰一次不受扰；会话闭环 answered。
    const askerRuns = await nodeRows(h.db, taskId, 'asker')
    expect(askerRuns.length).toBe(2)
    expect(askerRuns.every((r) => r.status === 'done')).toBe(true)
    const slowRuns = await nodeRows(h.db, taskId, 'slow')
    expect(slowRuns).toHaveLength(1)
    expect(slowRuns[0]!.status).toBe('done')
    const sessions = await h.db
      .select()
      .from(clarifySessions)
      .where(eq(clarifySessions.taskId, taskId))
    expect(sessions).toHaveLength(1)
    expect(sessions[0]!.status).toBe('answered')
  }, 20_000)
})
