// RFC-097 — cancel 赢家语义 + limits 不污染终态（design/RFC-097-task-status-cas/
// design.md §2 写点 4/6/10、§6 失败模式「done-vs-cancel」「limits 文案污染」）。
//
// 锁定的合同（任一回归即红）：
//   1. cancel-vs-done：任务运行中 cancelTask → 即使 agent 的 <workflow-output>
//      封皮已完整写到 stdout，abort 仍赢——调度器在每个终态/停泊写之前必经
//      `opts.signal?.aborted` 终检（scheduler.ts runTask 步骤 9 与 awaiting_* 分支），
//      done CAS(from=running) 与 cancel CAS 的 from-集互斥，恰一胜。最终 canceled
//      非 done。
//   2. limits 不污染：enforceLimits 的扫描只取 status='running'（已 done 任务根本
//      不进扫描）；扫描后才落终态的竞态窗口由两层防护兜住——cancelTask 对终态任务
//      抛 task-not-cancelable 被分类吞 + 文案覆写改为条件写 `WHERE status='canceled'`
//      不命中。已 done 任务的 errorSummary/errorMessage/finishedAt 保持原值，
//      不被 limit 文案涂掉。

import type { WorkflowDefinition } from '@agent-workflow/shared'
import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { eq } from 'drizzle-orm'
import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { ulid } from 'ulid'
import { createInMemoryDb, type DbClient } from '../src/db/client'
import { agents, nodeRuns, tasks, workflows } from '../src/db/schema'
import { trySetTaskStatus } from '../src/services/lifecycle'
import { enforceLimits } from '../src/services/limits'
import { cancelTask, resumeTask } from '../src/services/task'
import { runGit } from '../src/util/git'

const MIGRATIONS = resolve(import.meta.dir, '..', 'db', 'migrations')

// 慢 mock：先把完整 envelope 写上 stdout，再写起跑 marker，然后挂起等 SIGTERM。
// 「envelope 已在手但 abort 仍赢」是比单纯挂起更尖的 oracle——runner 对 abort 的
// 处置不依赖子进程输出内容。
function buildSlowEnvelopeMock(ctrlDir: string): string {
  return `// generated by rfc097-cancel-wins.test.ts — envelope-then-hang mock.
import { writeFileSync } from 'node:fs'
const text =
  '<workflow-output>\\n  <port name="out">WOULD-BE-DONE</port>\\n</workflow-output>'
process.stdout.write(
  JSON.stringify({ type: 'text', timestamp: Date.now(), part: { type: 'text', text } }) + '\\n',
)
writeFileSync(${JSON.stringify(ctrlDir)} + '/work-started', '1')
await Bun.sleep(120000)
process.exit(1)
`
}

interface Harness {
  db: DbClient
  appHome: string
  worktreePath: string
  ctrlDir: string
  taskId: string
  slowMock: string
  cleanup: () => void
}

async function buildHarness(): Promise<Harness> {
  const appHome = mkdtempSync(join(tmpdir(), 'aw-rfc097-cancel-'))
  const worktreePath = join(appHome, 'wt')
  const ctrlDir = join(appHome, 'ctrl')
  mkdirSync(worktreePath, { recursive: true })
  mkdirSync(ctrlDir, { recursive: true })
  await runGit(worktreePath, ['init', '-q', '-b', 'main'])
  await runGit(worktreePath, ['config', 'user.email', 't@t.test'])
  await runGit(worktreePath, ['config', 'user.name', 't'])
  writeFileSync(join(worktreePath, 'README.md'), '# r\n')
  await runGit(worktreePath, ['add', '.'])
  await runGit(worktreePath, ['commit', '-q', '-m', 'init'])

  const slowMock = join(ctrlDir, 'mock-slow-envelope.ts')
  writeFileSync(slowMock, buildSlowEnvelopeMock(ctrlDir))

  const db = createInMemoryDb(MIGRATIONS)
  await db.insert(agents).values({
    id: ulid(),
    name: 'worker',
    description: 'test',
    outputs: JSON.stringify(['out']),
    permission: '{}',
    skills: '[]',
    frontmatterExtra: '{}',
    bodyMd: '',
  })
  const definition: WorkflowDefinition = {
    $schema_version: 3,
    inputs: [],
    nodes: [
      { id: 'work', kind: 'agent-single', agentName: 'worker' },
    ] as unknown as WorkflowDefinition['nodes'],
    edges: [],
  }
  const workflowId = ulid()
  const taskId = ulid()
  await db.insert(workflows).values({
    id: workflowId,
    name: 'wf-rfc097-cancel',
    definition: JSON.stringify(definition),
  })
  await db.insert(tasks).values({
    id: taskId,
    name: 'rfc097-cancel-task',
    workflowId,
    workflowSnapshot: JSON.stringify(definition),
    repoPath: worktreePath,
    worktreePath,
    baseBranch: 'main',
    branch: `agent-workflow/${taskId}`,
    status: 'failed',
    inputs: '{}',
    startedAt: Date.now() - 60_000,
    finishedAt: Date.now() - 30_000,
    errorSummary: 'boom',
  })
  await db.insert(nodeRuns).values({
    id: ulid(),
    taskId,
    nodeId: 'work',
    status: 'failed',
    retryIndex: 0,
    iteration: 0,
    startedAt: Date.now() - 60_000,
    finishedAt: Date.now() - 30_000,
    errorMessage: 'boom',
  })
  return {
    db,
    appHome,
    worktreePath,
    ctrlDir,
    taskId,
    slowMock,
    cleanup: () => rmSync(appHome, { recursive: true, force: true }),
  }
}

async function waitFor(cond: () => boolean, what: string): Promise<void> {
  for (let i = 0; i < 400; i++) {
    if (cond()) return
    await Bun.sleep(25)
  }
  throw new Error(`timeout waiting for ${what}`)
}

async function seedLimitsTask(
  db: DbClient,
  overrides: Partial<typeof tasks.$inferInsert>,
): Promise<string> {
  const workflowId = ulid()
  const taskId = ulid()
  await db.insert(workflows).values({ id: workflowId, name: 'wf', definition: '{}' })
  await db.insert(tasks).values({
    id: taskId,
    name: 'limits-fixture',
    workflowId,
    workflowSnapshot: '{}',
    repoPath: '/tmp/repo',
    worktreePath: '/tmp/wt',
    baseBranch: 'main',
    branch: `agent-workflow/${taskId}`,
    status: 'running',
    inputs: '{}',
    startedAt: Date.now() - 1000,
    ...overrides,
  })
  return taskId
}

describe('RFC-097 — cancel 赢家语义 + limits 不污染', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h.cleanup())

  test('cancel-vs-done：运行中 cancelTask → 最终 canceled 非 done（envelope 已写出也不翻盘）', async () => {
    await resumeTask(h.db, h.taskId, {
      db: h.db,
      appHome: h.appHome,
      opencodeCmd: ['bun', 'run', h.slowMock],
      // RFC-115: retry budget via StartTaskDeps (was node.retries: 0).
      defaultNodeRetries: 0,
    })
    await waitFor(() => existsSync(join(h.ctrlDir, 'work-started')), 'work node spawn')

    // cancelTask abort controller → runner SIGTERM 子进程 → runScope canceled →
    // cancelTaskRow CAS(from=running)。cancelTask 自身轮询到终态后返回赢家。
    const returned = await cancelTask(h.db, h.taskId)
    expect(returned.status).toBe('canceled')

    const final = (await h.db.select().from(tasks).where(eq(tasks.id, h.taskId)))[0]!
    expect(final.status).toBe('canceled') // 非 done——cancel 赢
    expect(final.errorSummary).toBe('canceled by user')
    expect(final.finishedAt).not.toBeNull()

    // 节点行同样收敛 canceled：envelope 虽已完整写出 stdout，abort 后 runner
    // 不得把该行结算为 done。
    const rows = await h.db.select().from(nodeRuns).where(eq(nodeRuns.taskId, h.taskId))
    const latest = rows
      .filter((r) => r.nodeId === 'work')
      .sort((a, b) => (a.id > b.id ? -1 : 1))[0]!
    expect(latest.status).toBe('canceled')
    expect(rows.some((r) => r.status === 'done')).toBe(false)
  }, 30000)

  test('limits：已 done 的任务不进扫描——errorSummary/errorMessage 保持原值', async () => {
    const taskId = await seedLimitsTask(h.db, {
      status: 'done',
      maxDurationMs: 5_000,
      startedAt: Date.now() - 60_000,
      finishedAt: Date.now() - 1_000,
      errorSummary: null,
      errorMessage: null,
    })

    const r = await enforceLimits(h.db, Date.now())
    expect(r).toEqual({ scanned: 0, canceled: [] })

    const t = (await h.db.select().from(tasks).where(eq(tasks.id, taskId)))[0]!
    expect(t.status).toBe('done')
    expect(t.errorSummary).toBeNull()
    expect(t.errorMessage).toBeNull()
  })

  test('limits 竞态窗口：扫描后任务落 done → cancelTask 抛 task-not-cancelable 被吞 + 条件覆写不命中，文案零污染', async () => {
    const finishedAt = Date.now() - 10
    const taskId = await seedLimitsTask(h.db, {
      status: 'running',
      maxDurationMs: 5_000,
      startedAt: Date.now() - 60_000, // 超时——必进扫描、必触发 cancel 流程
    })

    // 不 await：让 enforceLimits 的扫描 SELECT 先排队（读到 running），
    // 然后在它走到 cancelTask 之前用合法写者把任务翻 done——精确复现
    // 「scan 与 cancel 之间任务自然完成」的竞态窗口。
    const race = enforceLimits(h.db, Date.now())
    const flipped = await trySetTaskStatus({
      db: h.db,
      taskId,
      to: 'done',
      allowedFrom: ['running'],
      extra: { finishedAt, errorSummary: null, errorMessage: null },
      reason: 'test: scheduler done landing between limits scan and cancel',
    })
    expect(flipped).toBe(true) // 窗口构造成立：done 在 cancel 落账前先赢
    const r = await race
    expect(r.scanned).toBe(1) // 任务确实在扫描集里（竞态真实发生过）

    // 两层防护殊途同归：cancelTask 对终态抛 task-not-cancelable（被 enforceLimits
    // 分类吞）；即使走到 fallback 也是 trySet 输掉；最后的文案覆写是条件写
    // `WHERE status='canceled'`——对 done 行不命中。原终态字段全部保持。
    const t = (await h.db.select().from(tasks).where(eq(tasks.id, taskId)))[0]!
    expect(t.status).toBe('done')
    expect(t.errorSummary).toBeNull() // 不是 'task-time-limit-exceeded'
    expect(t.errorMessage).toBeNull()
    expect(t.finishedAt).toBe(finishedAt)
  })
})
