// RFC-193 T6 — wrapper 内 review 主回归（design.md §6 case 5，AC-1）。
//
// 这是本 RFC 的原始事故现场（用户 2026-07-15 线上撞到）：git/loop wrapper
// 内的 agent 把文件写进 wrapper-canonical（`~/.agent-workflow/iso/...`），而
// dispatchReviewNode 恒用 `task.worktreePath` 解析——review 又是 wrapper 的
// 暂停点，wrapper 永远等不到「整体完成」把文件带回主 worktree ⇒ 死锁级
// 「file not found in worktree」占位。修复后 review 读 emit-time 归档
// （readPortArtifact），scope 嵌套彻底无关。
//
// 锁定：loop wrapper 内 writer(path<md>) → review 的 doc_version body 必须
// 是文件内容（单文档 + list<path<md>> 多文档两形态），并且绝不含 RFC-079
// 占位文案。若未来有人把 review 的读取改回「对某个 worktree join 路径」，
// 这两条会立刻红。

import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { eq } from 'drizzle-orm'
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { monotonicFactory } from 'ulid'
import type { WorkflowDefinition, WorkflowNode } from '@agent-workflow/shared'
import { createInMemoryDb, type DbClient } from '../src/db/client'
import { agents, docVersions, tasks, workflows } from '../src/db/schema'
import { runTask } from '../src/services/scheduler'
import { runGit } from '../src/util/git'

const ulid = monotonicFactory()
const MIGRATIONS = resolve(import.meta.dir, '..', 'db', 'migrations')

function mockSource(planFile: string): string {
  return `// generated by rfc193-wrapper-review.test.ts
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
const argv = process.argv.slice(2)
if (argv.includes('--version')) { process.stdout.write('rfc193-wr-mock 1.14.99\\n'); process.exit(0) }
if (argv[0] !== 'run') { process.stderr.write('rfc193-wr-mock: expected run\\n'); process.exit(2) }
const nonce = /\\bnonce="([^"]+)"/.exec(argv[1] ?? '')?.[1]
const outputOpen =
  nonce === undefined ? '<workflow-output>' : '<workflow-output nonce="' + nonce + '">'
const ai = argv.indexOf('--agent')
const agent = ai >= 0 ? (argv[ai + 1] ?? '') : ''
const plan = JSON.parse(readFileSync(${JSON.stringify(planFile)}, 'utf-8'))
const step = plan[agent] ?? {}
for (const [rel, content] of Object.entries(step.files ?? {})) {
  const abs = join(process.cwd(), rel)
  mkdirSync(dirname(abs), { recursive: true })
  writeFileSync(abs, String(content))
}
function emit(text) {
  process.stdout.write(JSON.stringify({ type: 'text', timestamp: Date.now(), part: { type: 'text', text } }) + '\\n')
}
let envelope = outputOpen + '\\n'
for (const [p, c] of Object.entries(step.output ?? {})) envelope += '  <port name="' + p + '">' + c + '</port>\\n'
envelope += '</workflow-output>'
emit(envelope)
process.exit(0)
`
}

interface Harness {
  db: DbClient
  appHome: string
  repoPath: string
  worktreePath: string
  mockPath: string
  planFile: string
  cleanup: () => void
}

async function buildHarness(): Promise<Harness> {
  const appHome = mkdtempSync(join(tmpdir(), 'aw-rfc193-wr-'))
  const repoPath = join(appHome, 'repo')
  const worktreePath = join(appHome, 'wt')
  const planFile = join(appHome, 'plan.json')
  const mockPath = join(appHome, 'mock.ts')
  for (const p of [repoPath, worktreePath]) {
    mkdirSync(p, { recursive: true })
    await runGit(p, ['init', '-b', 'main'])
    await runGit(p, ['config', 'user.email', 't@t.test'])
    await runGit(p, ['config', 'user.name', 't'])
    writeFileSync(join(p, 'README.md'), '# r\n')
    await runGit(p, ['add', '.'])
    await runGit(p, ['commit', '-m', 'init'])
  }
  writeFileSync(mockPath, mockSource(planFile))
  const db = createInMemoryDb(MIGRATIONS)
  return {
    db,
    appHome,
    repoPath,
    worktreePath,
    mockPath,
    planFile,
    cleanup: () => rmSync(appHome, { recursive: true, force: true }),
  }
}

async function seedAgent(
  db: DbClient,
  name: string,
  outputs: string[],
  outputKinds: Record<string, string>,
): Promise<void> {
  await db.insert(agents).values({
    id: ulid(),
    name,
    description: 'test',
    outputs: JSON.stringify(outputs),
    permission: '{}',
    skills: '[]',
    frontmatterExtra: JSON.stringify({ outputKinds }),
    bodyMd: '',
  })
}

function loopReviewDef(docKind: 'path<md>' | 'list<path<md>>'): WorkflowDefinition {
  void docKind
  return {
    $schema_version: 3,
    inputs: [{ kind: 'text', key: 'req', label: 'r' }],
    nodes: [
      { id: 'in1', kind: 'input', inputKey: 'req' } as WorkflowNode,
      {
        id: 'loop',
        kind: 'wrapper-loop',
        nodeIds: ['writer', 'rev'],
        maxIterations: 1,
        exitCondition: { kind: 'port-not-empty', nodeId: 'writer', portName: 'doc' },
      } as unknown as WorkflowNode,
      { id: 'writer', kind: 'agent-single', agentName: 'writer' } as WorkflowNode,
      {
        id: 'rev',
        kind: 'review',
        inputSource: { nodeId: 'writer', portName: 'doc' },
      } as unknown as WorkflowNode,
    ],
    edges: [
      {
        id: 'e1',
        source: { nodeId: 'in1', portName: 'req' },
        target: { nodeId: 'writer', portName: 'req' },
      },
    ],
  }
}

async function seedTask(h: Harness, definition: WorkflowDefinition): Promise<string> {
  const workflowId = ulid()
  const taskId = ulid()
  await h.db.insert(workflows).values({
    id: workflowId,
    name: 'wf-rfc193-wr',
    definition: JSON.stringify(definition),
  })
  await h.db.insert(tasks).values({
    name: 'rfc193-wrapper-review',
    id: taskId,
    workflowId,
    workflowSnapshot: JSON.stringify(definition),
    repoPath: h.repoPath,
    worktreePath: h.worktreePath,
    baseBranch: 'main',
    branch: `agent-workflow/${taskId}`,
    status: 'pending',
    inputs: JSON.stringify({ req: 'go' }),
    startedAt: Date.now(),
  })
  return taskId
}

describe('RFC-193 e2e — wrapper 内 review 主回归（AC-1）', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h?.cleanup())

  test('case 5 单文档：loop 内 writer(path<md>) → review body = 文件内容，非占位', async () => {
    await seedAgent(h.db, 'writer', ['doc'], { doc: 'path<md>' })
    writeFileSync(
      h.planFile,
      JSON.stringify({
        writer: {
          files: { 'design.md': '# wrapper-internal design\n\nreal body' },
          output: { doc: 'design.md' },
        },
      }),
    )
    const taskId = await seedTask(h, loopReviewDef('path<md>'))
    await runTask({ db: h.db, taskId, appHome: h.appHome, opencodeCmd: ['bun', 'run', h.mockPath] })

    const taskRow = (await h.db.select().from(tasks).where(eq(tasks.id, taskId)))[0]!
    expect(taskRow.status).toBe('awaiting_review')

    const dvs = await h.db.select().from(docVersions).where(eq(docVersions.taskId, taskId))
    expect(dvs.length).toBe(1)
    const body = readFileSync(join(h.appHome, dvs[0]!.bodyPath), 'utf8')
    expect(body).toBe('# wrapper-internal design\n\nreal body')
    expect(body).not.toContain('file not found in worktree')
  })

  test('case 5 多文档：loop 内 writer(list<path<md>>) → 每个 doc_version body 对齐 item', async () => {
    await seedAgent(h.db, 'writer', ['doc'], { doc: 'list<path<md>>' })
    writeFileSync(
      h.planFile,
      JSON.stringify({
        writer: {
          files: { 'a.md': 'DOC A', 'sub/b.md': 'DOC B' },
          output: { doc: 'a.md\nsub/b.md' },
        },
      }),
    )
    const taskId = await seedTask(h, loopReviewDef('list<path<md>>'))
    await runTask({ db: h.db, taskId, appHome: h.appHome, opencodeCmd: ['bun', 'run', h.mockPath] })

    const taskRow = (await h.db.select().from(tasks).where(eq(tasks.id, taskId)))[0]!
    expect(taskRow.status).toBe('awaiting_review')

    const dvs = (await h.db.select().from(docVersions).where(eq(docVersions.taskId, taskId))).sort(
      (a, b) => (a.itemIndex ?? 0) - (b.itemIndex ?? 0),
    )
    expect(dvs.length).toBe(2)
    expect(dvs.map((d) => d.itemPath)).toEqual(['a.md', 'sub/b.md'])
    const bodies = dvs.map((d) => readFileSync(join(h.appHome, d.bodyPath), 'utf8'))
    expect(bodies).toEqual(['DOC A', 'DOC B'])
    for (const b of bodies) expect(b).not.toContain('file not found in worktree')
  })
})

describe('RFC-193 e2e — 派生投影透传（D16 / case 8b）', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h?.cleanup())

  test('loop 提升行与 output 虚拟节点行携带上游 kind + archive_json', async () => {
    await seedAgent(h.db, 'writer', ['doc'], { doc: 'path<md>' })
    writeFileSync(
      h.planFile,
      JSON.stringify({
        writer: { files: { 'design.md': 'PROJECTED BODY' }, output: { doc: 'design.md' } },
      }),
    )
    const def: WorkflowDefinition = {
      $schema_version: 3,
      inputs: [{ kind: 'text', key: 'req', label: 'r' }],
      nodes: [
        { id: 'in1', kind: 'input', inputKey: 'req' } as WorkflowNode,
        {
          id: 'loop',
          kind: 'wrapper-loop',
          nodeIds: ['writer'],
          maxIterations: 1,
          exitCondition: { kind: 'port-not-empty', nodeId: 'writer', portName: 'doc' },
          outputBindings: [{ name: 'final', bind: { nodeId: 'writer', portName: 'doc' } }],
        } as unknown as WorkflowNode,
        { id: 'writer', kind: 'agent-single', agentName: 'writer' } as WorkflowNode,
        {
          id: 'out1',
          kind: 'output',
          ports: [{ name: 'z', bind: { nodeId: 'loop', portName: 'final' } }],
        } as unknown as WorkflowNode,
      ],
      edges: [
        {
          id: 'e1',
          source: { nodeId: 'in1', portName: 'req' },
          target: { nodeId: 'writer', portName: 'req' },
        },
        {
          id: 'e2',
          source: { nodeId: 'loop', portName: 'final' },
          target: { nodeId: 'out1', portName: 'z' },
        },
      ],
    }
    const taskId = await seedTask(h, def)
    await runTask({ db: h.db, taskId, appHome: h.appHome, opencodeCmd: ['bun', 'run', h.mockPath] })

    const { nodeRunOutputs, nodeRuns } = await import('../src/db/schema')
    const { and } = await import('drizzle-orm')
    const { parseArchiveJson } = await import('../src/services/portArtifacts')
    async function projectedRow(nodeId: string, port: string) {
      const runs = await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, taskId), eq(nodeRuns.nodeId, nodeId)))
      const done = runs.filter((r) => r.status === 'done').at(-1)
      expect(done).toBeDefined()
      const rows = await h.db
        .select()
        .from(nodeRunOutputs)
        .where(and(eq(nodeRunOutputs.nodeRunId, done!.id), eq(nodeRunOutputs.portName, port)))
      return rows[0]
    }
    for (const [nodeId, port] of [
      ['loop', 'final'],
      ['out1', 'z'],
    ] as const) {
      const row = await projectedRow(nodeId, port)
      expect(row).toBeDefined()
      expect(row!.content).toBe('design.md')
      expect(row!.kind).toBe('path<md>')
      const arch = parseArchiveJson(row!.archiveJson)
      expect(arch).not.toBeNull()
      expect(readFileSync(join(h.appHome, arch!.items[0]!.file!), 'utf8')).toBe('PROJECTED BODY')
    }
  })
})

// RFC-193 D9/AC-7 源码锁 — scopeRoot 接线 + review.ts 禁 task.worktreePath。
// 若有人把 review 的读取改回「join(task.worktreePath, …)」或把 wrapper
// innerState 的 scopeRoot 拆掉，这里比 e2e 更快地红出来。
describe('RFC-193 source locks (scopeRoot / review.ts)', () => {
  const SCHEDULER = resolve(import.meta.dir, '..', 'src', 'services', 'scheduler.ts')
  const REVIEW = resolve(import.meta.dir, '..', 'src', 'services', 'review.ts')
  const S1 = resolve(import.meta.dir, '..', 'src', 'services', 'lifecycleRepair', 'options-S1.ts')

  test('review.ts never touches task.worktreePath (AC-7)', () => {
    const src = readFileSync(REVIEW, 'utf8')
    expect(src).not.toContain('task.worktreePath')
  })

  test('scheduler wires scopeRoot: top level + both wrapper innerStates', () => {
    const src = readFileSync(SCHEDULER, 'utf8')
    expect(src).toContain('scopeRoot: task.worktreePath')
    expect(src.split('scopeRoot: wrapperIso.containerPath').length - 1).toBe(2)
    expect(src).toContain('scopeRoot: state.scopeRoot')
  })

  test('S1 repair derives scopeRoot from wrapper lineage, not task.worktreePath directly (case 8d)', () => {
    const src = readFileSync(S1, 'utf8')
    expect(src).toContain('deriveScopeRoot')
    expect(src).toContain('scopeRoot: prep.scopeRoot')
    expect(src).toContain('isoWorktreePathFor')
  })
})
