// RFC-242 PR-3 — call-workflow 节点端到端（design §6.2 D→L→W→F→M 全链）。
//
// Locks in:
//   1. 父任务的 call 节点从冻结闭包起独立子任务：子任务行 parentTaskId /
//      parentNodeRunId / invocationDepth=1 / spaceKind='inherited'，其 canonical
//      即调用行的 iso worktree。
//   2. 工作区继承（D5）：父 canonical 的【未提交】文件对子任务的 agent 可见
//      （通过 iso 派生 —— snapshotFullState 含未提交/untracked）。
//   3. 子任务 done → F 输出回填（call 行 node_run_outputs = 子任务 output 投影）
//      → M 合并回（子任务写盘文件落回父 canonical）→ 调用行 done+merged →
//      父 output 节点消费 call 端口 → 父任务 done。
//   4. 子任务失败 → 调用行 failed(child-task-failed) → 父任务 failed（错误
//      摘要携带子任务信息）。
//   5. freezeCallClosure 纯服务：无 call 节点 → null；引用缺失 →
//      workflow-call-ref-missing；A→B→A → workflow-call-cycle（id-only 载荷）。
import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { existsSync, mkdirSync, readFileSync, rmSync, mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { monotonicFactory } from 'ulid'
import { and, eq } from 'drizzle-orm'
import type { WorkflowDefinition, WorkflowNode } from '@agent-workflow/shared'
import { createInMemoryDb, type DbClient } from '../src/db/client'
import { agents, nodeRunOutputs, nodeRuns, tasks, workflows } from '../src/db/schema'
import { runTask } from '../src/services/scheduler'
import type { StartTaskDeps } from '../src/services/task'
import { freezeCallClosure } from '../src/services/execution/closure'
import { runGit } from '../src/util/git'
import { seedTestDefaultOpencodeRuntime } from './helpers/executionRuntimeFixture'

const ulid = monotonicFactory()
const MIGRATIONS = resolve(import.meta.dir, '..', 'db', 'migrations')

interface Harness {
  db: DbClient
  appHome: string
  repoPath: string
  worktreePath: string
  mockPath: string
  planFile: string
  cleanup: () => void
}

// mock runtime：按 --agent 查 plan，写文件 + 发 <workflow-output> 信封。
// `__FILE__:rel` 端口值 = 读该 agent 自己 CWD（= 子任务 iso）下 rel 的内容 ——
// 用它证明「父 canonical 未提交文件出现在子任务的工作区里」。exitCode 非 0
// 的 plan 项用来构造子任务失败。
function mockSource(planFile: string): string {
  return `// generated by rfc242-call-workflow.test.ts
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
const argv = process.argv.slice(2)
if (argv.includes('--version')) { process.stdout.write('rfc242-call-mock 1.14.99\\n'); process.exit(0) }
if (argv[0] !== 'run') { process.stderr.write('rfc242-call-mock: expected run\\n'); process.exit(2) }
const nonce = /\\bnonce="([^"]+)"/.exec(argv.includes('--') ? argv.slice(argv.indexOf('--') + 1).join(' ') : (argv[1] ?? ''))?.[1]
const outputOpen =
  nonce === undefined ? '<workflow-output>' : '<workflow-output nonce="' + nonce + '">'
const ai = argv.indexOf('--agent')
const agent = ai >= 0 ? (argv[ai + 1] ?? '') : ''
const plan = JSON.parse(readFileSync(${JSON.stringify(planFile)}, 'utf-8'))
const step = plan[agent] ?? {}
if (step.hangMs !== undefined) { await Bun.sleep(step.hangMs); process.exit(1) }
if (step.exitCode !== undefined) { process.stderr.write('planned failure\\n'); process.exit(step.exitCode) }
for (const [rel, content] of Object.entries(step.files ?? {})) {
  const abs = join(process.cwd(), rel)
  mkdirSync(dirname(abs), { recursive: true })
  writeFileSync(abs, String(content))
}
function emit(text) {
  process.stdout.write(JSON.stringify({ type: 'text', timestamp: Date.now(), part: { type: 'text', text } }) + '\\n')
}
let envelope = outputOpen + '\\n'
for (const [p, c] of Object.entries(step.output ?? {})) {
  let v = String(c)
  if (v.startsWith('__FILE__:')) {
    const rel = v.slice('__FILE__:'.length)
    try { v = readFileSync(join(process.cwd(), rel), 'utf8') } catch { v = 'FILE-MISSING:' + rel }
  }
  envelope += '  <port name="' + p + '">' + v + '</port>\\n'
}
envelope += '</workflow-output>'
emit(envelope)
process.exit(0)
`
}

async function buildHarness(): Promise<Harness> {
  const appHome = mkdtempSync(join(tmpdir(), 'aw-rfc242-call-'))
  const repoPath = join(appHome, 'repo')
  const worktreePath = join(appHome, 'wt')
  const planFile = join(appHome, 'plan.json')
  const mockPath = join(appHome, 'mock.ts')
  for (const p of [repoPath, worktreePath]) {
    mkdirSync(p, { recursive: true })
    await runGit(p, ['init', '-b', 'main'])
    await runGit(p, ['config', 'user.email', 't@t.test'])
    await runGit(p, ['config', 'user.name', 't'])
    writeFileSync(join(p, 'README.md'), '# r\n')
    await runGit(p, ['add', '.'])
    await runGit(p, ['commit', '-m', 'init'])
  }
  writeFileSync(mockPath, mockSource(planFile))
  const db = createInMemoryDb(MIGRATIONS)
  await seedTestDefaultOpencodeRuntime(db)
  return {
    db,
    appHome,
    repoPath,
    worktreePath,
    mockPath,
    planFile,
    cleanup: () => rmSync(appHome, { recursive: true, force: true }),
  }
}

async function seedAgent(db: DbClient, name: string, outputs: string[]): Promise<string> {
  const id = ulid()
  await db.insert(agents).values({
    id,
    name,
    description: 'test',
    outputs: JSON.stringify(outputs),
    permission: '{}',
    skills: '[]',
    frontmatterExtra: '{}',
    bodyMd: '',
  })
  return id
}

function childDefinition(workerId: string): WorkflowDefinition {
  return {
    $schema_version: 4,
    inputs: [{ kind: 'text', key: 'req', label: 'r' }],
    nodes: [
      { id: 'cin', kind: 'input', inputKey: 'req' } as WorkflowNode,
      {
        id: 'work',
        kind: 'agent-single',
        agentId: workerId,
        agentName: 'worker',
        promptTemplate: 'do {{req}}',
      } as WorkflowNode,
      {
        id: 'cout',
        kind: 'output',
        ports: [
          { name: 'report', bind: { nodeId: 'work', portName: 'out' } },
          { name: 'echo', bind: { nodeId: 'work', portName: 'echo' } },
        ],
      } as WorkflowNode,
    ],
    edges: [
      {
        id: 'e1',
        source: { nodeId: 'cin', portName: 'req' },
        target: { nodeId: 'work', portName: 'req' },
      },
    ],
  } as WorkflowDefinition
}

function parentDefinition(): WorkflowDefinition {
  return {
    $schema_version: 4,
    inputs: [{ kind: 'text', key: 'req', label: 'r' }],
    nodes: [
      { id: 'pin', kind: 'input', inputKey: 'req' } as WorkflowNode,
      {
        id: 'call1',
        kind: 'call-workflow',
        workflowName: 'child-wf',
      } as WorkflowNode,
      {
        id: 'pout',
        kind: 'output',
        ports: [{ name: 'report', bind: { nodeId: 'call1', portName: 'report' } }],
      } as WorkflowNode,
    ],
    edges: [
      {
        id: 'pe1',
        source: { nodeId: 'pin', portName: 'req' },
        target: { nodeId: 'call1', portName: 'req' },
      },
    ],
  } as WorkflowDefinition
}

interface Seeded {
  parentTaskId: string
  childWorkflowId: string
}

async function seedParentTask(h: Harness, workerId: string): Promise<Seeded> {
  const childDef = childDefinition(workerId)
  const childWorkflowId = ulid()
  await h.db.insert(workflows).values({
    id: childWorkflowId,
    name: 'child-wf',
    definition: JSON.stringify(childDef),
  })
  const parentDef = parentDefinition()
  const parentWorkflowId = ulid()
  await h.db.insert(workflows).values({
    id: parentWorkflowId,
    name: 'parent-wf',
    definition: JSON.stringify(parentDef),
  })
  const closure = JSON.stringify({
    workflows: { 'child-wf': { id: childWorkflowId, version: 1, definition: childDef } },
  })
  const parentTaskId = ulid()
  await h.db.insert(tasks).values({
    id: parentTaskId,
    name: 'rfc242-parent',
    workflowId: parentWorkflowId,
    workflowSnapshot: JSON.stringify(parentDef),
    repoPath: h.repoPath,
    worktreePath: h.worktreePath,
    baseBranch: 'main',
    branch: `agent-workflow/${parentTaskId}`,
    status: 'pending',
    inputs: JSON.stringify({ req: 'go' }),
    startedAt: Date.now(),
    refClosureJson: closure,
  })
  return { parentTaskId, childWorkflowId }
}

describe('RFC-242 e2e — call-workflow 全链', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h?.cleanup())

  test('D→L→W→F→M：继承派生、子任务独立行、输出回填、合并回父、父任务 done', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    // 父 canonical 的未提交文件 —— 子 agent 用 __FILE__ 读它证明继承可见。
    writeFileSync(join(h.worktreePath, 'parent-seed.txt'), 'UNCOMMITTED PARENT STATE')
    writeFileSync(
      h.planFile,
      JSON.stringify({
        worker: {
          files: { 'src/child-artifact.txt': 'WRITTEN BY CHILD' },
          output: { out: 'CHILD SAYS HI', echo: '__FILE__:parent-seed.txt' },
        },
      }),
    )
    const { parentTaskId } = await seedParentTask(h, workerId)
    await runTask({
      db: h.db,
      taskId: parentTaskId,
      appHome: h.appHome,
      opencodeCmd: ['bun', 'run', h.mockPath],
    })

    const parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    expect(parent.status).toBe('done')

    // 子任务独立行：父链接 + inherited 空间 + done。
    const children = await h.db.select().from(tasks).where(eq(tasks.parentTaskId, parentTaskId))
    expect(children.length).toBe(1)
    const child = children[0]!
    expect(child.status).toBe('done')
    expect(child.spaceKind).toBe('inherited')
    expect(child.invocationDepth).toBe(1)
    expect(child.name).toContain('rfc242-parent')

    // 调用行：childTaskId / done / merged / 输出回填（F）。
    const callRow = (
      await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, parentTaskId), eq(nodeRuns.nodeId, 'call1')))
    ).find((r) => r.parentNodeRunId === null)!
    expect(callRow.childTaskId).toBe(child.id)
    expect(callRow.status).toBe('done')
    expect(callRow.mergeState).toBe('merged')
    expect(child.parentNodeRunId).toBe(callRow.id)
    const callOutputs = await h.db
      .select()
      .from(nodeRunOutputs)
      .where(eq(nodeRunOutputs.nodeRunId, callRow.id))
    const byPort = new Map(callOutputs.map((o) => [o.portName, o.content]))
    expect(byPort.get('report')).toBe('CHILD SAYS HI')
    // D5 继承：子 agent 在自己的工作区读到了父 canonical 的未提交文件。
    expect(byPort.get('echo')).toBe('UNCOMMITTED PARENT STATE')

    // M 合并回：子任务写盘的文件出现在父 canonical。
    const merged = join(h.worktreePath, 'src', 'child-artifact.txt')
    expect(existsSync(merged)).toBe(true)
    expect(readFileSync(merged, 'utf8')).toBe('WRITTEN BY CHILD')

    // 父 output 节点消费 call 端口。
    const outRow = (
      await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, parentTaskId), eq(nodeRuns.nodeId, 'pout')))
    )[0]!
    const outPorts = await h.db
      .select()
      .from(nodeRunOutputs)
      .where(eq(nodeRunOutputs.nodeRunId, outRow.id))
    expect(outPorts.find((o) => o.portName === 'report')?.content).toBe('CHILD SAYS HI')
  })

  test('子任务失败 → 调用行 failed(child-task-failed) → 父任务 failed', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    writeFileSync(h.planFile, JSON.stringify({ worker: { exitCode: 3 } }))
    const { parentTaskId } = await seedParentTask(h, workerId)
    await runTask({
      db: h.db,
      taskId: parentTaskId,
      appHome: h.appHome,
      opencodeCmd: ['bun', 'run', h.mockPath],
      // 子任务 agent 重试烧时间——压到 0 让失败立即冒泡。
      defaultNodeRetries: 0,
    })
    const parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    expect(parent.status).toBe('failed')
    const children = await h.db.select().from(tasks).where(eq(tasks.parentTaskId, parentTaskId))
    expect(children.length).toBe(1)
    expect(children[0]!.status).toBe('failed')
    const callRow = (
      await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, parentTaskId), eq(nodeRuns.nodeId, 'call1')))
    ).find((r) => r.parentNodeRunId === null)!
    expect(callRow.status).toBe('failed')
    expect(callRow.failureCode).toBe('child-task-failed')
  })
})

describe('RFC-242 e2e — 生命周期', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h?.cleanup())

  test('mid-flight 取消父任务：级联取消子任务并落 durable 标记，调用行 canceled', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    // worker 挂起：hang 计划项让子任务停在 running。
    writeFileSync(h.planFile, JSON.stringify({ worker: { hangMs: 120000 } }))
    const { parentTaskId } = await seedParentTask(h, workerId)
    const { cancelTask } = await import('../src/services/task')
    const running = runTask({
      db: h.db,
      taskId: parentTaskId,
      appHome: h.appHome,
      opencodeCmd: ['bun', 'run', h.mockPath],
    })
    // 等到子任务出现且 running（budget→iso→launch 全链完成）。
    let childId: string | null = null
    for (let i = 0; i < 200 && childId === null; i++) {
      const rows = await h.db.select().from(tasks).where(eq(tasks.parentTaskId, parentTaskId))
      if (rows[0]?.status === 'running') childId = rows[0].id
      else await Bun.sleep(50)
    }
    expect(childId).not.toBeNull()
    await cancelTask(h.db, parentTaskId)
    await running
    const parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    const child = (await h.db.select().from(tasks).where(eq(tasks.id, childId!)))[0]!
    expect(parent.status).toBe('canceled')
    expect(child.status).toBe('canceled')
    expect(child.errorMessage).toBe('canceled-by-parent-cascade')
    const callRow = (
      await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, parentTaskId), eq(nodeRuns.nodeId, 'call1')))
    ).find((r) => r.parentNodeRunId === null)!
    expect(['canceled', 'failed']).toContain(callRow.status)
  }, 30000)

  test('重试调用节点：旧子任务保留为历史行，新子任务全新发起并成功', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    writeFileSync(h.planFile, JSON.stringify({ worker: { exitCode: 3 } }))
    const { parentTaskId } = await seedParentTask(h, workerId)
    await runTask({
      db: h.db,
      taskId: parentTaskId,
      appHome: h.appHome,
      opencodeCmd: ['bun', 'run', h.mockPath],
      defaultNodeRetries: 0,
    })
    const failedCall = (
      await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, parentTaskId), eq(nodeRuns.nodeId, 'call1')))
    ).find((r) => r.parentNodeRunId === null)!
    expect(failedCall.status).toBe('failed')
    // 修好计划 → retryNode 换代。
    writeFileSync(
      h.planFile,
      JSON.stringify({ worker: { output: { out: 'SECOND TRY', echo: 'x' } } }),
    )
    const { retryNode } = await import('../src/services/task')
    await retryNode(h.db, parentTaskId, failedCall.id, {
      deps: {
        db: h.db,
        appHome: h.appHome,
        opencodeCmd: ['bun', 'run', h.mockPath],
      } as unknown as StartTaskDeps,
    })
    // retryNode 的 kick 是 fire-and-forget —— 轮询到终态再断言。
    let parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    for (let i = 0; i < 300 && !['done', 'failed', 'canceled'].includes(parent.status); i++) {
      await Bun.sleep(50)
      parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    }
    expect(parent.status).toBe('done')
    const children = await h.db.select().from(tasks).where(eq(tasks.parentTaskId, parentTaskId))
    expect(children.length).toBe(2) // 旧 failed 历史行 + 新 done
    expect(children.map((c) => c.status).sort()).toEqual(['done', 'failed'])
  }, 30000)
})

describe('RFC-242 §3.1 — freezeCallClosure', () => {
  test('无 call 节点 → null；缺引用/环 → 专码', async () => {
    const db = createInMemoryDb(MIGRATIONS)
    const plain: WorkflowDefinition = {
      $schema_version: 4,
      inputs: [],
      nodes: [],
      edges: [],
    } as WorkflowDefinition
    expect(await freezeCallClosure(db, { id: 'W0', definition: plain })).toBeNull()

    const callsMissing = {
      $schema_version: 4,
      inputs: [],
      nodes: [{ id: 'c', kind: 'call-workflow', workflowName: 'ghost' }],
      edges: [],
    } as unknown as WorkflowDefinition
    await expect(
      freezeCallClosure(db, { id: 'W0', definition: callsMissing }),
    ).rejects.toMatchObject({ code: 'workflow-call-ref-missing' })

    // A(root) → B → A 环：B 在库里、其定义回指 root 的 name——环检测按冻结图。
    const defB = {
      $schema_version: 4,
      inputs: [],
      nodes: [{ id: 'cb', kind: 'call-workflow', workflowName: 'wf-a' }],
      edges: [],
    }
    const idA = ulid()
    const idB = ulid()
    await db.insert(workflows).values({ id: idB, name: 'wf-b', definition: JSON.stringify(defB) })
    const defA = {
      $schema_version: 4,
      inputs: [],
      nodes: [{ id: 'ca', kind: 'call-workflow', workflowName: 'wf-b' }],
      edges: [],
    }
    await db.insert(workflows).values({ id: idA, name: 'wf-a', definition: JSON.stringify(defA) })
    const err = await freezeCallClosure(db, {
      id: idA,
      definition: defA as unknown as WorkflowDefinition,
    }).then(
      () => null,
      (e: unknown) => e as { code: string; detail?: { cycle?: string[] } },
    )
    expect(err?.code).toBe('workflow-call-cycle')
    const payload = JSON.stringify(err)
    expect(payload).not.toContain('wf-a') // id-only 载荷（RFC-099 回显纪律）
    expect(payload).not.toContain('wf-b')
  })

  test('PR-4：workgroups 叶随冻结入闭包（完整 roster）；缺失同码拒绝', async () => {
    const db = createInMemoryDb(MIGRATIONS)
    const defWithWg = {
      $schema_version: 4,
      inputs: [],
      nodes: [{ id: 'cw', kind: 'call-workgroup', workgroupName: 'ghost-wg', goalTemplate: 'g' }],
      edges: [],
    } as unknown as WorkflowDefinition
    await expect(freezeCallClosure(db, { id: 'W0', definition: defWithWg })).rejects.toMatchObject({
      code: 'workflow-call-ref-missing',
    })
    const { createAgent } = await import('../src/services/agent')
    const { createWorkgroup } = await import('../src/services/workgroups')
    const { buildActor } = await import('../src/auth/actor')
    const actor = buildActor({
      user: { id: 'u-z', username: 'z', displayName: 'z', role: 'admin', status: 'active' },
      source: 'daemon',
    })
    const agent = await createAgent(db, {
      name: 'wg-a',
      description: '',
      outputs: [],
      syncOutputsOnIterate: true,
      permission: {},
      skills: [],
      dependsOn: [],
      mcp: [],
      plugins: [],
      frontmatterExtra: {},
      bodyMd: 'x',
    })
    const group = await createWorkgroup(
      db,
      {
        name: 'ghost-wg',
        description: '',
        instructions: '',
        mode: 'free_collab',
        autonomous: true,
        switches: { shareOutputs: true, directMessages: true, blackboard: true },
        maxRounds: 4,
        completionGate: false,
        members: [{ memberType: 'agent', agentId: agent.id, displayName: 'a', roleDesc: 'r' }],
      } as Parameters<typeof createWorkgroup>[1],
      { ownerUserId: actor.user.id, actor },
    )
    const json = await freezeCallClosure(db, { id: 'W0', definition: defWithWg })
    expect(json).not.toBeNull()
    const parsed = JSON.parse(json!) as {
      workgroups: Record<string, { id: string; group: { members: unknown[] } }>
    }
    expect(parsed.workgroups['ghost-wg']?.id).toBe(group.id)
    expect(parsed.workgroups['ghost-wg']?.group.members.length).toBe(1)
  })
})
