// RFC-243 PR-3 — call-workflow 节点端到端（design §6.2 D→L→W→F→M 全链）。
//
// Locks in:
//   1. 父任务的 call 节点从冻结闭包起独立子任务：子任务行 parentTaskId /
//      parentNodeRunId / invocationDepth=1 / spaceKind='inherited'，其 canonical
//      即调用行的 iso worktree。
//   2. 工作区继承（D5）：父 canonical 的【未提交】文件对子任务的 agent 可见
//      （通过 iso 派生 —— snapshotFullState 含未提交/untracked）。
//   3. 子任务 done → F 输出回填（call 行 node_run_outputs = 子任务 output 投影）
//      → M 合并回（子任务写盘文件落回父 canonical）→ 调用行 done+merged →
//      父 output 节点消费 call 端口 → 父任务 done。
//   4. 子任务失败 → 调用行 failed(child-task-failed) → 父任务 failed（错误
//      摘要携带子任务信息）。
//   5. freezeCallClosure 纯服务：无 call 节点 → null；引用缺失 →
//      workflow-call-ref-missing；A→B→A → workflow-call-cycle（id-only 载荷）。
import { afterEach, beforeEach, describe, expect, test } from 'bun:test'
import { existsSync, mkdirSync, readFileSync, rmSync, mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { monotonicFactory } from 'ulid'
import { and, eq } from 'drizzle-orm'
import type { WorkflowDefinition, WorkflowNode } from '@agent-workflow/shared'
import { createInMemoryDb, type DbClient } from '../src/db/client'
import { agents, nodeRunOutputs, nodeRuns, tasks, workflows } from '../src/db/schema'
import { runTask } from '../src/services/scheduler'
import type { StartTaskDeps } from '../src/services/task'
import { freezeCallClosure } from '../src/services/execution/closure'
import { buildActor } from '../src/auth/actor'

const closureActor = buildActor({
  user: { id: 'u-closure', username: 'closure', displayName: 'c', role: 'admin', status: 'active' },
  source: 'daemon',
})
import { runGit } from '../src/util/git'
import { seedTestDefaultOpencodeRuntime } from './helpers/executionRuntimeFixture'

const ulid = monotonicFactory()
const MIGRATIONS = resolve(import.meta.dir, '..', 'db', 'migrations')

interface Harness {
  db: DbClient
  appHome: string
  repoPath: string
  worktreePath: string
  mockPath: string
  planFile: string
  cleanup: () => void
}

// mock runtime：按 --agent 查 plan，写文件 + 发 <workflow-output> 信封。
// `__FILE__:rel` 端口值 = 读该 agent 自己 CWD（= 子任务 iso）下 rel 的内容 ——
// 用它证明「父 canonical 未提交文件出现在子任务的工作区里」。exitCode 非 0
// 的 plan 项用来构造子任务失败。
function mockSource(planFile: string): string {
  return `// generated by rfc243-call-workflow.test.ts
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
const argv = process.argv.slice(2)
if (argv.includes('--version')) { process.stdout.write('rfc243-call-mock 1.14.99\\n'); process.exit(0) }
if (argv[0] !== 'run') { process.stderr.write('rfc243-call-mock: expected run\\n'); process.exit(2) }
const nonce = /\\bnonce="([^"]+)"/.exec(argv.includes('--') ? argv.slice(argv.indexOf('--') + 1).join(' ') : (argv[1] ?? ''))?.[1]
const outputOpen =
  nonce === undefined ? '<workflow-output>' : '<workflow-output nonce="' + nonce + '">'
const ai = argv.indexOf('--agent')
const agent = ai >= 0 ? (argv[ai + 1] ?? '') : ''
const plan = JSON.parse(readFileSync(${JSON.stringify(planFile)}, 'utf-8'))
const step = plan[agent] ?? {}
if (step.hangMs !== undefined) { await Bun.sleep(step.hangMs); process.exit(1) }
if (step.exitCode !== undefined) { process.stderr.write('planned failure\\n'); process.exit(step.exitCode) }
for (const [rel, content] of Object.entries(step.files ?? {})) {
  const abs = join(process.cwd(), rel)
  mkdirSync(dirname(abs), { recursive: true })
  writeFileSync(abs, String(content))
}
function emit(text) {
  process.stdout.write(JSON.stringify({ type: 'text', timestamp: Date.now(), part: { type: 'text', text } }) + '\\n')
}
let envelope = outputOpen + '\\n'
for (const [p, c] of Object.entries(step.output ?? {})) {
  let v = String(c)
  if (v.startsWith('__FILE__:')) {
    const rel = v.slice('__FILE__:'.length)
    try { v = readFileSync(join(process.cwd(), rel), 'utf8') } catch { v = 'FILE-MISSING:' + rel }
  }
  envelope += '  <port name="' + p + '">' + v + '</port>\\n'
}
envelope += '</workflow-output>'
emit(envelope)
process.exit(0)
`
}

async function buildHarness(): Promise<Harness> {
  const appHome = mkdtempSync(join(tmpdir(), 'aw-rfc243-call-'))
  const repoPath = join(appHome, 'repo')
  const worktreePath = join(appHome, 'wt')
  const planFile = join(appHome, 'plan.json')
  const mockPath = join(appHome, 'mock.ts')
  for (const p of [repoPath, worktreePath]) {
    mkdirSync(p, { recursive: true })
    await runGit(p, ['init', '-b', 'main'])
    await runGit(p, ['config', 'user.email', 't@t.test'])
    await runGit(p, ['config', 'user.name', 't'])
    writeFileSync(join(p, 'README.md'), '# r\n')
    await runGit(p, ['add', '.'])
    await runGit(p, ['commit', '-m', 'init'])
  }
  writeFileSync(mockPath, mockSource(planFile))
  const db = createInMemoryDb(MIGRATIONS)
  await seedTestDefaultOpencodeRuntime(db)
  return {
    db,
    appHome,
    repoPath,
    worktreePath,
    mockPath,
    planFile,
    cleanup: () => rmSync(appHome, { recursive: true, force: true }),
  }
}

async function seedAgent(db: DbClient, name: string, outputs: string[]): Promise<string> {
  const id = ulid()
  await db.insert(agents).values({
    id,
    name,
    description: 'test',
    outputs: JSON.stringify(outputs),
    permission: '{}',
    skills: '[]',
    frontmatterExtra: '{}',
    bodyMd: '',
  })
  return id
}

function childDefinition(workerId: string): WorkflowDefinition {
  return {
    $schema_version: 4,
    inputs: [{ kind: 'text', key: 'req', label: 'r' }],
    nodes: [
      { id: 'cin', kind: 'input', inputKey: 'req' } as WorkflowNode,
      {
        id: 'work',
        kind: 'agent-single',
        agentId: workerId,
        agentName: 'worker',
        promptTemplate: 'do {{req}}',
      } as WorkflowNode,
      {
        id: 'cout',
        kind: 'output',
        ports: [
          { name: 'report', bind: { nodeId: 'work', portName: 'out' } },
          { name: 'echo', bind: { nodeId: 'work', portName: 'echo' } },
        ],
      } as WorkflowNode,
    ],
    edges: [
      {
        id: 'e1',
        source: { nodeId: 'cin', portName: 'req' },
        target: { nodeId: 'work', portName: 'req' },
      },
    ],
  } as WorkflowDefinition
}

function parentDefinition(): WorkflowDefinition {
  return {
    $schema_version: 4,
    inputs: [{ kind: 'text', key: 'req', label: 'r' }],
    nodes: [
      { id: 'pin', kind: 'input', inputKey: 'req' } as WorkflowNode,
      {
        id: 'call1',
        kind: 'call-workflow',
        workflowName: 'child-wf',
      } as WorkflowNode,
      {
        id: 'pout',
        kind: 'output',
        ports: [{ name: 'report', bind: { nodeId: 'call1', portName: 'report' } }],
      } as WorkflowNode,
    ],
    edges: [
      {
        id: 'pe1',
        source: { nodeId: 'pin', portName: 'req' },
        target: { nodeId: 'call1', portName: 'req' },
      },
    ],
  } as WorkflowDefinition
}

interface Seeded {
  parentTaskId: string
  childWorkflowId: string
}

async function seedParentTask(h: Harness, workerId: string): Promise<Seeded> {
  const childDef = childDefinition(workerId)
  const childWorkflowId = ulid()
  await h.db.insert(workflows).values({
    id: childWorkflowId,
    name: 'child-wf',
    definition: JSON.stringify(childDef),
  })
  const parentDef = parentDefinition()
  const parentWorkflowId = ulid()
  await h.db.insert(workflows).values({
    id: parentWorkflowId,
    name: 'parent-wf',
    definition: JSON.stringify(parentDef),
  })
  const closure = JSON.stringify({
    workflows: { 'child-wf': { id: childWorkflowId, version: 1, definition: childDef } },
  })
  const parentTaskId = ulid()
  await h.db.insert(tasks).values({
    id: parentTaskId,
    name: 'rfc243-parent',
    workflowId: parentWorkflowId,
    workflowSnapshot: JSON.stringify(parentDef),
    repoPath: h.repoPath,
    worktreePath: h.worktreePath,
    baseBranch: 'main',
    branch: `agent-workflow/${parentTaskId}`,
    status: 'pending',
    inputs: JSON.stringify({ req: 'go' }),
    startedAt: Date.now(),
    refClosureJson: closure,
  })
  return { parentTaskId, childWorkflowId }
}

describe('RFC-243 e2e — call-workflow 全链', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h?.cleanup())

  test('D→L→W→F→M：继承派生、子任务独立行、输出回填、合并回父、父任务 done', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    // 父 canonical 的未提交文件 —— 子 agent 用 __FILE__ 读它证明继承可见。
    writeFileSync(join(h.worktreePath, 'parent-seed.txt'), 'UNCOMMITTED PARENT STATE')
    writeFileSync(
      h.planFile,
      JSON.stringify({
        worker: {
          files: { 'src/child-artifact.txt': 'WRITTEN BY CHILD' },
          output: { out: 'CHILD SAYS HI', echo: '__FILE__:parent-seed.txt' },
        },
      }),
    )
    const { parentTaskId } = await seedParentTask(h, workerId)
    await runTask({
      db: h.db,
      taskId: parentTaskId,
      appHome: h.appHome,
      binaryOverride: ['bun', 'run', h.mockPath],
    })

    const parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    expect(parent.status).toBe('done')

    // 子任务独立行：父链接 + inherited 空间 + done。
    const children = await h.db.select().from(tasks).where(eq(tasks.parentTaskId, parentTaskId))
    expect(children.length).toBe(1)
    const child = children[0]!
    expect(child.status).toBe('done')
    expect(child.spaceKind).toBe('inherited')
    expect(child.invocationDepth).toBe(1)
    expect(child.name).toContain('rfc243-parent')

    // 调用行：childTaskId / done / merged / 输出回填（F）。
    const callRow = (
      await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, parentTaskId), eq(nodeRuns.nodeId, 'call1')))
    ).find((r) => r.parentNodeRunId === null)!
    expect(callRow.childTaskId).toBe(child.id)
    expect(callRow.status).toBe('done')
    expect(callRow.mergeState).toBe('merged')
    expect(child.parentNodeRunId).toBe(callRow.id)
    const callOutputs = await h.db
      .select()
      .from(nodeRunOutputs)
      .where(eq(nodeRunOutputs.nodeRunId, callRow.id))
    const byPort = new Map(callOutputs.map((o) => [o.portName, o.content]))
    expect(byPort.get('report')).toBe('CHILD SAYS HI')
    // D5 继承：子 agent 在自己的工作区读到了父 canonical 的未提交文件。
    expect(byPort.get('echo')).toBe('UNCOMMITTED PARENT STATE')

    // M 合并回：子任务写盘的文件出现在父 canonical。
    const merged = join(h.worktreePath, 'src', 'child-artifact.txt')
    expect(existsSync(merged)).toBe(true)
    expect(readFileSync(merged, 'utf8')).toBe('WRITTEN BY CHILD')

    // 父 output 节点消费 call 端口。
    const outRow = (
      await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, parentTaskId), eq(nodeRuns.nodeId, 'pout')))
    )[0]!
    const outPorts = await h.db
      .select()
      .from(nodeRunOutputs)
      .where(eq(nodeRunOutputs.nodeRunId, outRow.id))
    expect(outPorts.find((o) => o.portName === 'report')?.content).toBe('CHILD SAYS HI')
  })

  test('RFC-292: child task atomically inherits nested context and expands it in child agent prompt', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    writeFileSync(
      h.planFile,
      JSON.stringify({ worker: { output: { out: 'CHILD', echo: 'context' } } }),
    )
    const { parentTaskId } = await seedParentTask(h, workerId)
    const parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    const closure = JSON.parse(parent.refClosureJson!) as {
      workflows: Record<
        string,
        { definition: { $schema_version: number; nodes: Array<Record<string, unknown>> } }
      >
    }
    const child = closure.workflows['child-wf']!.definition
    child.$schema_version = 5
    const worker = child.nodes.find((node) => node.id === 'work')!
    worker.promptTemplate = 'do {{req}} / {{trigger.webhook.comment_text}}'
    const context = {
      trigger: {
        webhook: {
          event_type: 'note',
          comment_text: 'child-inherited-trigger',
        },
      },
    }
    await h.db
      .update(tasks)
      .set({
        refClosureJson: JSON.stringify(closure),
        triggerContextJson: JSON.stringify(context),
      })
      .where(eq(tasks.id, parentTaskId))

    await runTask({
      db: h.db,
      taskId: parentTaskId,
      appHome: h.appHome,
      binaryOverride: ['bun', 'run', h.mockPath],
    })

    const childTask = (
      await h.db.select().from(tasks).where(eq(tasks.parentTaskId, parentTaskId))
    )[0]!
    expect(JSON.parse(childTask.triggerContextJson!)).toEqual(context)
    const childRun = (
      await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, childTask.id), eq(nodeRuns.nodeId, 'work')))
    )[0]!
    expect(childRun.promptText).toContain('child-inherited-trigger')
    expect(childRun.promptText).not.toContain('{{trigger.webhook.comment_text}}')
  })

  test('子任务失败 → 调用行 failed(child-task-failed) → 父任务 failed', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    writeFileSync(h.planFile, JSON.stringify({ worker: { exitCode: 3 } }))
    const { parentTaskId } = await seedParentTask(h, workerId)
    await runTask({
      db: h.db,
      taskId: parentTaskId,
      appHome: h.appHome,
      binaryOverride: ['bun', 'run', h.mockPath],
      // 子任务 agent 重试烧时间——压到 0 让失败立即冒泡。
      defaultNodeRetries: 0,
    })
    const parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    expect(parent.status).toBe('failed')
    const children = await h.db.select().from(tasks).where(eq(tasks.parentTaskId, parentTaskId))
    expect(children.length).toBe(1)
    expect(children[0]!.status).toBe('failed')
    const callRow = (
      await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, parentTaskId), eq(nodeRuns.nodeId, 'call1')))
    ).find((r) => r.parentNodeRunId === null)!
    expect(callRow.status).toBe('failed')
    expect(callRow.failureCode).toBe('child-task-failed')
  })
})

describe('RFC-243 e2e — 生命周期', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h?.cleanup())

  test('mid-flight 取消父任务：级联取消子任务并落 durable 标记，调用行 canceled', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    // worker 挂起：hang 计划项让子任务停在 running。
    writeFileSync(h.planFile, JSON.stringify({ worker: { hangMs: 120000 } }))
    const { parentTaskId } = await seedParentTask(h, workerId)
    const { cancelTask } = await import('../src/services/task')
    const running = runTask({
      db: h.db,
      taskId: parentTaskId,
      appHome: h.appHome,
      binaryOverride: ['bun', 'run', h.mockPath],
    })
    // 等到子任务出现且 running（budget→iso→launch 全链完成）。
    let childId: string | null = null
    for (let i = 0; i < 200 && childId === null; i++) {
      const rows = await h.db.select().from(tasks).where(eq(tasks.parentTaskId, parentTaskId))
      if (rows[0]?.status === 'running') childId = rows[0].id
      else await Bun.sleep(50)
    }
    expect(childId).not.toBeNull()
    await cancelTask(h.db, parentTaskId)
    await running
    const parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    const child = (await h.db.select().from(tasks).where(eq(tasks.id, childId!)))[0]!
    expect(parent.status).toBe('canceled')
    expect(child.status).toBe('canceled')
    expect(child.errorMessage).toBe('canceled-by-parent-cascade')
    const callRow = (
      await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, parentTaskId), eq(nodeRuns.nodeId, 'call1')))
    ).find((r) => r.parentNodeRunId === null)!
    expect(['canceled', 'failed']).toContain(callRow.status)
  }, 30000)

  test('重试调用节点：旧子任务保留为历史行，新子任务全新发起并成功', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    writeFileSync(h.planFile, JSON.stringify({ worker: { exitCode: 3 } }))
    const { parentTaskId } = await seedParentTask(h, workerId)
    await runTask({
      db: h.db,
      taskId: parentTaskId,
      appHome: h.appHome,
      binaryOverride: ['bun', 'run', h.mockPath],
      defaultNodeRetries: 0,
    })
    const failedCall = (
      await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, parentTaskId), eq(nodeRuns.nodeId, 'call1')))
    ).find((r) => r.parentNodeRunId === null)!
    expect(failedCall.status).toBe('failed')
    // 修好计划 → retryNode 换代。
    writeFileSync(
      h.planFile,
      JSON.stringify({ worker: { output: { out: 'SECOND TRY', echo: 'x' } } }),
    )
    const { retryNode } = await import('../src/services/task')
    await retryNode(h.db, parentTaskId, failedCall.id, {
      deps: {
        db: h.db,
        appHome: h.appHome,
        binaryOverride: ['bun', 'run', h.mockPath],
      } as unknown as StartTaskDeps,
    })
    // retryNode 的 kick 是 fire-and-forget —— 轮询到终态再断言。
    let parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    for (let i = 0; i < 300 && !['done', 'failed', 'canceled'].includes(parent.status); i++) {
      await Bun.sleep(50)
      parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    }
    expect(parent.status).toBe('done')
    const children = await h.db.select().from(tasks).where(eq(tasks.parentTaskId, parentTaskId))
    expect(children.length).toBe(2) // 旧 failed 历史行 + 新 done
    expect(children.map((c) => c.status).sort()).toEqual(['done', 'failed'])
  }, 30000)
})

describe('RFC-243 e2e — 叠加形态与恢复矩阵（实现门 P1-5 / 验收 4·9）', () => {
  let h: Harness
  beforeEach(async () => {
    h = await buildHarness()
  })
  afterEach(() => h?.cleanup())

  function loopParentDefinition(): WorkflowDefinition {
    return {
      $schema_version: 4,
      inputs: [{ kind: 'text', key: 'req', label: 'r' }],
      nodes: [
        { id: 'pin', kind: 'input', inputKey: 'req' } as WorkflowNode,
        {
          id: 'lp',
          kind: 'wrapper-loop',
          nodeIds: ['call1'],
          maxIterations: 2,
          continueOnMaxIterations: true,
          exitCondition: {
            kind: 'port-equals',
            nodeId: 'call1',
            portName: 'report',
            value: 'NEVER',
          },
          outputBindings: [{ name: 'final', bind: { nodeId: 'call1', portName: 'report' } }],
        } as unknown as WorkflowNode,
        { id: 'call1', kind: 'call-workflow', workflowName: 'child-wf' } as WorkflowNode,
      ],
      edges: [
        {
          id: 'pe1',
          source: { nodeId: 'pin', portName: 'req' },
          target: { nodeId: 'call1', portName: 'req' },
          boundary: 'wrapper-input',
        },
      ],
    } as unknown as WorkflowDefinition
  }

  test('loop 内 call：每轮一个独立子任务（验收 4）', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    writeFileSync(
      h.planFile,
      JSON.stringify({ worker: { output: { out: 'ROUND OUTPUT', echo: 'x' } } }),
    )
    const seeded = await seedParentTask(h, workerId)
    // 换成 loop 形态快照（复用已入库的 child-wf 与闭包）。
    await h.db
      .update(tasks)
      .set({ workflowSnapshot: JSON.stringify(loopParentDefinition()) })
      .where(eq(tasks.id, seeded.parentTaskId))
    await runTask({
      db: h.db,
      taskId: seeded.parentTaskId,
      appHome: h.appHome,
      binaryOverride: ['bun', 'run', h.mockPath],
    })
    const parent = (await h.db.select().from(tasks).where(eq(tasks.id, seeded.parentTaskId)))[0]!
    expect(parent.status).toBe('done')
    const children = await h.db
      .select()
      .from(tasks)
      .where(eq(tasks.parentTaskId, seeded.parentTaskId))
    expect(children.length).toBe(2) // 每轮一个
    expect(children.every((c) => c.status === 'done')).toBe(true)
  }, 40000)

  test('git wrapper 内 call：子任务写盘计入 git_diff 窗口（验收 9 / 开放问题 4）', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    writeFileSync(
      h.planFile,
      JSON.stringify({
        worker: {
          files: { 'src/from-child.txt': 'CHILD IN GIT WRAPPER' },
          output: { out: 'ok', echo: 'x' },
        },
      }),
    )
    const seeded = await seedParentTask(h, workerId)
    const gitDef = {
      $schema_version: 4,
      inputs: [{ kind: 'text', key: 'req', label: 'r' }],
      nodes: [
        { id: 'pin', kind: 'input', inputKey: 'req' },
        { id: 'gw', kind: 'wrapper-git', nodeIds: ['call1'] },
        { id: 'call1', kind: 'call-workflow', workflowName: 'child-wf' },
        {
          id: 'pout',
          kind: 'output',
          ports: [{ name: 'diff', bind: { nodeId: 'gw', portName: 'git_diff' } }],
        },
      ],
      edges: [
        {
          id: 'pe1',
          source: { nodeId: 'pin', portName: 'req' },
          target: { nodeId: 'call1', portName: 'req' },
          boundary: 'wrapper-input',
        },
      ],
    } as unknown as WorkflowDefinition
    await h.db
      .update(tasks)
      .set({ workflowSnapshot: JSON.stringify(gitDef) })
      .where(eq(tasks.id, seeded.parentTaskId))
    await runTask({
      db: h.db,
      taskId: seeded.parentTaskId,
      appHome: h.appHome,
      binaryOverride: ['bun', 'run', h.mockPath],
    })
    const parent = (await h.db.select().from(tasks).where(eq(tasks.id, seeded.parentTaskId)))[0]!
    expect(parent.status).toBe('done')
    const gwRow = (
      await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, seeded.parentTaskId), eq(nodeRuns.nodeId, 'gw')))
    ).find((r) => r.parentNodeRunId === null)!
    const gwOutputs = await h.db
      .select()
      .from(nodeRunOutputs)
      .where(eq(nodeRunOutputs.nodeRunId, gwRow.id))
    expect(gwOutputs.find((o) => o.portName === 'git_diff')?.content ?? '').toContain(
      'src/from-child.txt',
    )
  }, 40000)

  test('daemon 重启恢复：shutdown 打断 → reap → resume 领养同一子任务收尾（P1-5 分支 1/2）', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    writeFileSync(h.planFile, JSON.stringify({ worker: { hangMs: 120000 } }))
    const { parentTaskId } = await seedParentTask(h, workerId)
    const { DAEMON_SHUTDOWN_ABORT_REASON } = await import('@agent-workflow/shared')
    const { abortAllActiveTasks, isTaskActive, resumeTask } = await import('../src/services/task')
    // 父任务在生产里由 startTask 注册 activeTasks 并持 signal；直连 runTask 的
    // 测试必须自带 controller，否则「关停」只打到子任务，父侧判据无从谈起。
    const parentCtrl = new AbortController()
    const running = runTask({
      db: h.db,
      taskId: parentTaskId,
      appHome: h.appHome,
      binaryOverride: ['bun', 'run', h.mockPath],
      signal: parentCtrl.signal,
    })
    let childId: string | null = null
    for (let i = 0; i < 200 && childId === null; i++) {
      const rows = await h.db.select().from(tasks).where(eq(tasks.parentTaskId, parentTaskId))
      if (rows[0]?.status === 'running') childId = rows[0].id
      else await Bun.sleep(50)
    }
    expect(childId).not.toBeNull()
    abortAllActiveTasks(DAEMON_SHUTDOWN_ABORT_REASON)
    parentCtrl.abort(DAEMON_SHUTDOWN_ABORT_REASON)
    await running
    // 忠实模拟「daemon 重启后的新进程」：等本进程的驱动全部收尾，activeTasks
    // 清空（真实重启后该表天然为空）。不等的话子任务仍被本进程持有，
    // resume 会以 task-active 冲突——那是测试假象，不是恢复语义。
    for (let i = 0; i < 200; i++) {
      const rows = await h.db.select().from(tasks)
      if (!rows.some((t) => isTaskActive(t.id))) break
      await Bun.sleep(50)
    }
    // boot reap（孤儿收割）把父子与残行翻 interrupted。
    const { reapOrphanRuns } = await import('../src/services/orphans')
    await reapOrphanRuns(h.db)
    // 修好计划再恢复。
    writeFileSync(h.planFile, JSON.stringify({ worker: { output: { out: 'RESUMED', echo: 'x' } } }))
    await resumeTask(h.db, parentTaskId, {
      db: h.db,
      appHome: h.appHome,
      binaryOverride: ['bun', 'run', h.mockPath],
      awaitScheduler: true,
    } as unknown as StartTaskDeps)
    const parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    expect(parent.status).toBe('done')
    const children = await h.db.select().from(tasks).where(eq(tasks.parentTaskId, parentTaskId))
    expect(children.length).toBe(1) // 领养同一子任务，绝不重复发起
    expect(children[0]!.id).toBe(childId!)
    expect(children[0]!.status).toBe('done')
    // 调用行原地复用（retryIndex 不递增）——领养绝不 mint 新代，否则
    // abandonSupersededMergeStates 会作废子任务 canonical 所在的 iso 世代。
    const callRows = (
      await h.db
        .select()
        .from(nodeRuns)
        .where(and(eq(nodeRuns.taskId, parentTaskId), eq(nodeRuns.nodeId, 'call1')))
    ).filter((r) => r.parentNodeRunId === null)
    expect(callRows.length).toBe(1)
    expect(callRows[0]!.retryIndex).toBe(0)
    expect(callRows[0]!.mergeState).toBe('merged')
  }, 40000)

  test('R-merged 分段：子已 done+已合并、调用行 interrupted → 领养只补 F 与终态（P1-5 分支 3）', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    void workerId
    const { parentTaskId, childWorkflowId } = await seedParentTask(h, workerId)
    // 构造崩溃后现场：子任务 done + 输出行在库；调用行 interrupted、
    // mergeState='merged'（合并早已完成）；父任务 pending 等待重驱。
    const childId = ulid()
    await h.db.insert(tasks).values({
      id: childId,
      name: 'seeded-child',
      workflowId: childWorkflowId,
      workflowSnapshot: JSON.stringify(childDefinition(workerId)),
      repoPath: h.repoPath,
      worktreePath: h.worktreePath,
      baseBranch: 'main',
      branch: `agent-workflow/${childId}`,
      status: 'done',
      inputs: JSON.stringify({ req: 'go' }),
      startedAt: Date.now() - 60_000,
      finishedAt: Date.now() - 30_000,
      parentTaskId,
      invocationDepth: 1,
      spaceKind: 'inherited',
    })
    const childOut = ulid()
    await h.db.insert(nodeRuns).values({
      id: childOut,
      taskId: childId,
      nodeId: 'cout',
      status: 'done',
      retryIndex: 0,
      iteration: 0,
      startedAt: Date.now() - 60_000,
      finishedAt: Date.now() - 30_000,
    })
    await h.db.insert(nodeRunOutputs).values({
      nodeRunId: childOut,
      portName: 'report',
      content: 'MERGED ALREADY',
      kind: 'text',
    })
    const callRun = ulid()
    await h.db.insert(nodeRuns).values({
      id: callRun,
      taskId: parentTaskId,
      nodeId: 'call1',
      status: 'interrupted',
      retryIndex: 0,
      iteration: 0,
      startedAt: Date.now() - 60_000,
      childTaskId: childId,
      mergeState: 'merged',
    })
    await h.db.update(tasks).set({ parentNodeRunId: callRun }).where(eq(tasks.id, childId))
    await runTask({
      db: h.db,
      taskId: parentTaskId,
      appHome: h.appHome,
      binaryOverride: ['bun', 'run', h.mockPath],
    })
    const parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    expect(parent.status).toBe('done')
    const row = (await h.db.select().from(nodeRuns).where(eq(nodeRuns.id, callRun)))[0]!
    expect(row.status).toBe('done')
    const outs = await h.db
      .select()
      .from(nodeRunOutputs)
      .where(eq(nodeRunOutputs.nodeRunId, callRun))
    expect(outs.find((o) => o.portName === 'report')?.content).toBe('MERGED ALREADY')
    // 领养复用同一行：无新代 call 行。
    const callRows = await h.db
      .select()
      .from(nodeRuns)
      .where(and(eq(nodeRuns.taskId, parentTaskId), eq(nodeRuns.nodeId, 'call1')))
    expect(callRows.length).toBe(1)
  })

  test('child-deleted：调用行 interrupted 指向不存在子任务 → failed(child-deleted)（P1-5 分支 4）', async () => {
    const workerId = await seedAgent(h.db, 'worker', ['out', 'echo'])
    const { parentTaskId } = await seedParentTask(h, workerId)
    const callRun = ulid()
    await h.db.insert(nodeRuns).values({
      id: callRun,
      taskId: parentTaskId,
      nodeId: 'call1',
      status: 'interrupted',
      retryIndex: 0,
      iteration: 0,
      startedAt: Date.now() - 60_000,
      childTaskId: ulid(), // 已被删除的子任务
      mergeState: null,
    })
    await runTask({
      db: h.db,
      taskId: parentTaskId,
      appHome: h.appHome,
      binaryOverride: ['bun', 'run', h.mockPath],
    })
    const row = (await h.db.select().from(nodeRuns).where(eq(nodeRuns.id, callRun)))[0]!
    expect(row.status).toBe('failed')
    expect(row.failureCode).toBe('child-deleted')
    const parent = (await h.db.select().from(tasks).where(eq(tasks.id, parentTaskId)))[0]!
    expect(parent.status).toBe('failed')
  })
})

describe('RFC-243 §3.1 — freezeCallClosure', () => {
  test('无 call 节点 → null；缺引用/环 → 专码', async () => {
    const db = createInMemoryDb(MIGRATIONS)
    const plain: WorkflowDefinition = {
      $schema_version: 4,
      inputs: [],
      nodes: [],
      edges: [],
    } as WorkflowDefinition
    expect(await freezeCallClosure(db, { id: 'W0', definition: plain }, closureActor)).toBeNull()

    const callsMissing = {
      $schema_version: 4,
      inputs: [],
      nodes: [{ id: 'c', kind: 'call-workflow', workflowName: 'ghost' }],
      edges: [],
    } as unknown as WorkflowDefinition
    await expect(
      freezeCallClosure(db, { id: 'W0', definition: callsMissing }, closureActor),
    ).rejects.toMatchObject({ code: 'workflow-call-ref-missing' })

    // A(root) → B → A 环：B 在库里、其定义回指 root 的 name——环检测按冻结图。
    const defB = {
      $schema_version: 4,
      inputs: [],
      nodes: [{ id: 'cb', kind: 'call-workflow', workflowName: 'wf-a' }],
      edges: [],
    }
    const idA = ulid()
    const idB = ulid()
    await db.insert(workflows).values({ id: idB, name: 'wf-b', definition: JSON.stringify(defB) })
    const defA = {
      $schema_version: 4,
      inputs: [],
      nodes: [{ id: 'ca', kind: 'call-workflow', workflowName: 'wf-b' }],
      edges: [],
    }
    await db.insert(workflows).values({ id: idA, name: 'wf-a', definition: JSON.stringify(defA) })
    const err = await freezeCallClosure(
      db,
      { id: idA, definition: defA as unknown as WorkflowDefinition },
      closureActor,
    ).then(
      () => null,
      (e: unknown) => e as { code: string; detail?: { cycle?: string[] } },
    )
    expect(err?.code).toBe('workflow-call-cycle')
    const payload = JSON.stringify(err)
    expect(payload).not.toContain('wf-a') // id-only 载荷（RFC-099 回显纪律）
    expect(payload).not.toContain('wf-b')
  })

  test('PR-4：workgroups 叶随冻结入闭包（完整 roster）；缺失同码拒绝', async () => {
    const db = createInMemoryDb(MIGRATIONS)
    const defWithWg = {
      $schema_version: 4,
      inputs: [],
      nodes: [{ id: 'cw', kind: 'call-workgroup', workgroupName: 'ghost-wg', goalTemplate: 'g' }],
      edges: [],
    } as unknown as WorkflowDefinition
    await expect(
      freezeCallClosure(db, { id: 'W0', definition: defWithWg }, closureActor),
    ).rejects.toMatchObject({
      code: 'workflow-call-ref-missing',
    })
    const { createAgent } = await import('../src/services/agent')
    const { createWorkgroup } = await import('../src/services/workgroups')
    const { buildActor } = await import('../src/auth/actor')
    const actor = buildActor({
      user: { id: 'u-z', username: 'z', displayName: 'z', role: 'admin', status: 'active' },
      source: 'daemon',
    })
    const agent = await createAgent(db, {
      name: 'wg-a',
      description: '',
      outputs: [],
      syncOutputsOnIterate: true,
      permission: {},
      skills: [],
      dependsOn: [],
      mcp: [],
      plugins: [],
      frontmatterExtra: {},
      bodyMd: 'x',
    })
    const group = await createWorkgroup(
      db,
      {
        name: 'ghost-wg',
        description: '',
        instructions: '',
        mode: 'free_collab',
        autonomous: true,
        switches: { shareOutputs: true, directMessages: true, blackboard: true },
        maxRounds: 4,
        completionGate: false,
        members: [{ memberType: 'agent', agentId: agent.id, displayName: 'a', roleDesc: 'r' }],
      } as Parameters<typeof createWorkgroup>[1],
      { ownerUserId: actor.user.id, actor },
    )
    const json = await freezeCallClosure(db, { id: 'W0', definition: defWithWg }, closureActor)
    expect(json).not.toBeNull()
    // ── RFC-271 T6e 显式改判（2026-08-08）──────────────────────────────
    // 冻结闭包由 `Record<name, ref>` 改为按**边**键控 `sourceWorkflowId#nodeId`
    // （决策 28）：同名两个 call 节点此前落到同一条，用户在下拉里选的那个被
    // 静默丢弃。断言的**内容不变**（同一个组、完整 roster），只是取法从名字
    // 换成边键；节点 id 是 'cw'、source 是 'W0'。
    const parsed = JSON.parse(json!) as {
      closureVersion?: number
      workgroups: Record<string, { id: string; group: { members: unknown[] } }>
    }
    expect(parsed.closureVersion).toBe(2)
    expect(parsed.workgroups['W0#cw']?.id).toBe(group.id)
    expect(parsed.workgroups['W0#cw']?.group.members.length).toBe(1)
    // 旧的按名字取法必须**取不到**——否则说明形状没真的改。
    expect(parsed.workgroups['ghost-wg']).toBeUndefined()
  })
})
