// RFC-349 T4/T8 — locks the independent PostgreSQL baseline: 178 active
// tables, six archive-only omissions, native provider types/defaults, and no
// replay of SQLite migration SQL.

import { describe, expect, test } from 'bun:test'
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import {
  buildPostgresqlSchemaPlan,
  renderPostgresqlBaselineSql,
} from '@/platform/persistence/postgresqlSchema'
import {
  buildLogicalSchemaContract,
  canonicalSchemaJson,
  RFC349_ARCHIVE_THEN_OMIT_TABLES,
} from '@/platform/persistence/schemaContract'

describe('RFC-349 PostgreSQL schema projection', () => {
  test('projects the exact 178-table active parity set', () => {
    const contract = buildLogicalSchemaContract()
    const plan = buildPostgresqlSchemaPlan(contract)
    const tables = plan.statements.filter((statement) => statement.kind === 'table')
    expect(tables).toHaveLength(178)
    expect(new Set(tables.map((statement) => statement.logicalId)).size).toBe(178)
    expect(plan.activeTableCount).toBe(contract.activeTableCount)
    expect(plan.archiveOnlyTableCount).toBe(6)
  })

  test('omits exactly the six approved legacy tables', () => {
    const sql = renderPostgresqlBaselineSql(buildPostgresqlSchemaPlan())
    for (const table of RFC349_ARCHIVE_THEN_OMIT_TABLES) {
      expect(sql).not.toContain(`CREATE TABLE "agent_workflow"."${table}"`)
    }
    expect(sql).toContain('CREATE TABLE "agent_workflow"."tasks"')
    expect(sql).toContain('CREATE TABLE "agent_workflow"."code_work_items"')
  })

  test('uses PostgreSQL-native boolean, bigint, identity and defaults', () => {
    const sql = renderPostgresqlBaselineSql(buildPostgresqlSchemaPlan())
    expect(sql).toContain('"sync_outputs_on_iterate" BOOLEAN NOT NULL DEFAULT TRUE')
    expect(sql).toContain('"created_at" BIGINT NOT NULL DEFAULT (extract(epoch')
    expect(sql).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL')
    expect(sql).toContain('DEFAULT md5(random()::text || clock_timestamp()::text)')
  })

  test('maps SQLite-only check syntax and bounds physical identifiers', () => {
    const plan = buildPostgresqlSchemaPlan()
    const sql = renderPostgresqlBaselineSql(plan)
    expect(sql).not.toMatch(/\bGLOB\b/i)
    expect(sql).not.toMatch(/\brandomblob\s*\(/i)
    expect(sql).toContain("!~ '[^0-9a-f]'")
    expect(sql).toContain('"from_scope_id" IS DISTINCT FROM "to_scope_id"')
    expect(sql).toContain('"reset_pending" IN (FALSE, TRUE)')
    for (const statement of plan.statements.filter(
      (candidate) => candidate.kind === 'constraint' || candidate.kind === 'index',
    )) {
      const identifier = /(?:CONSTRAINT|INDEX) "([^"]+)"/.exec(statement.sql)?.[1]
      expect(identifier).toBeDefined()
      expect(Buffer.byteLength(identifier!, 'utf8')).toBeLessThanOrEqual(63)
    }
  })

  test('plan digest is deterministic and covers every DDL statement', () => {
    const first = buildPostgresqlSchemaPlan()
    const second = buildPostgresqlSchemaPlan()
    expect(first).toEqual(second)
    expect(first.digest).toMatch(/^sha256:[a-f0-9]{64}$/)
    const { digest: _digest, ...payload } = first
    expect(first.digest).toBe(
      `sha256:${createHash('sha256').update(canonicalSchemaJson(payload)).digest('hex')}`,
    )
    const mutated = {
      ...payload,
      statements: first.statements.map((statement, index) =>
        index === 0 ? { ...statement, sql: `${statement.sql} ` } : statement,
      ),
    }
    expect(first.digest).not.toBe(
      `sha256:${createHash('sha256').update(canonicalSchemaJson(mutated)).digest('hex')}`,
    )
  })

  test('committed immutable baseline and journal match the current projector', () => {
    const plan = buildPostgresqlSchemaPlan()
    const migrationRoot = resolve(import.meta.dir, '..', 'db', 'postgresql-migrations')
    expect(readFileSync(resolve(migrationRoot, '0000_rfc349_baseline.sql'), 'utf8')).toBe(
      renderPostgresqlBaselineSql(plan),
    )
    const journal = JSON.parse(
      readFileSync(resolve(migrationRoot, 'meta', '_journal.json'), 'utf8'),
    ) as {
      baselineId: string
      contractDigest: string
      planDigest: string
      statements: readonly { digest: string }[]
    }
    expect(journal.baselineId).toBe(plan.baselineId)
    expect(journal.contractDigest).toBe(plan.contractDigest)
    expect(journal.planDigest).toBe(plan.digest)
    expect(journal.statements).toHaveLength(plan.statements.length)
    expect(journal.statements.map((statement) => statement.digest)).toEqual(
      plan.statements.map(
        (statement) => `sha256:${createHash('sha256').update(statement.sql).digest('hex')}`,
      ),
    )
  })
})
