// RFC-349 —— 逐表对着**真 PostgreSQL** 执行一次真 INSERT 的写矩阵。
// 普通 backend 跑批跳过本文件；postgresql-evidence.yml 提供一台一次性外置服务器。
//
// 为什么这条测试存在（2026-09-03）：RFC-349 的双 provider 行为 oracle 用的是「只记录
// SQL 文本」的假 runtime，它能证明适配器走了哪条事务/fence 路径，**证明不了那条 SQL 在
// 真 PostgreSQL 上能不能跑**。于是一个致命缺陷一路穿过全部门禁：Drizzle 的 SQLite
// dialect 把「values 里没给、列也没有 default」的列渲染成字面量 `null`，SQLite 把
// `INSERT INTO t(id) VALUES (NULL)` 里的 INTEGER PRIMARY KEY 读成「分配下一个 rowid」，
// 而 PostgreSQL 的 `GENERATED BY DEFAULT AS IDENTITY NOT NULL` 直接拒绝——
// `node_run_events` 因此在 PostgreSQL 上一条都写不进去，而它是 agent 每输出一行就要写的
// 那张表（详见 rfc349-identity-column-insert-default.test.ts）。
//
// 这条矩阵把那一类缺陷变成**结构性**可发现：对 contract 里每一张有 PostgreSQL 投影的表，
// 用真适配器渲染一次真 INSERT 并执行。判据按 SQLSTATE 分类，而不是错误文本：
//   预期内（与列渲染无关）：23503 外键、23514 check、22003 越界、22P02 文本转换
//   ——都是「合成值不满足业务约束」，不是投影缺陷；
//   其余一律算缺陷，尤其是 23502 not-null（identity 列渲染成 null 就长这样）、
//   42703 未知列、42804 类型不匹配、42601 语法、42883 未知函数（SQLite 函数没打 shim）。
//
// 每次插入都在事务里做完就回滚，数据库保持干净。

import { describe, expect, test } from 'bun:test'
import { getTableName, is } from 'drizzle-orm'
import { SQLiteTable } from 'drizzle-orm/sqlite-core'

import * as schema from '@/db/schema'
import { selectDatabaseSchemaProvider } from '@/db/providerSchema'
import { createPostgresqlDatabaseClient } from '@/platform/persistence/postgresqlDatabaseClient'
import { migratePostgresqlSchema } from '@/platform/persistence/postgresqlMigrator'
import { createPostgresqlDatabaseRuntime } from '@/platform/persistence/postgresqlRuntime'
import { buildLogicalSchemaContract } from '@/platform/persistence/schemaContract'

const URL_ENV = 'RFC349_WRITE_MATRIX_DATABASE_URL'
const realTest = process.env[URL_ENV] === undefined ? test.skip : test
const GENERATION_ID = 'dbg_write_matrix_01'
const OPERATION_ID = 'dbm_write_matrix_01'

/** 合成值不满足业务约束 —— 与「这条 SQL 能不能在 PostgreSQL 上跑」无关。 */
const EXPECTED_SQLSTATES = new Set(['23503', '23514', '22003', '22P02'])

function sqlStates(error: unknown): readonly string[] {
  const codes: string[] = []
  const seen = new Set<object>()
  let current: unknown = error
  for (let depth = 0; depth < 6 && typeof current === 'object' && current !== null; depth += 1) {
    if (seen.has(current)) break
    seen.add(current)
    for (const key of ['errno', 'code', 'sqlState'] as const) {
      const value = (current as Record<string, unknown>)[key]
      if (typeof value === 'string' || typeof value === 'number') codes.push(String(value))
    }
    current = (current as { cause?: unknown }).cause
  }
  return codes
}

function message(error: unknown): string {
  const own = error as Error & { cause?: Error }
  return own.cause?.message ?? own.message ?? String(error)
}

/** Sqlite-projection column metadata Drizzle exposes on every table facade. */
interface FacadeColumn {
  readonly name?: string
  readonly notNull?: boolean
  readonly hasDefault?: boolean
  readonly primary?: boolean
  readonly dataType?: string
  readonly enumValues?: readonly string[]
  readonly autoIncrement?: boolean
}

/**
 * 每张表填一份**最小可插入**的值：非空且没有 default 的列必须给；identity 列故意**不给**
 * ——那正是要验的那条路径。`implicit-primary`（SQLite 的 rowid 别名、但业务自己算的
 * 修订号，如 `employee_execution_policy_revisions.revision`）也必须给：它在 PostgreSQL
 * 上没有 identity，省略就是 not-null，而生产写手本来就显式赋值。
 */
function minimalValues(facade: object): Record<string, unknown> {
  const values: Record<string, unknown> = {}
  const restore = selectDatabaseSchemaProvider('sqlite')
  try {
    for (const [property, candidate] of Object.entries(facade)) {
      const column = candidate as FacadeColumn
      if (typeof column?.name !== 'string' || column.notNull === undefined) continue
      const identity = column.autoIncrement === true
      const needsValue =
        (column.notNull && !column.hasDefault) || (column.primary && !identity && column.hasDefault)
      if (!needsValue) continue
      if (column.enumValues?.length) values[property] = column.enumValues[0]
      else if (column.dataType === 'boolean') values[property] = true
      else if (column.dataType === 'number') values[property] = 1
      else if (column.dataType === 'buffer') values[property] = new Uint8Array([1])
      else values[property] = `probe-${column.name}`
    }
  } finally {
    restore()
  }
  return values
}

function sqliteTableFacades(): Map<string, object> {
  const facades = new Map<string, object>()
  const restore = selectDatabaseSchemaProvider('sqlite')
  try {
    for (const value of Object.values(schema)) {
      if (typeof value !== 'object' || value === null) continue
      if (is(value, SQLiteTable)) facades.set(getTableName(value), value)
    }
  } finally {
    restore()
  }
  return facades
}

describe('RFC-349 every logical table accepts a real INSERT on real PostgreSQL', () => {
  realTest(
    'no table is rejected for a reason that is about how its statement was rendered',
    async () => {
      const runtime = createPostgresqlDatabaseRuntime({
        config: {
          provider: 'postgresql',
          urlEnv: URL_ENV,
          poolMax: 4,
          connectTimeoutMs: 10_000,
          statementTimeoutMs: 60_000,
          idleTimeoutMs: 30_000,
        },
        generationId: GENERATION_ID,
      })
      try {
        const pool = runtime.providerPool()
        await pool.unsafe('DROP SCHEMA IF EXISTS agent_workflow CASCADE')
        await pool.unsafe('DROP SCHEMA IF EXISTS agent_workflow_meta CASCADE')
        await migratePostgresqlSchema({ runtime })
        // The business client fences every write against the active generation.
        await pool.unsafe(
          'INSERT INTO "agent_workflow_meta"."logical_copy_operations" ' +
            '(operation_id, source_generation_id, contract_digest, plan_digest, stage, created_at, updated_at) ' +
            `VALUES ('${OPERATION_ID}', 'dbg_write_matrix_source', 'digest', 'plan', 'prepared', 1, 1)`,
        )
        await pool.unsafe(
          'INSERT INTO "agent_workflow_meta"."database_generations" ' +
            '(generation_id, operation_id, source_generation_id, contract_digest, state, activated_at, first_live_write_at) ' +
            `VALUES ('${GENERATION_ID}', '${OPERATION_ID}', 'dbg_write_matrix_source', 'digest', 'active', 1, 1)`,
        )

        selectDatabaseSchemaProvider('postgresql')
        const db = createPostgresqlDatabaseClient(runtime)
        const facades = sqliteTableFacades()
        const contract = buildLogicalSchemaContract()
        const defects: string[] = []
        let inserted = 0
        let examined = 0

        for (const table of contract.tables) {
          if (table.providerTables.postgresql === undefined) continue
          examined += 1
          const facade = facades.get(table.sourceTable)
          if (facade === undefined) {
            defects.push(`${table.sourceTable}: contract 里的表在 schema 导出中找不到`)
            continue
          }
          try {
            await db.transaction(async (tx) => {
              await tx
                .insert(facade as Parameters<typeof db.insert>[0])
                .values(minimalValues(facade) as never)
                .run()
              // Roll the row back: the matrix proves the statement runs, not that
              // a synthetic row belongs in the database.
              throw new Error('__rollback__')
            })
          } catch (error) {
            if (message(error).includes('__rollback__')) {
              inserted += 1
              continue
            }
            const codes = sqlStates(error)
            if (codes.some((code) => EXPECTED_SQLSTATES.has(code))) continue
            defects.push(
              `${table.sourceTable}: [${codes.join(',')}] ${message(error).slice(0, 200)}`,
            )
          }
        }

        expect(
          defects,
          '有表的 INSERT 在真 PostgreSQL 上被拒，且理由与「语句怎么渲染的」有关 —— ' +
            'identity 列渲染成 null（23502）、SQLite 函数没打 shim（42883）都会落在这里',
        ).toEqual([])
        // 大多数表带外键，合成行满足不了引用完整性 —— 矩阵的信号是 `defects`，不是这个
        // 计数。它只用来证明矩阵**确实跑过**，没有整段被跳过。
        expect(examined, '矩阵没覆盖到 contract 的全部有效表').toBe(
          contract.tables.filter((table) => table.providerTables.postgresql !== undefined).length,
        )
        expect(inserted, '一张表都没插进去 ⇒ 矩阵本身没跑起来').toBeGreaterThan(50)
      } finally {
        await runtime.close?.()
      }
    },
    600_000,
  )
})
