// RFC-349 回归防护 —— identity 列被省略时，PostgreSQL 投影必须渲染 `default` 而不是 `null`。
//
// 为什么这条测试存在（2026-09-03，对着真 PostgreSQL 跑真适配器时实测）：
// Drizzle 的 **SQLite dialect** 在 `buildInsertQuery` 里对「值里没给、列也没有
// default」的列一律填字面量 `null`（`node_modules/drizzle-orm/sqlite-core/dialect.cjs`
// 的 `defaultValue = sql\`null\``）。SQLite 把 `INSERT INTO t(id) VALUES (NULL)` 里的
// `INTEGER PRIMARY KEY` 读成「分配下一个 rowid」，所以在 SQLite 上一直是对的；而
// RFC-349 把这类列投影成 PostgreSQL 的 `GENERATED BY DEFAULT AS IDENTITY NOT NULL`，
// 显式的 NULL 直接撞 NOT NULL：
//
//   null value in column "id" of relation "node_run_events" violates not-null constraint
//
// 命中的是**产品最热的写路径**：`appendEvents` 每写一行 agent stdout/stderr 就插一次
// `node_run_events`。选 PostgreSQL 时它 100% 失败，等于任务跑起来一条输出都存不下。
// 另外两处同形：`memory_distill_events`（蒸馏会话捕获）、`mcp_runtime_test_events`。
// `intent_turn_events` 的生产写手用的是显式列名的裸 SQL、本来就没带 id，这里一并纳入
// 是为了让**未来**任何走 Drizzle 的写手也自动受保护。
// 双 provider oracle 测试用的是「只记录 SQL 文本」的假 runtime，永远看不到这类
// 「SQL 合法但语义不同」的偏差，所以这条断言直接钉在渲染出来的 SQL 上。
//
// 判据（对 contract 里**每一张**带 identity 列的表都成立，新表自动纳入）：
//   ① PostgreSQL 投影下省略 identity 列 ⇒ 该位置渲染成 `default`；
//   ② SQLite 投影下仍渲染成 `null`（rowid 自动分配的既有语义不能被动到）；
//   ③ 最热路径 node_run_events 的多行 insert 单独再钉一次。

import { describe, expect, test } from 'bun:test'
import { drizzle } from 'drizzle-orm/sqlite-proxy'
import { getTableName, is } from 'drizzle-orm'
import { SQLiteTable } from 'drizzle-orm/sqlite-core'

import * as schema from '@/db/schema'
import { selectDatabaseSchemaProvider } from '@/db/providerSchema'
import { buildLogicalSchemaContract } from '@/platform/persistence/schemaContract'
import type { DatabaseProvider } from '@/platform/persistence/schemaContract'

const db = drizzle(async () => ({ rows: [] }), { schema })

/** Column list + first VALUES tuple of a rendered single-table insert. */
function renderedInsert(table: object): { columns: string[]; values: string[] } {
  const { sql } = db
    .insert(table as Parameters<typeof db.insert>[0])
    .values({})
    .toSQL()
  const match = /^insert into\s+\S+\s+\(([^)]*)\)\s+values\s+\(([^)]*)\)/iu.exec(sql)
  expect(match, `无法解析渲染出的 insert：${sql}`).not.toBeNull()
  return {
    columns: match![1]!.split(',').map((piece) => piece.trim().replaceAll('"', '')),
    values: match![2]!.split(',').map((piece) => piece.trim()),
  }
}

function withProvider<T>(provider: DatabaseProvider, body: () => T): T {
  const restore = selectDatabaseSchemaProvider(provider)
  try {
    return body()
  } finally {
    restore()
  }
}

/** Every logical table that declares an identity column, paired with its facade. */
function identityTables(): { table: string; column: string; facade: object }[] {
  const facades = new Map<string, object>()
  for (const value of Object.values(schema)) {
    if (typeof value !== 'object' || value === null) continue
    if (!is(value, SQLiteTable)) continue
    facades.set(getTableName(value), value)
  }
  return buildLogicalSchemaContract()
    .tables.flatMap((table) =>
      table.columns
        .filter((column) => column.identity)
        .map((column) => ({ table: table.sourceTable, column: column.name })),
    )
    .map((entry) => {
      const facade = facades.get(entry.table)
      expect(facade, `contract 里的 ${entry.table} 在 schema 导出中找不到`).toBeDefined()
      return { ...entry, facade: facade! }
    })
}

describe('RFC-349 identity columns render DEFAULT on PostgreSQL', () => {
  test('the contract still has identity columns to protect', () => {
    const tables = identityTables()
    expect(
      tables.map((entry) => entry.table).sort(),
      'identity 列的清单变了 ⇒ 先确认新表/删表是有意的，再更新这条断言',
    ).toEqual([
      'intent_turn_events',
      'mcp_runtime_test_events',
      'memory_distill_events',
      'node_run_events',
    ])
  })

  test('an omitted identity column renders `default`, never `null`', () => {
    for (const entry of identityTables()) {
      const rendered = withProvider('postgresql', () => renderedInsert(entry.facade))
      const at = rendered.columns.indexOf(entry.column)
      expect(at, `${entry.table} 的渲染列表里没有 ${entry.column}`).toBeGreaterThanOrEqual(0)
      expect(
        rendered.values[at],
        `${entry.table}.${entry.column} 渲染成了 ${rendered.values[at]} ⇒ PostgreSQL 会以 ` +
          'null value in column ... violates not-null constraint 拒绝每一次插入',
      ).toBe('default')
    }
  })

  test('SQLite keeps rendering `null` so the rowid alias still auto-assigns', () => {
    for (const entry of identityTables()) {
      const rendered = withProvider('sqlite', () => renderedInsert(entry.facade))
      const at = rendered.columns.indexOf(entry.column)
      expect(rendered.values[at], `${entry.table}.${entry.column} 的 SQLite 语义被改动了`).toBe(
        'null',
      )
    }
  })

  test('the hot path — a multi-row node_run_events insert — carries no null id', () => {
    const restore = selectDatabaseSchemaProvider('postgresql')
    try {
      const { sql } = db
        .insert(schema.nodeRunEvents)
        .values([
          { nodeRunId: 'nr1', ts: 1, kind: 'text', payload: 'a' },
          { nodeRunId: 'nr1', ts: 2, kind: 'stderr', payload: 'b' },
        ])
        .toSQL()
      expect(sql).toContain('values (default,')
      expect(
        sql,
        'appendEvents 又渲染出了 null id ⇒ PostgreSQL 上一条事件都写不进去',
      ).not.toContain('(null,')
    } finally {
      restore()
    }
  })
})
