// RFC-329 —— 没有 MCP 工具的路由，逐条登记。判据在 rfc329-mcp-surface-guard.test.ts。
//
// 为什么每条叶子都是一个数组元素
// ------------------------------
// 高水位机制（rfc317-ledger-highwater.test.ts）按 AST 数**顶层数组元素**，不会递归数嵌套
// 的子数组。所以如果按域分组、把叶子塞进每组的子数组里，往已有组加一条豁免时组数纹丝
// 不动、基线不响——那和用前缀批量豁免是同一个漏洞，只是换了层皮。
//
// 于是这里反过来：**叶子是唯一事实源，每条一个元素**（加一条 ⇒ 基线必须同批改大，而改大
// 需要显式写 allowGrowth 并点名 RFC），归属写在叶子自己身上；理由按组存一份，不重复。
//
// 前缀在这里一条都没有。新路由不在任何一条叶子里 → 落进 uncovered → 红 → 逼出一次有署名
// 的决定，而不是被某条宽 prefix 无声吸收。

export type ExemptCategory =
  /** tokenAccess:'never' —— PAT 不得开这扇门（RFC-247 D5/D6）。 */
  | 'never'
  /** 权限点在 SYSTEM_DOMAIN_POINTS —— PAT 结构上够不着，做工具没有意义，不是待办。 */
  | 'system-point'
  /** 运维 / 平台面：权限上够得着，但不该交给模型。 */
  | 'system'
  /** 三类 / 四类：该做，但不在本 RFC 范围，各自等后续 RFC。 */
  | 'not-in-scope'
  /** 够得着也不给，各带一句理由。 */
  | 'deliberate'

export interface ExemptLeaf {
  /** 精确 `METHOD /path` 模板，与 allRouteMeta() 规范化后逐字相等。 */
  readonly leaf: string
  /** 归属分组；理由在 EXEMPT_REASONS 里按这个键存一份。 */
  readonly group: string
  readonly category: ExemptCategory
}

/** 每条叶子一个元素——见文件头。只许缩。 */
export const MCP_SURFACE_EXEMPTION_LEAVES: ReadonlyArray<ExemptLeaf> = [
  { leaf: "GET /.well-known/mcp", group: "(infrastructure)", category: "deliberate" },
  { leaf: "GET /health", group: "(infrastructure)", category: "deliberate" },
  { leaf: "GET /api/clarify/pending-count", group: "/api/clarify", category: "deliberate" },
  { leaf: "GET /api/docs/api", group: "/api/docs", category: "deliberate" },
  { leaf: "GET /api/fusions/pending-count", group: "/api/fusions", category: "deliberate" },
  { leaf: "POST /api/fusions", group: "/api/fusions", category: "deliberate" },
  { leaf: "GET /api/overview", group: "/api/overview", category: "deliberate" },
  { leaf: "GET /api/reviews/pending-count", group: "/api/reviews", category: "deliberate" },
  { leaf: "GET /api/whoami", group: "/api/whoami", category: "deliberate" },
  { leaf: "GET /api/workgroup-tasks/pending-count", group: "/api/workgroup-tasks", category: "deliberate" },
  { leaf: "DELETE /api/account/code-host-push-credentials/:id", group: "/api/account", category: "never" },
  { leaf: "GET /api/account/code-host-push-credentials", group: "/api/account", category: "never" },
  { leaf: "POST /api/account/code-host-push-credentials/:id/test", group: "/api/account", category: "never" },
  { leaf: "PUT /api/account/code-host-push-credentials/:id", group: "/api/account", category: "never" },
  { leaf: "PUT /api/agents/:id/acl", group: "/api/agents", category: "never" },
  { leaf: "DELETE /api/auth/identities/:id", group: "/api/auth", category: "never" },
  { leaf: "DELETE /api/auth/pats/:id", group: "/api/auth", category: "never" },
  { leaf: "GET /api/auth/bootstrap/status", group: "/api/auth", category: "never" },
  { leaf: "GET /api/auth/identities", group: "/api/auth", category: "never" },
  { leaf: "GET /api/auth/me", group: "/api/auth", category: "never" },
  { leaf: "GET /api/auth/oidc/:id/callback", group: "/api/auth", category: "never" },
  { leaf: "GET /api/auth/oidc/providers", group: "/api/auth", category: "never" },
  { leaf: "GET /api/auth/pats", group: "/api/auth", category: "never" },
  { leaf: "GET /api/auth/pats/audit", group: "/api/auth", category: "never" },
  { leaf: "GET /api/auth/sessions", group: "/api/auth", category: "never" },
  { leaf: "PATCH /api/auth/me/profile", group: "/api/auth", category: "never" },
  { leaf: "POST /api/auth/bootstrap/admin", group: "/api/auth", category: "never" },
  { leaf: "POST /api/auth/change-password", group: "/api/auth", category: "never" },
  { leaf: "POST /api/auth/login", group: "/api/auth", category: "never" },
  { leaf: "POST /api/auth/logout", group: "/api/auth", category: "never" },
  { leaf: "POST /api/auth/oidc/:id/login/start", group: "/api/auth", category: "never" },
  { leaf: "POST /api/auth/pats", group: "/api/auth", category: "never" },
  { leaf: "POST /api/auth/sessions/:id/revoke", group: "/api/auth", category: "never" },
  { leaf: "PUT /api/capability-templates/:id/acl", group: "/api/capability-templates", category: "never" },
  { leaf: "PUT /api/code/action-templates/:id/acl", group: "/api/code", category: "never" },
  { leaf: "PUT /api/code/automation-policies/:id/acl", group: "/api/code", category: "never" },
  { leaf: "PUT /api/code/digital-employees/:id/acl", group: "/api/code", category: "never" },
  { leaf: "PUT /api/code/verification-profiles/:id/acl", group: "/api/code", category: "never" },
  { leaf: "DELETE /api/code-hosts/:id", group: "/api/code-hosts", category: "never" },
  { leaf: "GET /api/code-hosts", group: "/api/code-hosts", category: "never" },
  { leaf: "POST /api/code-hosts/:id/test", group: "/api/code-hosts", category: "never" },
  { leaf: "PUT /api/code-hosts/:id", group: "/api/code-hosts", category: "never" },
  { leaf: "PUT /api/digital-employees/:id/acl", group: "/api/digital-employees", category: "never" },
  { leaf: "POST /api/employee-cases/worker/run-one", group: "/api/employee-cases", category: "never" },
  { leaf: "DELETE /api/event-center/response-rules/:id", group: "/api/event-center", category: "never" },
  { leaf: "GET /api/event-center/response-rules", group: "/api/event-center", category: "never" },
  { leaf: "GET /api/event-center/sources/:id", group: "/api/event-center", category: "never" },
  { leaf: "POST /api/event-center/observers/run-due", group: "/api/event-center", category: "never" },
  { leaf: "POST /api/event-center/response-rules", group: "/api/event-center", category: "never" },
  { leaf: "POST /api/event-center/sources", group: "/api/event-center", category: "never" },
  { leaf: "POST /api/event-center/sources/:id/publish", group: "/api/event-center", category: "never" },
  { leaf: "POST /api/event-center/sources/:id/retire", group: "/api/event-center", category: "never" },
  { leaf: "POST /api/event-center/sources/:id/validate", group: "/api/event-center", category: "never" },
  { leaf: "PUT /api/event-center/response-rules/:id", group: "/api/event-center", category: "never" },
  { leaf: "PUT /api/event-center/sources/:id", group: "/api/event-center", category: "never" },
  { leaf: "PUT /api/integrations/development-adapters/:id/acl", group: "/api/integrations", category: "never" },
  { leaf: "PUT /api/mcps/:id/acl", group: "/api/mcps", category: "never" },
  { leaf: "PUT /api/plugins/:id/acl", group: "/api/plugins", category: "never" },
  { leaf: "PUT /api/scheduled-tasks/:id/acl", group: "/api/scheduled-tasks", category: "never" },
  { leaf: "PUT /api/skills/:id/acl", group: "/api/skills", category: "never" },
  { leaf: "PUT /api/tasks/:id/members", group: "/api/tasks", category: "never" },
  { leaf: "GET /api/tokens", group: "/api/tokens", category: "never" },
  { leaf: "GET /api/tokens/audit", group: "/api/tokens", category: "never" },
  { leaf: "POST /api/webhook-deliveries/:id/replay", group: "/api/webhook-deliveries", category: "never" },
  { leaf: "DELETE /api/webhook-endpoints/:id", group: "/api/webhook-endpoints", category: "never" },
  { leaf: "POST /api/webhook-endpoints", group: "/api/webhook-endpoints", category: "never" },
  { leaf: "POST /api/webhook-endpoints/:id/rotate-secret", group: "/api/webhook-endpoints", category: "never" },
  { leaf: "POST /api/webhook-endpoints/:id/rotate-url-token", group: "/api/webhook-endpoints", category: "never" },
  { leaf: "PUT /api/webhook-endpoints/:id", group: "/api/webhook-endpoints", category: "never" },
  { leaf: "PUT /api/workflows/:id/acl", group: "/api/workflows", category: "never" },
  { leaf: "PUT /api/workgroup-tasks/:id/config", group: "/api/workgroup-tasks", category: "never" },
  { leaf: "PUT /api/workgroups/:id/acl", group: "/api/workgroups", category: "never" },
  { leaf: "GET /api/agents/:id/acl", group: "/api/agents", category: "not-in-scope" },
  { leaf: "GET /api/agents/:id/closure", group: "/api/agents", category: "not-in-scope" },
  { leaf: "GET /api/agents/:id/export-package", group: "/api/agents", category: "not-in-scope" },
  { leaf: "GET /api/agents/:id/resource-status", group: "/api/agents", category: "not-in-scope" },
  { leaf: "GET /api/agents/builtins/digital-employee-templates", group: "/api/agents", category: "not-in-scope" },
  { leaf: "GET /api/agents/builtins/skill-merger", group: "/api/agents", category: "not-in-scope" },
  { leaf: "POST /api/agents/:id/rename", group: "/api/agents", category: "not-in-scope" },
  { leaf: "POST /api/agents/:id/tasks", group: "/api/agents", category: "not-in-scope" },
  { leaf: "POST /api/agents/closure-preview", group: "/api/agents", category: "not-in-scope" },
  { leaf: "POST /api/agents/import-resolve", group: "/api/agents", category: "not-in-scope" },
  { leaf: "GET /api/cached-repos/imports/:id", group: "/api/cached-repos", category: "not-in-scope" },
  { leaf: "POST /api/cached-repos/:id/refresh", group: "/api/cached-repos", category: "not-in-scope" },
  { leaf: "POST /api/cached-repos/imports/:id/rows/:id/retry", group: "/api/cached-repos", category: "not-in-scope" },
  { leaf: "GET /api/capability-templates/:id/acl", group: "/api/capability-templates", category: "not-in-scope" },
  { leaf: "GET /api/capability-templates/:id/export-package", group: "/api/capability-templates", category: "not-in-scope" },
  { leaf: "GET /api/capability-templates/:id/upstream", group: "/api/capability-templates", category: "not-in-scope" },
  { leaf: "POST /api/capability-templates/:id/copy", group: "/api/capability-templates", category: "not-in-scope" },
  { leaf: "POST /api/capability-templates/:id/upstream/merge", group: "/api/capability-templates", category: "not-in-scope" },
  { leaf: "DELETE /api/code/mission-input-uploads/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "DELETE /api/code/repository-assignments/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/action-templates", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/action-templates/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/action-templates/:id/acl", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/automation-policies", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/automation-policies/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/automation-policies/:id/acl", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/capabilities", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/capabilities/:id/graph", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/cutover", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/deliveries", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/digital-employees", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/digital-employees/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/digital-employees/:id/acl", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/digital-employees/:id/playbook", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/matrix/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/metrics", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/missions", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/missions/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/missions/:id/decision-trace", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/missions/:id/pipeline-evidence/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/missions/:id/requirement-files/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/missions/:id/requirement-manifest", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/missions/outcome-summaries", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/repository-assignments", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/rounds/:id/attempts", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/setup-journey", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/verification-profiles", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/verification-profiles/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/verification-profiles/:id/acl", group: "/api/code", category: "not-in-scope" },
  { leaf: "GET /api/code/work-items", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/action-templates", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/action-templates/:id/archive", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/action-templates/:id/publish", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/automation-policies", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/automation-policies/:id/archive", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/automation-policies/:id/publish", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/automation-policies/preview-decision", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/cutover/adopt-mr", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/cutover/flip", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/cutover/freeze", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/cutover/materialize", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/cutover/rollback", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/digital-employees", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/digital-employees/:id/archive", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/digital-employees/:id/playbook/validate", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/digital-employees/:id/publish", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/digital-employees/preview-selection", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/mission-input-uploads", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/missions", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/missions/:id/answers", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/missions/:id/attach-mr", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/missions/:id/cancel", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/missions/:id/confirm-no-change", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/missions/:id/handoff", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/missions/:id/requirement-source", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/missions/:id/resume", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/missions/:id/retry", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/missions/:id/source-refresh", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/missions/:id/source-refresh/preview", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/missions/direct-input/preview", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/missions/preview", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/verification-profiles", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/verification-profiles/:id/archive", group: "/api/code", category: "not-in-scope" },
  { leaf: "POST /api/code/verification-profiles/:id/publish", group: "/api/code", category: "not-in-scope" },
  { leaf: "PUT /api/code/action-templates/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "PUT /api/code/automation-policies/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "PUT /api/code/digital-employees/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "PUT /api/code/digital-employees/:id/playbook", group: "/api/code", category: "not-in-scope" },
  { leaf: "PUT /api/code/repository-assignments", group: "/api/code", category: "not-in-scope" },
  { leaf: "PUT /api/code/verification-profiles/:id", group: "/api/code", category: "not-in-scope" },
  { leaf: "DELETE /api/digital-employee-input-uploads/:id", group: "/api/digital-employee-input-uploads", category: "not-in-scope" },
  { leaf: "POST /api/digital-employee-input-uploads", group: "/api/digital-employee-input-uploads", category: "not-in-scope" },
  { leaf: "POST /api/digital-employee-job-templates/:id/publish", group: "/api/digital-employee-job-templates", category: "not-in-scope" },
  { leaf: "PUT /api/digital-employee-job-templates/:id", group: "/api/digital-employee-job-templates", category: "not-in-scope" },
  { leaf: "GET /api/digital-employee-types", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "GET /api/digital-employee-types/:id", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "GET /api/digital-employee-types/:id/authoring-manifest", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "GET /api/digital-employee-types/:id/employees", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "GET /api/digital-employee-types/:id/job-templates", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "GET /api/digital-employee-types/:id/work-items/:id/tools", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "GET /api/digital-employee-types/:id/work-items/:id/tools/:id", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "POST /api/digital-employee-types/:id/employees", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "POST /api/digital-employee-types/:id/job-templates", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "POST /api/digital-employee-types/:id/work-items/:id/tools", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "POST /api/digital-employee-types/:id/work-items/:id/tools/:id/publish", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "POST /api/digital-employee-types/:id/work-items/:id/tools/:id/retire", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "POST /api/digital-employee-types/:id/work-items/:id/tools/:id/validate", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "PUT /api/digital-employee-types/:id/work-items/:id/tools/:id", group: "/api/digital-employee-types", category: "not-in-scope" },
  { leaf: "GET /api/digital-employees", group: "/api/digital-employees", category: "not-in-scope" },
  { leaf: "GET /api/digital-employees/:id", group: "/api/digital-employees", category: "not-in-scope" },
  { leaf: "GET /api/digital-employees/:id/acl", group: "/api/digital-employees", category: "not-in-scope" },
  { leaf: "GET /api/digital-employees/launchable", group: "/api/digital-employees", category: "not-in-scope" },
  { leaf: "GET /api/digital-employees/migration-status", group: "/api/digital-employees", category: "not-in-scope" },
  { leaf: "GET /api/digital-employees/outcome-summaries", group: "/api/digital-employees", category: "not-in-scope" },
  { leaf: "POST /api/digital-employees/:id/cases", group: "/api/digital-employees", category: "not-in-scope" },
  { leaf: "PUT /api/digital-employees/:id", group: "/api/digital-employees", category: "not-in-scope" },
  { leaf: "GET /api/employee-cases/:id", group: "/api/employee-cases", category: "not-in-scope" },
  { leaf: "POST /api/employee-cases/:id/policy-upgrade-preview", group: "/api/employee-cases", category: "not-in-scope" },
  { leaf: "POST /api/employee-cases/:id/resume", group: "/api/employee-cases", category: "not-in-scope" },
  { leaf: "POST /api/employee-cases/:id/terminate", group: "/api/employee-cases", category: "not-in-scope" },
  { leaf: "POST /api/employee-cases/policy-upgrade-apply", group: "/api/employee-cases", category: "not-in-scope" },
  { leaf: "DELETE /api/event-center/subscriptions/:id", group: "/api/event-center", category: "not-in-scope" },
  { leaf: "GET /api/event-center/catalog", group: "/api/event-center", category: "not-in-scope" },
  { leaf: "GET /api/event-center/deliveries", group: "/api/event-center", category: "not-in-scope" },
  { leaf: "GET /api/event-center/deliveries/page", group: "/api/event-center", category: "not-in-scope" },
  { leaf: "GET /api/event-center/events/page", group: "/api/event-center", category: "not-in-scope" },
  { leaf: "GET /api/event-center/observers", group: "/api/event-center", category: "not-in-scope" },
  { leaf: "GET /api/event-center/sources", group: "/api/event-center", category: "not-in-scope" },
  { leaf: "GET /api/event-center/subscriptions", group: "/api/event-center", category: "not-in-scope" },
  { leaf: "GET /api/event-center/subscriptions/page", group: "/api/event-center", category: "not-in-scope" },
  { leaf: "POST /api/event-center/observations", group: "/api/event-center", category: "not-in-scope" },
  { leaf: "POST /api/event-center/subscriptions", group: "/api/event-center", category: "not-in-scope" },
  { leaf: "GET /api/execution-contracts", group: "/api/execution-contracts", category: "not-in-scope" },
  { leaf: "GET /api/execution-contracts/:id", group: "/api/execution-contracts", category: "not-in-scope" },
  { leaf: "POST /api/execution-contracts/:id/agent-candidates", group: "/api/execution-contracts", category: "not-in-scope" },
  { leaf: "GET /api/integrations/development-adapters", group: "/api/integrations", category: "not-in-scope" },
  { leaf: "GET /api/integrations/development-adapters/:id", group: "/api/integrations", category: "not-in-scope" },
  { leaf: "GET /api/integrations/development-adapters/:id/acl", group: "/api/integrations", category: "not-in-scope" },
  { leaf: "POST /api/integrations/development-adapters", group: "/api/integrations", category: "not-in-scope" },
  { leaf: "POST /api/integrations/development-adapters/:id/archive", group: "/api/integrations", category: "not-in-scope" },
  { leaf: "POST /api/integrations/development-adapters/:id/publish", group: "/api/integrations", category: "not-in-scope" },
  { leaf: "PUT /api/integrations/development-adapters/:id", group: "/api/integrations", category: "not-in-scope" },
  { leaf: "GET /api/mcps/:id/acl", group: "/api/mcps", category: "not-in-scope" },
  { leaf: "GET /api/mcps/:id/export-package", group: "/api/mcps", category: "not-in-scope" },
  { leaf: "GET /api/mcps/:id/probe", group: "/api/mcps", category: "not-in-scope" },
  { leaf: "GET /api/mcps/:id/runtime-test-session", group: "/api/mcps", category: "not-in-scope" },
  { leaf: "GET /api/mcps/:id/runtime-test-sessions/:id", group: "/api/mcps", category: "not-in-scope" },
  { leaf: "GET /api/mcps/:id/runtime-test-sessions/:id/session", group: "/api/mcps", category: "not-in-scope" },
  { leaf: "GET /api/mcps/probes", group: "/api/mcps", category: "not-in-scope" },
  { leaf: "POST /api/mcps/:id/probe", group: "/api/mcps", category: "not-in-scope" },
  { leaf: "POST /api/mcps/:id/rename", group: "/api/mcps", category: "not-in-scope" },
  { leaf: "POST /api/mcps/:id/runtime-test-sessions", group: "/api/mcps", category: "not-in-scope" },
  { leaf: "POST /api/mcps/:id/runtime-test-sessions/:id/cancel-turn", group: "/api/mcps", category: "not-in-scope" },
  { leaf: "POST /api/mcps/:id/runtime-test-sessions/:id/end", group: "/api/mcps", category: "not-in-scope" },
  { leaf: "POST /api/mcps/:id/runtime-test-sessions/:id/messages", group: "/api/mcps", category: "not-in-scope" },
  { leaf: "POST /api/memories/:id/archive", group: "/api/memories", category: "not-in-scope" },
  { leaf: "POST /api/memories/:id/promote", group: "/api/memories", category: "not-in-scope" },
  { leaf: "POST /api/memories/:id/unarchive", group: "/api/memories", category: "not-in-scope" },
  { leaf: "POST /api/plantuml/render", group: "/api/plantuml", category: "not-in-scope" },
  { leaf: "GET /api/plugins/:id/acl", group: "/api/plugins", category: "not-in-scope" },
  { leaf: "GET /api/plugins/:id/export-package", group: "/api/plugins", category: "not-in-scope" },
  { leaf: "POST /api/plugins/:id/check-update", group: "/api/plugins", category: "not-in-scope" },
  { leaf: "POST /api/plugins/:id/rename", group: "/api/plugins", category: "not-in-scope" },
  { leaf: "POST /api/plugins/:id/upgrade", group: "/api/plugins", category: "not-in-scope" },
  { leaf: "GET /api/repo-groups/:id/layout", group: "/api/repo-groups", category: "not-in-scope" },
  { leaf: "POST /api/repo-groups/preview", group: "/api/repo-groups", category: "not-in-scope" },
  { leaf: "GET /api/repos/files", group: "/api/repos", category: "not-in-scope" },
  { leaf: "POST /api/resource-packages/commit", group: "/api/resource-packages", category: "not-in-scope" },
  { leaf: "POST /api/resource-packages/preview", group: "/api/resource-packages", category: "not-in-scope" },
  { leaf: "GET /api/scheduled-tasks/:id/acl", group: "/api/scheduled-tasks", category: "not-in-scope" },
  { leaf: "POST /api/scheduled-tasks/:id/run-now", group: "/api/scheduled-tasks", category: "not-in-scope" },
  { leaf: "DELETE /api/skills/:id/file", group: "/api/skills", category: "not-in-scope" },
  { leaf: "GET /api/skills/:id/acl", group: "/api/skills", category: "not-in-scope" },
  { leaf: "GET /api/skills/:id/content", group: "/api/skills", category: "not-in-scope" },
  { leaf: "GET /api/skills/:id/export-package", group: "/api/skills", category: "not-in-scope" },
  { leaf: "GET /api/skills/:id/file", group: "/api/skills", category: "not-in-scope" },
  { leaf: "GET /api/skills/:id/files", group: "/api/skills", category: "not-in-scope" },
  { leaf: "GET /api/skills/:id/versions", group: "/api/skills", category: "not-in-scope" },
  { leaf: "GET /api/skills/:id/versions/:id/content", group: "/api/skills", category: "not-in-scope" },
  { leaf: "GET /api/skills/:id/versions/diff", group: "/api/skills", category: "not-in-scope" },
  { leaf: "POST /api/skills/:id/versions/:id/restore", group: "/api/skills", category: "not-in-scope" },
  { leaf: "POST /api/skills/import-zip/commit", group: "/api/skills", category: "not-in-scope" },
  { leaf: "POST /api/skills/import-zip/parse", group: "/api/skills", category: "not-in-scope" },
  { leaf: "PUT /api/skills/:id", group: "/api/skills", category: "not-in-scope" },
  { leaf: "PUT /api/skills/:id/content", group: "/api/skills", category: "not-in-scope" },
  { leaf: "PUT /api/skills/:id/file", group: "/api/skills", category: "not-in-scope" },
  { leaf: "GET /api/task-catalog", group: "/api/task-catalog", category: "not-in-scope" },
  { leaf: "GET /api/task-catalog/sources", group: "/api/task-catalog", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/call-targets", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/change-narrative", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/code-intel", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/feedback", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/file-content", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/file-symbols", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/members", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/node-runs/:id/events", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/node-runs/:id/inventory", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/node-runs/:id/session", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/node-runs/:id/startup-verification", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/nodes/:id/stdout", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/port-artifacts/:id/:id", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/recovery-events", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/structural-diff", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/workflow-sync-preview", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/worktree-file", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/tasks/:id/worktree-tree", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "POST /api/tasks/:id/change-narrative", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "POST /api/tasks/:id/clear-recovery-suspension", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "POST /api/tasks/:id/feedback", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "POST /api/tasks/:id/sync-workflow", group: "/api/tasks", category: "not-in-scope" },
  { leaf: "GET /api/webhook-deliveries", group: "/api/webhook-deliveries", category: "not-in-scope" },
  { leaf: "GET /api/webhook-deliveries/:id", group: "/api/webhook-deliveries", category: "not-in-scope" },
  { leaf: "GET /api/webhook-deliveries/repos", group: "/api/webhook-deliveries", category: "not-in-scope" },
  { leaf: "GET /api/webhook-endpoints", group: "/api/webhook-endpoints", category: "not-in-scope" },
  { leaf: "GET /api/webhook-endpoints/:id", group: "/api/webhook-endpoints", category: "not-in-scope" },
  { leaf: "DELETE /api/webhook-triggers/:id", group: "/api/webhook-triggers", category: "not-in-scope" },
  { leaf: "GET /api/webhook-triggers", group: "/api/webhook-triggers", category: "not-in-scope" },
  { leaf: "GET /api/webhook-triggers/:id", group: "/api/webhook-triggers", category: "not-in-scope" },
  { leaf: "GET /api/webhook-triggers/:id/fires", group: "/api/webhook-triggers", category: "not-in-scope" },
  { leaf: "POST /api/webhook-triggers", group: "/api/webhook-triggers", category: "not-in-scope" },
  { leaf: "POST /api/webhook-triggers/:id/streams/reset", group: "/api/webhook-triggers", category: "not-in-scope" },
  { leaf: "PUT /api/webhook-triggers/:id", group: "/api/webhook-triggers", category: "not-in-scope" },
  { leaf: "GET /api/workflows/:id/acl", group: "/api/workflows", category: "not-in-scope" },
  { leaf: "GET /api/workflows/:id/export-package", group: "/api/workflows", category: "not-in-scope" },
  { leaf: "POST /api/workflows/:id/copy", group: "/api/workflows", category: "not-in-scope" },
  { leaf: "POST /api/workflows/:id/validate", group: "/api/workflows", category: "not-in-scope" },
  { leaf: "POST /api/workflows/:id/validate-draft", group: "/api/workflows", category: "not-in-scope" },
  { leaf: "GET /api/workgroups/:id/acl", group: "/api/workgroups", category: "not-in-scope" },
  { leaf: "GET /api/workgroups/:id/export-package", group: "/api/workgroups", category: "not-in-scope" },
  { leaf: "GET /api/workgroups/:id/resource-status", group: "/api/workgroups", category: "not-in-scope" },
  { leaf: "POST /api/workgroups/:id/copy", group: "/api/workgroups", category: "not-in-scope" },
  { leaf: "POST /api/workgroups/:id/rename", group: "/api/workgroups", category: "not-in-scope" },
  { leaf: "POST /api/workgroups/:id/tasks", group: "/api/workgroups", category: "not-in-scope" },
  { leaf: "GET /api/worktree-files/:id", group: "/api/worktree-files", category: "not-in-scope" },
  { leaf: "GET /api/worktree-files/:id/*", group: "/api/worktree-files", category: "not-in-scope" },
  { leaf: "POST /api/backup", group: "/api/backup", category: "system-point" },
  { leaf: "GET /api/config", group: "/api/config", category: "system-point" },
  { leaf: "PUT /api/config", group: "/api/config", category: "system-point" },
  { leaf: "GET /api/daemon", group: "/api/daemon", category: "system-point" },
  { leaf: "GET /api/intent-provenance/:id/:id", group: "/api/intent-provenance", category: "system-point" },
  { leaf: "DELETE /api/intent-sessions/:id/mounts/:id", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "DELETE /api/intent-sessions/:id/working-set/:id", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "GET /api/intent-sessions", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "GET /api/intent-sessions/:id", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "GET /api/intent-sessions/:id/turns/:id/session", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/answers", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/archive", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/cancel-turn", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/commit", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/current-action", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/iterations", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/messages", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/mount-approvals", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/mounts", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/rebase", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/reopen", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/retry", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/working-set", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "POST /api/intent-sessions/:id/working-set/:id/retry", group: "/api/intent-sessions", category: "system-point" },
  { leaf: "GET /api/maintenance/disk", group: "/api/maintenance", category: "system-point" },
  { leaf: "POST /api/maintenance/disk/cleanup", group: "/api/maintenance", category: "system-point" },
  { leaf: "GET /api/memory-distill-jobs", group: "/api/memory-distill-jobs", category: "system-point" },
  { leaf: "GET /api/memory-distill-jobs/:id", group: "/api/memory-distill-jobs", category: "system-point" },
  { leaf: "GET /api/memory-distill-jobs/:id/session", group: "/api/memory-distill-jobs", category: "system-point" },
  { leaf: "POST /api/memory-distill-jobs/:id/cancel", group: "/api/memory-distill-jobs", category: "system-point" },
  { leaf: "POST /api/memory-distill-jobs/:id/retry", group: "/api/memory-distill-jobs", category: "system-point" },
  { leaf: "DELETE /api/oidc/providers/:id", group: "/api/oidc", category: "system-point" },
  { leaf: "GET /api/oidc/login-policy", group: "/api/oidc", category: "system-point" },
  { leaf: "GET /api/oidc/providers", group: "/api/oidc", category: "system-point" },
  { leaf: "GET /api/oidc/providers/:id", group: "/api/oidc", category: "system-point" },
  { leaf: "PATCH /api/oidc/providers/:id", group: "/api/oidc", category: "system-point" },
  { leaf: "POST /api/oidc/providers", group: "/api/oidc", category: "system-point" },
  { leaf: "POST /api/oidc/providers/:id/test", group: "/api/oidc", category: "system-point" },
  { leaf: "PUT /api/oidc/login-policy", group: "/api/oidc", category: "system-point" },
  { leaf: "DELETE /api/restore/pending", group: "/api/restore", category: "system-point" },
  { leaf: "GET /api/restore/pending", group: "/api/restore", category: "system-point" },
  { leaf: "POST /api/restore", group: "/api/restore", category: "system-point" },
  { leaf: "GET /api/runtime/models", group: "/api/runtime", category: "system-point" },
  { leaf: "DELETE /api/runtimes/:id", group: "/api/runtimes", category: "system-point" },
  { leaf: "GET /api/runtimes", group: "/api/runtimes", category: "system-point" },
  { leaf: "GET /api/runtimes/status", group: "/api/runtimes", category: "system-point" },
  { leaf: "POST /api/runtimes", group: "/api/runtimes", category: "system-point" },
  { leaf: "POST /api/runtimes/:id/enabled", group: "/api/runtimes", category: "system-point" },
  { leaf: "POST /api/runtimes/:id/probe", group: "/api/runtimes", category: "system-point" },
  { leaf: "POST /api/runtimes/probe", group: "/api/runtimes", category: "system-point" },
  { leaf: "PUT /api/runtimes/:id", group: "/api/runtimes", category: "system-point" },
  { leaf: "POST /api/tasks/archive", group: "/api/tasks", category: "system-point" },
  { leaf: "DELETE /api/users/:id", group: "/api/users", category: "system-point" },
  { leaf: "GET /api/users", group: "/api/users", category: "system-point" },
  { leaf: "GET /api/users/:id", group: "/api/users", category: "system-point" },
  { leaf: "GET /api/users/search", group: "/api/users", category: "system-point" },
  { leaf: "PATCH /api/users/:id", group: "/api/users", category: "system-point" },
  { leaf: "POST /api/users", group: "/api/users", category: "system-point" },
  { leaf: "POST /api/users/:id/reset-password", group: "/api/users", category: "system-point" },
  { leaf: "POST /api/users/lookup", group: "/api/users", category: "system-point" },
]

/** 每组一条理由。守卫要求：每个用到的 group 都在这里有非空理由。 */
export const EXEMPT_REASONS: Readonly<Record<string, string>> = {
  "(infrastructure)": "不是产品 API：/health 是存活探针，/.well-known/mcp 是 MCP 客户端接入前读的 discovery 文档——两者都在认证之前、面向运维与客户端而非模型。给它们做工具等于让模型去读它自己所在通道的说明书。",
  "/api/account": "tokenAccess 为 never —— PAT 不得开这扇门（RFC-247 D5/D6：不得发令牌、不得改 owner / grants / visibility）。",
  "/api/agents": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/auth": "tokenAccess 为 never —— PAT 不得开这扇门（RFC-247 D5/D6：不得发令牌、不得改 owner / grants / visibility）。",
  "/api/backup": "权限点在 SYSTEM_DOMAIN_POINTS，resolveTokenPermissions 会把它从任何 PAT 上剔除——工具声明该权限则永不出现在 tools/list，声明空权限则恒 403。不是待办：补工具解决不了，要改的是权限目录。",
  "/api/cached-repos": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/capability-templates": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/clarify": "够得着也不给：pending-count 只是数字，模型要的是行（list_pending_gates 给行）；POST /api/fusions 是发起不是门，与 launch_task 同类、归三类；whoami / overview / docs 由 describe_capabilities 与 describe_resource 覆盖同一需求。",
  "/api/code": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/code-hosts": "tokenAccess 为 never —— PAT 不得开这扇门（RFC-247 D5/D6：不得发令牌、不得改 owner / grants / visibility）。",
  "/api/config": "权限点在 SYSTEM_DOMAIN_POINTS，resolveTokenPermissions 会把它从任何 PAT 上剔除——工具声明该权限则永不出现在 tools/list，声明空权限则恒 403。不是待办：补工具解决不了，要改的是权限目录。",
  "/api/daemon": "权限点在 SYSTEM_DOMAIN_POINTS，resolveTokenPermissions 会把它从任何 PAT 上剔除——工具声明该权限则永不出现在 tools/list，声明空权限则恒 403。不是待办：补工具解决不了，要改的是权限目录。",
  "/api/digital-employee-input-uploads": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/digital-employee-job-templates": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/digital-employee-types": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/digital-employees": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/docs": "够得着也不给：pending-count 只是数字，模型要的是行（list_pending_gates 给行）；POST /api/fusions 是发起不是门，与 launch_task 同类、归三类；whoami / overview / docs 由 describe_capabilities 与 describe_resource 覆盖同一需求。",
  "/api/employee-cases": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/event-center": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/execution-contracts": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/fusions": "够得着也不给：pending-count 只是数字，模型要的是行（list_pending_gates 给行）；POST /api/fusions 是发起不是门，与 launch_task 同类、归三类；whoami / overview / docs 由 describe_capabilities 与 describe_resource 覆盖同一需求。",
  "/api/integrations": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/intent-provenance": "权限点在 SYSTEM_DOMAIN_POINTS，resolveTokenPermissions 会把它从任何 PAT 上剔除——工具声明该权限则永不出现在 tools/list，声明空权限则恒 403。不是待办：补工具解决不了，要改的是权限目录。",
  "/api/intent-sessions": "权限点在 SYSTEM_DOMAIN_POINTS，resolveTokenPermissions 会把它从任何 PAT 上剔除——工具声明该权限则永不出现在 tools/list，声明空权限则恒 403。不是待办：补工具解决不了，要改的是权限目录。",
  "/api/maintenance": "权限点在 SYSTEM_DOMAIN_POINTS，resolveTokenPermissions 会把它从任何 PAT 上剔除——工具声明该权限则永不出现在 tools/list，声明空权限则恒 403。不是待办：补工具解决不了，要改的是权限目录。",
  "/api/mcps": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/memories": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/memory-distill-jobs": "权限点在 SYSTEM_DOMAIN_POINTS，resolveTokenPermissions 会把它从任何 PAT 上剔除——工具声明该权限则永不出现在 tools/list，声明空权限则恒 403。不是待办：补工具解决不了，要改的是权限目录。",
  "/api/oidc": "权限点在 SYSTEM_DOMAIN_POINTS，resolveTokenPermissions 会把它从任何 PAT 上剔除——工具声明该权限则永不出现在 tools/list，声明空权限则恒 403。不是待办：补工具解决不了，要改的是权限目录。",
  "/api/overview": "够得着也不给：pending-count 只是数字，模型要的是行（list_pending_gates 给行）；POST /api/fusions 是发起不是门，与 launch_task 同类、归三类；whoami / overview / docs 由 describe_capabilities 与 describe_resource 覆盖同一需求。",
  "/api/plantuml": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/plugins": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/repo-groups": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/repos": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/resource-packages": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/restore": "权限点在 SYSTEM_DOMAIN_POINTS，resolveTokenPermissions 会把它从任何 PAT 上剔除——工具声明该权限则永不出现在 tools/list，声明空权限则恒 403。不是待办：补工具解决不了，要改的是权限目录。",
  "/api/reviews": "够得着也不给：pending-count 只是数字，模型要的是行（list_pending_gates 给行）；POST /api/fusions 是发起不是门，与 launch_task 同类、归三类；whoami / overview / docs 由 describe_capabilities 与 describe_resource 覆盖同一需求。",
  "/api/runtime": "权限点在 SYSTEM_DOMAIN_POINTS，resolveTokenPermissions 会把它从任何 PAT 上剔除——工具声明该权限则永不出现在 tools/list，声明空权限则恒 403。不是待办：补工具解决不了，要改的是权限目录。",
  "/api/runtimes": "权限点在 SYSTEM_DOMAIN_POINTS，resolveTokenPermissions 会把它从任何 PAT 上剔除——工具声明该权限则永不出现在 tools/list，声明空权限则恒 403。不是待办：补工具解决不了，要改的是权限目录。",
  "/api/scheduled-tasks": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/skills": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/task-catalog": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/tasks": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/tokens": "tokenAccess 为 never —— PAT 不得开这扇门（RFC-247 D5/D6：不得发令牌、不得改 owner / grants / visibility）。",
  "/api/users": "权限点在 SYSTEM_DOMAIN_POINTS，resolveTokenPermissions 会把它从任何 PAT 上剔除——工具声明该权限则永不出现在 tools/list，声明空权限则恒 403。不是待办：补工具解决不了，要改的是权限目录。",
  "/api/webhook-deliveries": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/webhook-endpoints": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/webhook-triggers": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/whoami": "够得着也不给：pending-count 只是数字，模型要的是行（list_pending_gates 给行）；POST /api/fusions 是发起不是门，与 launch_task 同类、归三类；whoami / overview / docs 由 describe_capabilities 与 describe_resource 覆盖同一需求。",
  "/api/workflows": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/workgroup-tasks": "够得着也不给：pending-count 只是数字，模型要的是行（list_pending_gates 给行）；POST /api/fusions 是发起不是门，与 launch_task 同类、归三类；whoami / overview / docs 由 describe_capabilities 与 describe_resource 覆盖同一需求。",
  "/api/workgroups": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
  "/api/worktree-files": "三类 / 四类：该做但不在 RFC-329 范围（proposal §2.3 / §2.4），等后续 RFC。",
}

/** 扁平叶子清单——账本清点与守卫判定用的是同一个数。 */
export function exemptionLeaves(): string[] {
  return MCP_SURFACE_EXEMPTION_LEAVES.map((entry) => entry.leaf)
}
