// RFC-359 W5-T19f —— 测试面「不得写死引擎」的高水位账本（只降不升）。
//
// **为什么单引擎测试是本 RFC 的核心风险。** `describeEachProvider`（`tests/helpers/eachProvider.ts`）
// 是 RFC-359 的双引擎 harness，而且**双引擎是缺省**：不设 `AW_TEST_PROVIDERS` 就两个引擎各跑一遍，
// PostgreSQL 侧没有 URL 是 **fail 而不是 skip**（`AW_TEST_PROVIDERS=sqlite` 只是本地的显式降级，
// Ubuntu CI 保持双引擎）。绕开它、直接在测试里建一个 SQLite 内存库，写出来的判据就**只验证 SQLite 一个引擎**——
// PostgreSQL 侧的同一段实现拿不到任何行为覆盖。这不是风格问题，是让 parity 缺陷一路穿过全部验收的
// **机制本身**：`design/dual-provider-parity-audit-2026-09-04.md` 里 12 条 P0 全是这么漏过去的，
// PG 侧实现长期零行为覆盖，直到两侧合一时才发现它比 SQLite 侧更弱（漏引用完整性复核、漏幂等回放）。
// 也就是说，只要还允许新写单引擎测试，本 RFC 收敛掉的实现分支就会从测试面再长回来。
//
// **为什么现在是高水位而不是 0。** 存量调用点散在几百个测试文件里，一次性迁移等于把整棵测试树重写一遍，
// 在本仓的并发工作树上必然撞车。所以本轮**只上守卫、不做迁移**：先把「还剩多少」变成可计数、可防守的量，
// 长期目标仍然是 0——每个后续波次顺手迁一批、把账本改小一格。
//
// **机制**同 RFC-317 T17 与 `rfc359-sync-transaction-highwater.test.ts`：逐文件列出调用点数、
// 与实测**逐字相等**。**增**了红——有人又写了一条只验证 SQLite 的判据；**减**了也红——收敛发生了，
// 把账本一起改小，让每一次迁移都留下一次有署名的提交记录。
//
// **两处豁免**：`helpers/eachProvider.ts` 是 harness 自己的家（SQLite 侧的库正是它用这个工厂造的）；
// 本文件正文里成段提到这个符号，扫自己等于自造债。除此之外整棵 `tests/` 树一视同仁——
// 夹具（`helpers/*.ts`）与用例同等对待，夹具写死引擎同样让它的全部下游只剩一个引擎的覆盖。

import { describe, expect, test } from 'bun:test'
import { readdirSync, readFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

const TESTS = resolve(import.meta.dir, '..')

/** harness 自己 + 本守卫：正文里提到这个符号，不算调用点。 */
const EXEMPT: ReadonlySet<string> = new Set([
  'helpers/eachProvider.ts',
  'architecture/rfc359-w5-t19f-test-engine-hardcoding.test.ts',
])

/** 整棵 `tests/` 树的 `.ts` 枚举——既是语料下限的分母，也是下面逐文件计数的唯一输入。 */
function enumerateTestSources(): string[] {
  const out: string[] = []
  const walk = (dir: string): void => {
    for (const entry of readdirSync(join(TESTS, dir), { withFileTypes: true })) {
      const rel = dir === '' ? entry.name : `${dir}/${entry.name}`
      if (entry.isDirectory()) walk(rel)
      else if (entry.name.endsWith('.ts')) out.push(rel)
    }
  }
  walk('')
  return out.sort()
}

/**
 * 模块级只枚举一次。**故意是个数组常量**：语料下限断言直接打在 `CORPUS_FILES.length` 上，
 * 「枚举 → 被数的量 → 断言」这条链一眼可追溯，`census.ts` 的 `measuredCorpusSize`
 * （`rfc317-guard-corpus-floor` 的判据）才认得出这是一条真语料下限。上一版把规模藏在
 * `scan().corpus` 这个数字属性里，两条判据（子树里要有 `.length`/`.size`、被数的东西要能
 * 追溯到枚举）双双落空，于是本守卫被点名「枚举文件却没有任何语料规模断言」。
 */
const CORPUS_FILES: readonly string[] = enumerateTestSources()

/**
 * `<相对 tests/ 的路径>: <直接建 SQLite 内存库的调用点数>`，按路径字典序。只降不升。
 * 迁移姿势：把 `describe(...)` 换成 `describeEachProvider(name, (harness) => ...)`，
 * 库从 `harness.db` 取（需要事务面就取 `harness.session`，需要按引擎分叉就看 `harness.capabilities`）。
 */
export const TEST_ENGINE_HARDCODING_DEBT: readonly string[] = [
  'admin-only-gate.test.ts: 1',
  'agents-closure-endpoints.test.ts: 1',
  'agents.test.ts: 2',
  'api-code-routes.test.ts: 1',
  'api-tasks-alerts-visibility.test.ts: 1',
  'api-tasks-alerts.test.ts: 1',
  'api-tasks-diagnose.test.ts: 1',
  'api-tasks-repair.test.ts: 1',
  'architecture/rfc329-mcp-surface-guard.test.ts: 1',
  'architecture/rfc359-w5-t19g-schema-contract-reconciliation.test.ts: 2',
  'auth-routes.test.ts: 1',
  'auth-self-service-idor.test.ts: 1',
  'auth-session.test.ts: 4',
  'backup.test.ts: 3',
  'cached-repos-http-batch.test.ts: 1',
  'cached-repos-http.test.ts: 1',
  'callgraph-multirepo-prefix.test.ts: 1',
  'change-narrative.test.ts: 8',
  'clarify-baseline-rest-ws.test.ts: 5',
  'clarify-inline-isolated-parity.test.ts: 1',
  'clarify-review-combination-scenarios.test.ts: 1',
  'cli.test.ts: 2',
  'commit-push-runner.test.ts: 1',
  'contracts/harness.ts: 1',
  'createindb-snapshot-parity.test.ts: 8',
  'daemon-info-route.test.ts: 1',
  'digital-employee-agent-template-reconcile.test.ts: 5',
  'distill-session-capture.test.ts: 1',
  'e2e-sqlite-fixture-lock-contention.test.ts: 3',
  'execution-contract-platform.test.ts: 5',
  'fixtures/rfc322-cpu-probe.ts: 1',
  'fixtures/rfc338-blocking-maintenance-worker.ts: 1',
  'fixtures/rfc338-foreground-contention-worker.ts: 1',
  'fixtures/rfc349-postgresql-crash-worker.ts: 1',
  'fixtures/rfc351-write-contention-worker.ts: 1',
  'flag-audit-kind-canonicalization.test.ts: 1',
  'fusion-engine.test.ts: 1',
  'gc.test.ts: 1',
  'gettask-multi-repo.test.ts: 1',
  'git-repo-cache-submodule.test.ts: 1',
  'git-repo-cache.test.ts: 2',
  'helpers/rfc310Pr3Fixture.ts: 1',
  'helpers/rfc349PostgresqlHostedEvidence.ts: 2',
  'input-port-contract.test.ts: 1',
  'integration-chaos/chaos-scenarios.integration.test.ts: 2',
  'intent-agent-branch-ports.test.ts: 1',
  'intent-mcp-oauth.test.ts: 1',
  'intent-privileged-node-capability.test.ts: 1',
  'inventory-in-flight-fallback.test.ts: 1',
  'lifecycle-property.test.ts: 1',
  'lifecycle-repair-harness.ts: 1',
  'lifecycle-transitions-current.test.ts: 1',
  'lifecycle-wrapper-nested.test.ts: 1',
  'limits.test.ts: 1',
  'mcp-end-to-end.test.ts: 1',
  'mcps-http.test.ts: 1',
  'memory-distiller-source-context.test.ts: 1',
  'memory-distiller.test.ts: 3',
  'migration-0002.test.ts: 1',
  'migration-0008-cached-repos.test.ts: 1',
  'migration-0010-opencode-session-id.test.ts: 1',
  'migration-0011-mcps.test.ts: 1',
  'migration-0012-node-run-events-session.test.ts: 1',
  'migration-0014-plugins.test.ts: 1',
  'migration-0015-inventory.test.ts: 1',
  'migration-0016-mcp-probes.test.ts: 1',
  'migration-0017-cached-repos-submodules.test.ts: 1',
  'migration-0021-task-name.test.ts: 1',
  'migration-0022-wrapper-progress.test.ts: 1',
  'migration-0023-rfc041.test.ts: 1',
  'migration-0024-distill-capture.test.ts: 1',
  'migration-0025-injected-memories.test.ts: 1',
  'migration-0026-port-validation-failures.test.ts: 1',
  'migration-0027-distill-output-lang.test.ts: 1',
  'migration-0028.test.ts: 3',
  'migration-0029-rfc056-cross-clarify.test.ts: 7',
  'migration-0030.test.ts: 5',
  'migration-0031-clarify-rounds.test.ts: 8',
  'migration-0032-rfc059-question-scopes.test.ts: 1',
  'migration-0033-task-git-identity.test.ts: 4',
  'migration-0034-task-repos.test.ts: 5',
  'migration-0037-output-kind.test.ts: 2',
  'migration-0038-backfill-review-kind.test.ts: 1',
  'migration-0039-rfc075.test.ts: 5',
  'migration-0040-rfc074-consumed-runs.test.ts: 4',
  'migration-0041-rfc074-drop-cci.test.ts: 3',
  'migration-0042-rfc079-doc-versions.test.ts: 1',
  'migration-0043-shard-value-hash.test.ts: 3',
  'migration-0044-rerun-cause.test.ts: 4',
  'migration-0057-rfc115-drop-agent-params.test.ts: 5',
  'migration-0058-rfc115-drop-agent-snapshot.test.ts: 5',
  'migration-0090-rfc170.test.ts: 2',
  'migration-0092-rfc178.test.ts: 2',
  'migration-0098-rfc204-repo-cred.test.ts: 1',
  'migration-0102-rfc210-submodule-isolation.test.ts: 1',
  'migration-0104-rfc211-drop-onboarding.test.ts: 1',
  'migration-0111-rfc223.test.ts: 5',
  'migration-0112-rfc223-pr2.test.ts: 2',
  'migration-0113-rfc223-pr3.test.ts: 2',
  'migration-0114-rfc225-workgroup-version.test.ts: 2',
  'migration-0115-rfc223-pr3a-terminal.test.ts: 2',
  'migration-0116-rfc223-skill-identity.test.ts: 2',
  'migration-0117-rfc223-fusion-provenance.test.ts: 3',
  'migration-0118-rfc223-owner-scoped-names.test.ts: 2',
  'migration-0119-rfc224-opencode-session-owners.test.ts: 2',
  'migration-0120-rfc224-runtime-probe-fence.test.ts: 1',
  'migration-0121-rfc227-opencode-provenance.test.ts: 1',
  'migration-0122-rfc229-workgroup-message-trigger.test.ts: 1',
  'migration-0124-rfc235-intent-turn-session.test.ts: 1',
  'migration-0125-rfc238-mcp-runtime-playground.test.ts: 1',
  'migration-0128-rfc244-task-list-indexes.test.ts: 3',
  'migration-0138-rfc257-webhook-triggers.test.ts: 1',
  'migration-0144-rfc276-runtime-hardening-deprecation.test.ts: 2',
  'migration-0150-rfc292-trigger-namespace.test.ts: 1',
  'migration-0151-rfc285-workflow-soft-link.test.ts: 1',
  'migration-0152-rfc293-intent-workbench.test.ts: 1',
  'migration-0155-rfc301-task-launch-origin.test.ts: 1',
  'migration-0156-rfc300-workspace-prune-cause.test.ts: 1',
  'migration-0157-rfc303-mr-terminal-control.test.ts: 1',
  'migration-0162-rfc305-user-permissions.test.ts: 1',
  'migration-0173-rfc308-workspace-profile.test.ts: 1',
  'migration-0188-rfc312-presence-grant.test.ts: 1',
  'migration-0193-rfc310-custom-event-sources.test.ts: 1',
  'migration-0194-rfc310-unified-event-delivery.test.ts: 2',
  'migration-0195-rfc310-work-start-lifecycle-events.test.ts: 1',
  'migration-0196-rfc310-task-event-delivery-link.test.ts: 1',
  'migration-0197-rfc310-event-response-rules.test.ts: 1',
  'migration-0198-rfc310-event-catalog-visibility.test.ts: 1',
  'migration-0202-rfc315-event-automation-permissions.test.ts: 1',
  'migration-0203-task-catalog-visibility.test.ts: 1',
  'migration-0205-rfc310-task-employee-case-link.test.ts: 1',
  'migration-0206-rfc310-employee-case-name.test.ts: 1',
  'migration-0208-rfc321-repository-transport-credentials.test.ts: 1',
  'migration-0218-rfc341-committed-events.test.ts: 1',
  'migration-0219-rfc341-task-cutover.test.ts: 1',
  'migration-0220-rfc341-committed-delivery-fk-repair.test.ts: 1',
  'migration-0221-rfc342-memory-scope-move-events.test.ts: 1',
  'migration-0222-rfc341-collaboration-cutover.test.ts: 2',
  'oidc-providers-service.test.ts: 1',
  'opencode-session-walk.test.ts: 1',
  'pats.test.ts: 1',
  'plantuml-proxy.test.ts: 1',
  'plugins-http.test.ts: 1',
  'repo-batch-import-gc.test.ts: 2',
  'repo-batch-import-retry.test.ts: 7',
  'repo-batch-import.test.ts: 1',
  'repos-path-allowlist.test.ts: 1',
  'repos.test.ts: 1',
  'rerun-prior-output-e2e.test.ts: 1',
  'resource-by-id-resolve.test.ts: 1',
  'resume-multi-repo-rollback.test.ts: 1',
  'resume-task-idempotent.test.ts: 1',
  'retry-cascade-kind-matrix.test.ts: 1',
  'retry-node-guard-order.test.ts: 1',
  'retry-node-no-review-cascade.test.ts: 1',
  'review-cancel-concurrency.test.ts: 1',
  'review-clarify-question-phase-stranded.test.ts: 1',
  'review-iterate-comments-in-prompt.test.ts: 1',
  'review-iterate-drops-prior-clarify-history.test.ts: 1',
  'review-iterate-file-path-in-prompt.test.ts: 1',
  'review-iterate-sibling-cascade.test.ts: 1',
  'review-multidoc-inherit.test.ts: 1',
  'review-state-machine.test.ts: 1',
  'reviews-comment-patch.test.ts: 1',
  'reviews-iterate-mints-new-run.test.ts: 1',
  'reviews-version-comments.test.ts: 1',
  'rfc074-prc-cci-retirement.test.ts: 2',
  'rfc092-followup-chain-rollback.test.ts: 1',
  'rfc092-leaked-pending-bounded.test.ts: 1',
  'rfc092-midrun-clarify-dispatch.test.ts: 1',
  'rfc092-midrun-review-iterate.test.ts: 1',
  'rfc093-db-tx-sync.test.ts: 1',
  'rfc095-wrapper-canceled-revival.test.ts: 1',
  'rfc096-retry-cascade-inherit.test.ts: 1',
  'rfc097-cancel-wins.test.ts: 1',
  'rfc097-pending-orphan-reap.test.ts: 1',
  'rfc097-repair-liveness.test.ts: 1',
  'rfc097-resume-mutex.test.ts: 1',
  'rfc097-task-status-cas.test.ts: 1',
  'rfc098-commitpush-nonblocking.test.ts: 1',
  'rfc098-fanout-consumed-gate.test.ts: 1',
  'rfc098-fanout-shard-hash-rerun.test.ts: 1',
  'rfc098-git-predirty-diff.test.ts: 1',
  'rfc098-git-wrapper-diff-fail.test.ts: 1',
  'rfc098-process-governance.test.ts: 1',
  'rfc098-snapshot-pin.test.ts: 1',
  'rfc098-wrapper-revival-e2e.test.ts: 1',
  'rfc098-wrapper-stale-redispatch.test.ts: 1',
  'rfc098-write-lock-registry.test.ts: 2',
  'rfc099-acl-endpoints-matrix.test.ts: 1',
  'rfc099-membership-attribution.test.ts: 2',
  'rfc099-migration-0045.test.ts: 1',
  'rfc099-resource-acl.test.ts: 1',
  'rfc099-resource-routes.test.ts: 1',
  'rfc099-task-members.test.ts: 1',
  'rfc099-ws-acl-filter.test.ts: 1',
  'rfc101-builtin-list-hidden.test.ts: 1',
  'rfc103-login-timing.test.ts: 1',
  'rfc104-builtin-readonly.test.ts: 1',
  'rfc107-url-upload-multipart.test.ts: 3',
  'rfc108-resume-safety.test.ts: 1',
  'rfc109-sync-route.test.ts: 1',
  'rfc109-sync-task-workflow.test.ts: 1',
  'rfc120-deferred-dispatch.test.ts: 42',
  'rfc120-task-questions-route.test.ts: 3',
  'rfc122-clarify-directive-dispatch.test.ts: 2',
  'rfc122-clarify-directive-route.test.ts: 6',
  'rfc123-stop-enforcement.test.ts: 1',
  'rfc127-borrow.test.ts: 1',
  'rfc128-p2-per-question-endpoint.test.ts: 1',
  'rfc128-p5-d-autodispatch.test.ts: 28',
  'rfc130-crash-replay.test.ts: 1',
  'rfc130-iso-gc.test.ts: 2',
  'rfc130-merge-agent-scheduler.test.ts: 1',
  'rfc130-shard-rerun-undo.test.ts: 4',
  'rfc130-wrapper-private-canonical.test.ts: 1',
  'rfc131-review-reject-aging-prior-output.test.ts: 1',
  'rfc135-runtimes-status.test.ts: 1',
  'rfc140-one-click-dispatch-all.test.ts: 4',
  'rfc142-review-rounds.test.ts: 2',
  'rfc144-merge-state-cas.test.ts: 1',
  'rfc144-migration-0076.test.ts: 1',
  'rfc144-stale-replay-regression.test.ts: 2',
  'rfc145-migration-0077.test.ts: 2',
  'rfc145-write-side.test.ts: 1',
  'rfc152-ws-channel-registry.test.ts: 2',
  'rfc152-ws-frame-gates.test.ts: 1',
  'rfc152-ws-task-channel.test.ts: 1',
  'rfc154-runtime-config-dir.test.ts: 8',
  'rfc161-defer-full-seal-broadcast.test.ts: 1',
  'rfc162-migration-0081.test.ts: 1',
  'rfc164-workgroup-engine.test.ts: 8',
  'rfc164-workgroup-room.test.ts: 2',
  'rfc164-workgroups.test.ts: 2',
  'rfc165-agent-launch.test.ts: 5',
  'rfc165-file-cache-key.test.ts: 1',
  'rfc165-migration-0085.test.ts: 1',
  'rfc165-optional-clarify.test.ts: 1',
  'rfc165-scheduled-heal.test.ts: 1',
  'rfc165-scheduled-kinds.test.ts: 3',
  'rfc165-scratch-space.test.ts: 1',
  'rfc165-workspace-gc.test.ts: 1',
  'rfc166-roster-capability-cards.test.ts: 4',
  'rfc167-dw-e2e.test.ts: 2',
  'rfc167-dynamic-workflow-engine.test.ts: 3',
  'rfc170-acl-revision-cas.test.ts: 1',
  'rfc172-dispatch-shard.test.ts: 18',
  'rfc181-autonomous-hardening.test.ts: 2',
  'rfc183-clarify-invite-accept-symmetry.test.ts: 1',
  'rfc186-workgroup-e2e.test.ts: 1',
  'rfc187-fanout-salvage-e2e.test.ts: 1',
  'rfc187-workgroup-e2e.test.ts: 1',
  'rfc188-isolated-agent-run.test.ts: 4',
  'rfc189-wg-round.test.ts: 1',
  'rfc190-overview-route.test.ts: 1',
  'rfc193-force-include.test.ts: 1',
  'rfc193-port-artifacts-api.test.ts: 1',
  'rfc193-port-artifacts.test.ts: 1',
  'rfc193-wrapper-review.test.ts: 1',
  'rfc199-start-task-workflow-race.test.ts: 1',
  'rfc199-workflow-revision.test.ts: 6',
  'rfc199-workflow-validate-draft.test.ts: 1',
  'rfc200-runner-wire.test.ts: 1',
  'rfc201-mcp-exact-operation.test.ts: 1',
  'rfc201-plugin-exact-operation.test.ts: 1',
  'rfc202-lifecycle-exits.test.ts: 5',
  'rfc203-refs-acl.test.ts: 1',
  'rfc204-cached-repo-wire-and-reuse.test.ts: 3',
  'rfc204-cold-clone-seal.test.ts: 2',
  'rfc204-credential-sealing.test.ts: 8',
  'rfc205-mirror-origin-sanitize.test.ts: 1',
  'rfc207-runtime-accounting.test.ts: 1',
  'rfc210-commitpush-nested-precommitted.test.ts: 1',
  'rfc210-commitpush-subrepo.test.ts: 1',
  'rfc210-commitpush-untouched-subrepo.test.ts: 1',
  'rfc210-refresh-recency-self-renewal.test.ts: 1',
  'rfc212-revalidation-behavior.test.ts: 13',
  'rfc212-revalidation-infrastructure.test.ts: 3',
  'rfc213-pending-restore.test.ts: 1',
  'rfc213-restore.test.ts: 3',
  'rfc217-migration-0107.test.ts: 1',
  'rfc217-workgroup-task-state.test.ts: 1',
  'rfc218-agent-launch-ports.test.ts: 5',
  'rfc220-oauth2-callback-route.test.ts: 1',
  'rfc220-oauth2-provider-schema-service.test.ts: 1',
  'rfc220-presented-name-sync.test.ts: 3',
  'rfc220-probe.test.ts: 1',
  'rfc221-account-auth-policy.test.ts: 1',
  'rfc221-auth-policy.test.ts: 10',
  'rfc221-bootstrap-auth.test.ts: 1',
  'rfc221-login-policy-routes.test.ts: 4',
  'rfc222-delete-confirm.test.ts: 1',
  'rfc222-manager-role.test.ts: 2',
  'rfc222-task-delete.test.ts: 1',
  'rfc223-import-refs.test.ts: 1',
  'rfc223-owner-transfer.test.ts: 2',
  'rfc223-pr1-impl-gate.test.ts: 1',
  'rfc223-pr2-refs.test.ts: 2',
  'rfc223-pr3a-consumers.test.ts: 1',
  'rfc223-pr3b-dynamic-token.test.ts: 2',
  'rfc223-pr5-boot-restore-wiring.test.ts: 3',
  'rfc223-pr6-injection-identity.test.ts: 1',
  'rfc223-pr9-cross-tenant-adversarial.test.ts: 5',
  'rfc223-reference-write-fence.test.ts: 1',
  'rfc223-reverse-delete-races.test.ts: 1',
  'rfc223-scheduled-target-races.test.ts: 2',
  'rfc225-workgroup-revision.test.ts: 3',
  'rfc225-workgroups-ws.test.ts: 2',
  'rfc228-agent-resource-integrity.test.ts: 1',
  'rfc230-run-liveness.test.ts: 6',
  'rfc230-wrapper-finalize-superseded.test.ts: 1',
  'rfc231-private-copy.test.ts: 6',
  'rfc232-owner-list.test.ts: 3',
  'rfc234-apply-changeset.test.ts: 1',
  'rfc234-config-intent-runtime.test.ts: 1',
  'rfc234-dump-builder.test.ts: 1',
  'rfc234-intent-routes.test.ts: 1',
  'rfc234-turn-engine.test.ts: 1',
  'rfc238-mcp-runtime-test-http.test.ts: 1',
  'rfc238-mcp-runtime-test-real-e2e.test.ts: 1',
  'rfc238-mcp-runtime-test-service.test.ts: 1',
  'rfc238-mcp-runtime-test-transitions.test.ts: 6',
  'rfc239-route-error-codes.test.ts: 1',
  'rfc243-call-refs-yaml.test.ts: 3',
  'rfc243-call-workflow.test.ts: 3',
  'rfc243-call-workgroup.test.ts: 1',
  'rfc243-executor-facade.test.ts: 6',
  'rfc243-list-child-count.test.ts: 5',
  'rfc243-parent-child-lifecycle.test.ts: 12',
  'rfc244-task-operations.test.ts: 9',
  'rfc247-api-docs.test.ts: 3',
  'rfc247-mcp-server.test.ts: 1',
  'rfc247-mcp-transport.test.ts: 1',
  'rfc247-token-audit.test.ts: 1',
  'rfc247-token-delete-confirm.test.ts: 1',
  'rfc248-materialize-group.test.ts: 1',
  'rfc248-migration-repo-groups.test.ts: 3',
  'rfc248-readonly-dirty-visible.test.ts: 1',
  'rfc248-repo-group-service.test.ts: 1',
  'rfc248-repo-groups-http.test.ts: 1',
  'rfc249-migration-repo-group-nodes.test.ts: 1',
  'rfc251-product-boundary.test.ts: 1',
  'rfc257-webhook-dispatch.test.ts: 1',
  'rfc257-webhook-e2e.test.ts: 1',
  'rfc257-webhook-error-codes.test.ts: 1',
  'rfc257-webhook-ingress.test.ts: 2',
  'rfc257-webhook-management.test.ts: 1',
  'rfc258-file-symbols.test.ts: 1',
  'rfc259-github-ingress.test.ts: 1',
  'rfc259-webhook-github-e2e.test.ts: 1',
  'rfc260-webhook-read-visibility.test.ts: 1',
  'rfc261-webhook-delivery-pagination.test.ts: 7',
  'rfc264-unicode-names.test.ts: 1',
  'rfc266-concurrency-hot-apply.test.ts: 1',
  'rfc266-script-pool-independence.test.ts: 1',
  'rfc268-webhook-scratch-launch.test.ts: 1',
  'rfc269-code-host-connections.test.ts: 4',
  'rfc269-code-host-wiring-2026-08-10.test.ts: 2',
  'rfc269-webhook-code-host-context-e2e.test.ts: 2',
  'rfc269-webhook-trigger-context-atomicity.test.ts: 1',
  'rfc270-privileged-node-rehydrate.test.ts: 11',
  'rfc271-builtin-normalization-token.test.ts: 1',
  'rfc271-builtin-resolve.test.ts: 6',
  'rfc271-bundle-engine.test.ts: 1',
  'rfc271-bundle-recovery-hardening.test.ts: 1',
  'rfc271-export-closure-authz.test.ts: 3',
  'rfc271-export-fence-http.test.ts: 1',
  'rfc271-export-fence.test.ts: 1',
  'rfc271-export-gates.test.ts: 5',
  'rfc271-export-package.test.ts: 11',
  'rfc271-import-commit.test.ts: 25',
  'rfc271-import-http.test.ts: 3',
  'rfc271-import-preview.test.ts: 13',
  'rfc271-intent-skill-plugin-update.test.ts: 5',
  'rfc271-mcp-owner-fence.test.ts: 4',
  'rfc271-overwrite-ownership.test.ts: 1',
  'rfc271-resource-package-hardening.test.ts: 7',
  'rfc271-roundtrip.test.ts: 1',
  'rfc271-validation-contexts.test.ts: 7',
  'rfc274-workgroup-output-messages.test.ts: 1',
  'rfc275-schema-admission.test.ts: 4',
  'rfc276-readonly-script-stall-regression.test.ts: 1',
  'rfc278-legacy-schema-reconciliation.test.ts: 2',
  'rfc279-database-redundancy-cleanup.test.ts: 1',
  'rfc280-startup-verification-route.test.ts: 1',
  'rfc282-b2-resolve-injection.test.ts: 2',
  'rfc282-c1-binary-freeze.test.ts: 1',
  'rfc282-d1-acl-inline-convergence.test.ts: 2',
  'rfc282-d2-granted-ids-single-source.test.ts: 1',
  'rfc282-d4-ref-fail-open-fixes.test.ts: 1',
  'rfc284-batchc-resource-dedup.test.ts: 5',
  'rfc285-b2-delete-tier.test.ts: 3',
  'rfc285-b3-inherited-actor.test.ts: 1',
  'rfc285-b7-memory-matrix.test.ts: 10',
  'rfc287-t11-file-scheme-rejected.test.ts: 3',
  'rfc287-t13-deferred-prep.test.ts: 27',
  'rfc287-t14-file-scheme-bypasses.test.ts: 2',
  'rfc287-t14b-prep-window-blast-radius.test.ts: 1',
  'rfc291-call-edge-binding.test.ts: 1',
  'rfc291-closure-call-edges.test.ts: 1',
  'rfc291-commit-auto-mount.test.ts: 1',
  'rfc291-commit-then-update.test.ts: 1',
  'rfc291-unavailable-mount.test.ts: 1',
  'rfc293-intent-state.test.ts: 1',
  'rfc294-apply-replay-recovery-parity.test.ts: 1',
  'rfc294-background-worker-boundary.test.ts: 3',
  'rfc294-route-gate-compat.test.ts: 1',
  'rfc294-task-execution-compat-oracles.test.ts: 1',
  'rfc295-downgrade-audit.test.ts: 2',
  'rfc298-webhook-task-source-link.test.ts: 5',
  'rfc300-terminal-workspace-policy.test.ts: 1',
  'rfc300-webhook-workspace-cleanup-e2e.test.ts: 2',
  'rfc300-workspace-prune.test.ts: 1',
  'rfc301-task-launch-origin-inheritance.test.ts: 1',
  'rfc303-node-revival-fence.test.ts: 1',
  'rfc303-verified-ingress.test.ts: 1',
  'rfc304-capability-package-roundtrip.test.ts: 1',
  'rfc304-capability-templates.test.ts: 4',
  'rfc304-template-upstream.test.ts: 1',
  'rfc305-architecture-lock.test.ts: 2',
  'rfc305-guest-access.test.ts: 1',
  'rfc305-script-grant-http.test.ts: 1',
  'rfc305-user-access-integration.test.ts: 1',
  'rfc306-scheduler-branch.test.ts: 1',
  'rfc307-demo-seed.test.ts: 1',
  'rfc309-template-merge-migration.test.ts: 1',
  'rfc309-template-upstream-wiring.test.ts: 1',
  'rfc310-config-create-contract.test.ts: 1',
  'rfc310-digital-employee-authoring.test.ts: 5',
  'rfc310-digital-employee-conflict-system-mock-e2e.test.ts: 1',
  'rfc310-digital-employee-human-review-system-mock-e2e.test.ts: 1',
  'rfc310-digital-employee-system-mock-e2e.test.ts: 1',
  'rfc310-digital-employee-writer-cutover.test.ts: 4',
  'rfc310-employee-workspace-delivery.test.ts: 1',
  'rfc310-employee-workspace-repository-freshness.test.ts: 1',
  'rfc310-pr1b-config-routes-errors.test.ts: 1',
  'rfc310-pr3-journey.test.ts: 1',
  'rfc310-pr3-upload-security.test.ts: 3',
  'rfc310-pr4-execution-host.test.ts: 1',
  'rfc310-pr4-profile-identity.test.ts: 1',
  'rfc310-pr6-evidence-read.test.ts: 1',
  'rfc310-pr6-pipeline-adapter.test.ts: 1',
  'rfc310-pr7b-handover.test.ts: 1',
  'rfc310-pr9-cutover.test.ts: 5',
  'rfc310-type-package-auto-upgrade.test.ts: 12',
  'rfc311-backup-concurrency.test.ts: 1',
  'rfc311-backup-worker-fallback.test.ts: 5',
  'rfc311-badge-counts.test.ts: 3',
  'rfc311-branch-started-at-maintenance.test.ts: 2',
  'rfc311-maintenance-boot-tick.test.ts: 4',
  // W12：新增两条真实 bun:sqlite statement observer SQL/CPU 机制回归，仅此引擎提供同步仪表。
  'rfc311-perf-foundation.test.ts: 10',
  'rfc311-repos-page.test.ts: 1',
  'rfc311-retention-sweep.test.ts: 1',
  'rfc311-task-archive.test.ts: 12',
  'rfc311-task-page-fastpath.test.ts: 1',
  'rfc311-workgroup-badge-acl.test.ts: 1',
  'rfc312-default-grant.test.ts: 1',
  'rfc312-impl-gate-fixes.test.ts: 5',
  'rfc312-presence-channel.test.ts: 3',
  'rfc312-t0-upgrade-dedup.test.ts: 4',
  'rfc313-session-escalation.test.ts: 1',
  'rfc314-autokill-stall-window.test.ts: 1',
  'rfc314-event-write-batching.test.ts: 1',
  'rfc314-session-view-window.test.ts: 1',
  'rfc315-event-automation-permissions.test.ts: 1',
  'rfc317-config-resource-write-gate.test.ts: 1',
  'rfc317-cross-context-ports.test.ts: 10',
  'rfc317-employee-definition-acl.test.ts: 1',
  'rfc317-runtime-spawn-capability-guard.test.ts: 1',
  'rfc319-fusion-manifest-merge-back.test.ts: 1',
  'rfc319-ssh-repo-access.test.ts: 1',
  'rfc321-cached-repo-refresh-credential.test.ts: 1',
  'rfc321-repository-publication-system-mock-e2e.test.ts: 1',
  'rfc321-repository-publication-transport.test.ts: 6',
  'rfc321-repository-transport-credentials.test.ts: 3',
  'rfc321-repository-transport-http.test.ts: 1',
  'rfc323-platform-pipeline-collection.test.ts: 1',
  'rfc324-acl-wire-contract.test.ts: 1',
  'rfc324-grant-level-matrix.test.ts: 1',
  'rfc324-memory-editor-grant.test.ts: 1',
  'rfc324-scheduled-task-acl.test.ts: 1',
  'rfc324-task-observer.test.ts: 1',
  'rfc326-mcp-review-tools.test.ts: 1',
  'rfc326-review-comment-simplified-anchor.test.ts: 1',
  'rfc326-review-decision-batch.test.ts: 2',
  'rfc326-review-decision-transaction.test.ts: 1',
  'rfc326-tx-primitives-equivalence.test.ts: 2',
  'rfc327-memory-filter-and-facets.test.ts: 1',
  'rfc328-codehost-attempt-ledger.test.ts: 1',
  'rfc328-durable-ownership.test.ts: 1',
  'rfc329-workgroup-pending.test.ts: 3',
  'rfc330-case-list-membership-scope.test.ts: 1',
  'rfc330-case-members-ws-gate.test.ts: 1',
  'rfc330-employee-case-access.test.ts: 1',
  'rfc330-migration-backfill.test.ts: 1',
  'rfc330-tool-template-acl-matrix.test.ts: 2',
  'rfc331-task-execution-topology.test.ts: 1',
  'rfc333-migration-human-gate-operations.test.ts: 4',
  'rfc333-task-participants.test.ts: 14',
  'rfc335-oidc-git-name-migration.test.ts: 1',
  'rfc336-employee-case-advanced-migration.test.ts: 1',
  'rfc338-maintenance-slices.test.ts: 7',
  'rfc338-maintenance-status.test.ts: 2',
  'rfc338-websocket-heartbeat.test.ts: 1',
  'rfc340-review-access.test.ts: 1',
  'rfc341-committed-event-store.test.ts: 1',
  'rfc342-memory-scope-move.test.ts: 1',
  'rfc343-intent-apply-correctness.test.ts: 1',
  'rfc345-resource-acl-revalidation.test.ts: 1',
  'rfc347-identity-access-runtime.test.ts: 4',
  'rfc349-auth-caller-closure.test.ts: 2',
  'rfc349-auth-provider-contract.test.ts: 2',
  'rfc349-auth-token-audit-provider.test.ts: 1',
  'rfc349-boolean-expression-parity.test.ts: 1',
  'rfc349-call-workgroup-frozen-contract.test.ts: 1',
  'rfc349-collaboration-runtime-mechanics.test.ts: 1',
  'rfc349-daemon-provider-core.test.ts: 1',
  'rfc349-database-migration-coordinator.integration.test.ts: 3',
  'rfc349-database-operational-adapter.test.ts: 1',
  'rfc349-digital-employee-platform-tools-wiring.test.ts: 1',
  'rfc349-dual-provider-behavior-oracle.test.ts: 3',
  'rfc349-execution-contract-postgresql-adapter.test.ts: 1',
  'rfc349-execution-peripheral-provider.test.ts: 1',
  'rfc349-frozen-source-request-writes.test.ts: 1',
  'rfc349-identity-access-promise-contract.test.ts: 2',
  'rfc349-integration-provider-adapters.test.ts: 1',
  'rfc349-intent-boot-resume-authority.test.ts: 1',
  'rfc349-intent-context-authorization-binding.test.ts: 1',
  'rfc349-maintenance-disk-provider.test.ts: 1',
  'rfc349-maintenance-execution-fence.test.ts: 1',
  'rfc349-mcp-runtime-test-daemon-identity.test.ts: 2',
  'rfc349-null-ordering-parity.test.ts: 1',
  'rfc349-owner-identity-provider.test.ts: 1',
  'rfc349-postgresql-daemon-system-identity.test.ts: 1',
  'rfc349-postgresql-logical-migration.integration.test.ts: 1',
  'rfc349-provider-search-case-parity.test.ts: 1',
  'rfc349-rest-launch-ownership.test.ts: 1',
  'rfc349-safety-backup-off-thread-verify.test.ts: 1',
  'rfc349-source-control-provider-adapters.test.ts: 2',
  'rfc349-sqlite-logical-source.test.ts: 3',
  'rfc349-sqlite-migration-compatibility.test.ts: 2',
  'rfc349-task-execution-provider-adapters.test.ts: 3',
  'rfc349-task-execution-read-models-postgresql-adapter.test.ts: 1',
  'rfc349-task-transaction-participants.test.ts: 1',
  'rfc349-websocket-provider.test.ts: 1',
  'rfc350-idle-timeout-integration.test.ts: 1',
  'rfc351-sqlite-write-transaction-immediate.test.ts: 1',
  'rfc352-memory-list-page-query.test.ts: 6',
  'rfc354-clarify-idle-skip.test.ts: 1',
  'rfc354-nested-depth3-frames.test.ts: 1',
  'rfc354-nested-failure-modes.test.ts: 1',
  'rfc354-nested-frames-closure.test.ts: 1',
  'rfc354-nested-loop-frames.test.ts: 1',
  'rfc355-intent-session-event-callsites.test.ts: 1',
  'rfc357-provider-portability.test.ts: 1',
  'rfc357-task-list-authorization.test.ts: 4',
  'rfc358-intent-graph-validation.test.ts: 1',
  'rfc359-database-transaction.test.ts: 1',
  'rfc359-engine-capabilities.test.ts: 1',
  // T19h mechanisms read the actual immutable SQLite prefix before any head
  // migration. The upgrade/restore files also select real PostgreSQL cases by
  // default; this records the native sources and readonly SQLite witness.
  'rfc359-t19h-generation-upgrade.test.ts: 4',
  'rfc359-t19h-logical-backup-restore.test.ts: 1',
  'rfc359-t19h-postgresql-upgrade.integration.test.ts: 1',
  // 原同步资源包提交必须在返回前写完并可回滚；这条真 SQLite 机制判据照样精确入账。
  'rfc359-w14-agent-commit-sequence.test.ts: 1',
  // 四条原生同步 companion/CAS/回滚判据共用一处构库；十条公共写入行为仍跑双引擎。
  'rfc359-w16-task-lifecycle-write-sequence.test.ts: 1',
  'rfc359-w17-boot-orphan-terminalization.test.ts: 1',
  'rfc359-w25-task-page-bounded-prefix.test.ts: 1', // Native SQLite fallback non-consumption witness; behavior cases use both providers.
  'rfc359-w6-t26-postgresql-plan-audit.test.ts: 1',
  'rfc359-w7-catalog-composition-roots.test.ts: 1',
  // RFC-359 W8：这一格**不是**本守卫要防的那种债，但照样入账，因为判据是纯文本、不该为它开洞。
  // `rfc359-w8-logical-source-conformance.test.ts` 整份判据都跑在 `describeEachProvider` 里
  // （两个引擎各一遍）；这条 `new Database(` 在它 SQLite 能力分支的**里面**——`openSqliteLogicalSource`
  // 按**路径**开只读连接，而「冻结窗漏进一个写手、围栏必须点名」这条判据非得有第二条写连接不可，
  // PostgreSQL 那一支根本没有「文件」这个概念（它的围栏守的是活跃生成代）。
  // 用别名 / 动态 import 把它藏过文本判据是本文件注释亲口点名的绕法，所以宁可占一格。
  'rfc359-w8-logical-source-conformance.test.ts: 1',
  'routes-clarify.test.ts: 1',
  'routes-cross-clarify.test.ts: 1',
  'routes-inventory.test.ts: 1',
  'routes-memories-patch.test.ts: 1',
  'routes-memories.test.ts: 1',
  'routes-memory-distill-job-detail.test.ts: 1',
  'routes-memory-distill-jobs.test.ts: 1',
  'routes-session.test.ts: 1',
  'routes-task-feedback.test.ts: 1',
  'routes-worktree-files.test.ts: 1',
  'routes/mcps-probe.test.ts: 1',
  'runner-clarify-branch.test.ts: 1',
  'runner-envelope-followup.test.ts: 1',
  'runner-inject-snapshot-eager-write.test.ts: 1',
  'runner-injected-memories.test.ts: 1',
  'runner-inventory-integration.test.ts: 1',
  'runner-malformed-port-followup.test.ts: 1',
  'runner-output-kind-persist.test.ts: 1',
  'runner-parent-stdout-broadcast.test.ts: 1',
  'runner-permission-inject-e2e.test.ts: 1',
  'runner-port-validation-eager.test.ts: 1',
  'runner-session-id-persist.test.ts: 1',
  'runner-signal-port-in-prompt.test.ts: 1',
  'runner-subagent-live-capture.test.ts: 6',
  'runner.test.ts: 1',
  'runtime-claude-capture.test.ts: 1',
  'runtime-claude-e2e.test.ts: 1',
  'runtime-extra-args.test.ts: 3',
  'runtime-routes-registry.test.ts: 1',
  'runtime-routes.test.ts: 1',
  'runtime-session-lease.test.ts: 1',
  'scheduled-task-scheduler.test.ts: 1',
  'scheduled-tasks-acl.test.ts: 1',
  'scheduled-tasks-crud.test.ts: 1',
  'scheduled-tasks-run-now.test.ts: 2',
  'scheduled-tasks-ws.test.ts: 1',
  'scheduler-audit-gap1-limits-resume-startedat.test.ts: 1',
  'scheduler-audit-gap3-gc-terminal-statuses.test.ts: 1',
  'scheduler-audit-gap4-loop-exit-out-of-scope-port.test.ts: 1',
  'scheduler-audit-s02-multirepo-retry-rollback-noop.test.ts: 1',
  'scheduler-audit-s04-git-wrapper-cumulative-diff.test.ts: 1',
  'scheduler-audit-s05-fanout-inner-chain.test.ts: 3',
  'scheduler-audit-s07-s28-wrapper-consumed-status.test.ts: 1',
  'scheduler-audit-s08-runtask-no-cas-revival.test.ts: 1',
  'scheduler-audit-s10-async-transaction-decorative.test.ts: 1',
  'scheduler-audit-s17-readonly-starved-by-writer-queue.test.ts: 1',
  'scheduler-audit-s18-s19-fanout-failure-semantics.test.ts: 1',
  'scheduler-audit-s21-fanout-aggregator-idempotency.test.ts: 1',
  'scheduler-audit-s22-canceled-retry-stall.test.ts: 2',
  'scheduler-boundary-canceled-fanout-status.test.ts: 1',
  'scheduler-boundary-fanout-concurrency.test.ts: 1',
  'scheduler-boundary-fanout-resume-duplicate-shards.test.ts: 1',
  'scheduler-boundary-fanout-shardkey-collision.test.ts: 1',
  'scheduler-boundary-intra-loop-cycle-stall.test.ts: 1',
  'scheduler-boundary-loop-exhausted-resume.test.ts: 1',
  'scheduler-boundary-presnapshot-rollback-skip.test.ts: 1',
  'scheduler-boundary-resume-retryindex-vs-id.test.ts: 1',
  'scheduler-boundary-wrapper-resume-interrupted.test.ts: 1',
  'scheduler-clarify-dispatch.test.ts: 1',
  'scheduler-clarify-inline.test.ts: 1',
  'scheduler-clarify-mid-batch.test.ts: 1',
  'scheduler-clarify-multiround-aging.test.ts: 1',
  'scheduler-commit-push.test.ts: 1',
  'scheduler-cross-clarify-dispatch.test.ts: 1',
  'scheduler-cross-clarify-no-runaway.test.ts: 2',
  'scheduler-default-retries.test.ts: 1',
  'scheduler-depends-closure.test.ts: 1',
  'scheduler-envelope-followup-integration.test.ts: 1',
  'scheduler-envelope-followup-rfc039.test.ts: 1',
  'scheduler-node-overrides.test.ts: 1',
  'scheduler-port-validation-followup-integration.test.ts: 1',
  'scheduler-rfc040-wrapper-await.test.ts: 1',
  'scheduler-wrapper-fanout-e2e.test.ts: 1',
  'scheduler-wrapper-scope-dependencies.test.ts: 1',
  'scheduler.test.ts: 1',
  'session-capture-sqlite.test.ts: 4',
  'sessions.test.ts: 1',
  'skill-file-symlink-containment.test.ts: 1',
  'skill-identity-migration.test.ts: 3',
  'skill-main-file-guard.test.ts: 1',
  'skill-version-owner-fence.test.ts: 3',
  'skill-zip-commit.test.ts: 1',
  'skills-import-zip-http.test.ts: 1',
  'skills.test.ts: 1',
  'sqlite-concurrency-fuzz.test.ts: 3',
  'start-task-deps.test.ts: 2',
  'start-task-multi-repo-gates.test.ts: 1',
  'start-task-url.test.ts: 1',
  'structural-diff-callchain-multi-repo.test.ts: 1',
  'structural-diff-node-multi-repo.test.ts: 1',
  'subagent-live-capture-source.test.ts: 1',
  'subagent-live-capture.test.ts: 4',
  'task-collab-launch.test.ts: 1',
  'task-diff-multi-repo-truncation.test.ts: 1',
  'task-diff-multi-repo.test.ts: 1',
  'task-file-content.test.ts: 4',
  'task-launch-gate.test.ts: 1',
  'task-start-git-identity.test.ts: 1',
  'task-start-pre-worktree.test.ts: 1',
  'task-start-working-branch.test.ts: 1',
  'tasks-create-name.test.ts: 1',
  'tasks-multipart.test.ts: 1',
  'tasks-visibility.test.ts: 1',
  'tasks.test.ts: 1',
  'terminal-maintenance-watermark-coverage.test.ts: 2',
  'transition-cas-route-409.test.ts: 2',
  'upgrade-rolling.test.ts: 7',
  'users-http.test.ts: 1',
  'users-service.test.ts: 1',
  'webhook-trigger-digital-employee-validation.test.ts: 1',
  'webhook-trigger-validation-acl-order.test.ts: 1',
  'wg-readonly-claim-and-pause-reason.test.ts: 1',
  'workflows.test.ts: 2',
  'workgroup-host-output-isolation.test.ts: 1',
  'worktree-files-acl.test.ts: 1',
  'worktree-files-proxy.test.ts: 1',
  'ws-auth-multi-token.test.ts: 1',
  'ws-repo-imports.test.ts: 1',
  'ws.test.ts: 1',
]

/**
 * 「在测试里直接造一个 SQLite 库」的两种写法。**两种都要数**：
 *
 *   - `createInMemoryDb(` —— 仓内的测试夹具工厂，绝大多数单引擎判据走这条；
 *   - `new Database(` —— 直接用 `bun:sqlite`，**绕过夹具**。
 *
 * 判据初版只数前一条，于是后一条整类在网外：实测（RFC-359 W7，2026-09-07）非迁移测试里
 * 还有 95 处 / 55 个文件走 `new Database(`，它们写出来的判据同样只验证 SQLite，
 * 而守卫一声不吭。**只堵一个入口的守卫等于没堵**——想绕的人（或者只是不知道夹具存在的人）
 * 自然会落到另一个入口上。
 *
 * 迁移测试（`migration-*.test.ts`）**不豁免**，口径与既有账本保持一致：它们本来就有 46 条
 * `createInMemoryDb` 记在账上。迁移 DDL 确实只对 SQLite 有意义（PostgreSQL 的 schema 来自
 * drizzle 声明，见 `rfc359-w5-t19g-schema-contract-reconciliation.test.ts`），但那是「这条债
 * 为什么合理」的理由，不是「不必计数」的理由——高水位账本记的是存量，不是过错。
 */
const SINGLE_ENGINE_CONSTRUCTION = /\bcreateInMemoryDb\(|\bnew Database\(/g

let cachedRows: readonly string[] | undefined

/**
 * `<路径>: <调用点数>`，字典序。整棵树只读一遍并缓存——全树源码扫描类守卫不缓存的话，
 * 每个用例都重读一遍，CI 上按秒累加（`docs/dev-gotchas.md` 记过这条）。
 */
function callSiteRows(): readonly string[] {
  if (cachedRows !== undefined) return cachedRows
  const rows: string[] = []
  for (const rel of CORPUS_FILES) {
    if (EXEMPT.has(rel)) continue
    const hits = (readFileSync(join(TESTS, rel), 'utf8').match(SINGLE_ENGINE_CONSTRUCTION) ?? [])
      .length
    if (hits > 0) rows.push(`${rel}: ${hits}`)
  }
  cachedRows = rows.sort()
  return cachedRows
}

describe('RFC-359 W5-T19f —— 测试不得写死引擎（高水位，只降不升）', () => {
  test('语料非空：确实扫到了整棵 backend 测试树（扫成 0 说明扫描根失效，此刻零预言力）', () => {
    expect(CORPUS_FILES.length).toBeGreaterThanOrEqual(1_500)
  }, 30_000)

  test('逐文件调用点数与账本逐字相等（增了是新的单引擎判据，减了是收敛，都要改账本）', () => {
    expect(
      [...callSiteRows()],
      '直接建 SQLite 库的测试调用点数与账本不符（`createInMemoryDb(` 与 `new Database(` 合计）。' +
        '**增**了说明有人又写了一条**只验证 SQLite** 的判据——PostgreSQL 侧的同一段实现因此零行为覆盖，' +
        '正是 dual-provider-parity-audit-2026-09-04 里 12 条 P0 穿过全部验收的那个机制。' +
        '改用双引擎 harness：`describeEachProvider(name, (harness) => ...)`，库取 `harness.db`' +
        '（事务面取 `harness.session`，要按引擎分叉就看 `harness.capabilities`）。' +
        '确有理由只跑单引擎，就把新增写进账本并在那一行旁写清为什么。' +
        '**减**了说明迁移发生了——把账本一起改小，让这次减少留下一次有署名的提交记录。',
    ).toEqual([...TEST_ENGINE_HARDCODING_DEBT])
  }, 30_000)

  test('账本按路径字典序、无重复（清点稳定的前提）', () => {
    const paths = TEST_ENGINE_HARDCODING_DEBT.map((row) => row.slice(0, row.lastIndexOf(':')))
    expect(new Set(paths).size, '账本里有重复路径').toBe(paths.length)
    expect([...paths].sort(), '账本没有按路径字典序排列').toEqual(paths)
  }, 30_000)
})
