// RFC-349 T4 — deterministic PostgreSQL baseline projection. SQLite migration
// SQL is never replayed: the canonical logical contract produces a fresh PG
// schema, with constraints/indexes applied after logical copy.

import { createHash } from 'node:crypto'
import {
  buildLogicalSchemaContract,
  canonicalSchemaJson,
  type LogicalColumnContract,
  type LogicalSchemaContract,
  type LogicalTableContract,
} from './schemaContract'

export const POSTGRESQL_APPLICATION_SCHEMA = 'agent_workflow'
export const POSTGRESQL_METADATA_SCHEMA = 'agent_workflow_meta'
export const POSTGRESQL_BASELINE_ID = '0000_rfc349_baseline_v1'

export interface PostgresqlSchemaStatement {
  readonly kind: 'bootstrap' | 'table' | 'constraint' | 'index' | 'metadata'
  readonly logicalId: string
  readonly sql: string
}

export interface PostgresqlSchemaPlan {
  readonly version: 1
  readonly baselineId: typeof POSTGRESQL_BASELINE_ID
  readonly contractDigest: string
  readonly activeTableCount: number
  readonly archiveOnlyTableCount: number
  readonly statements: readonly PostgresqlSchemaStatement[]
  readonly digest: string
}

export class PostgresqlSchemaProjectionError extends Error {
  constructor(message: string) {
    super(message)
    this.name = 'PostgresqlSchemaProjectionError'
  }
}

function quote(identifier: string): string {
  return `"${identifier.replaceAll('"', '""')}"`
}

function boundedIdentifier(identifier: string): string {
  if (Buffer.byteLength(identifier, 'utf8') <= 63) return identifier
  const digest = createHash('sha256').update(identifier).digest('hex').slice(0, 12)
  let prefix = identifier
  while (Buffer.byteLength(`${prefix}_${digest}`, 'utf8') > 63) prefix = prefix.slice(0, -1)
  return `${prefix}_${digest}`
}

function qualifiedTable(table: string): string {
  return `${quote(POSTGRESQL_APPLICATION_SCHEMA)}.${quote(table)}`
}

function columnSql(column: LogicalColumnContract): string {
  const pieces = [quote(column.name), column.providerType.postgresql.toUpperCase()]
  if (column.providerType.postgresql === 'text') pieces.push('COLLATE "C"')
  if (column.identity) pieces.push('GENERATED BY DEFAULT AS IDENTITY')
  if (!column.nullable) pieces.push('NOT NULL')
  if (column.providerDefault.postgresql !== null && !column.identity) {
    pieces.push(`DEFAULT ${column.providerDefault.postgresql}`)
  }
  return pieces.join(' ')
}

function localExpression(table: LogicalTableContract, input: string): string {
  let expression = input.replaceAll(`${quote(table.id)}.`, '')
  expression = expression.replace(
    /("[^"]+")\s+NOT\s+GLOB\s+'\*\[\^0-9a-f\]\*'/gi,
    "$1 !~ '[^0-9a-f]'",
  )
  expression = expression.replace(/("[^"]+")\s+IS\s+NOT\s+("[^"]+")/gi, '$1 IS DISTINCT FROM $2')
  for (const column of table.columns.filter((candidate) => candidate.logicalCodec === 'boolean')) {
    const name = quote(column.name).replaceAll(/[.*+?^${}()|[\]\\]/g, '\\$&')
    expression = expression
      .replaceAll(new RegExp(`(${name})\\s*=\\s*1\\b`, 'gi'), '$1 = TRUE')
      .replaceAll(new RegExp(`(${name})\\s*=\\s*0\\b`, 'gi'), '$1 = FALSE')
      .replaceAll(new RegExp(`(${name})\\s*<>\\s*1\\b`, 'gi'), '$1 <> TRUE')
      .replaceAll(new RegExp(`(${name})\\s*<>\\s*0\\b`, 'gi'), '$1 <> FALSE')
      .replaceAll(
        new RegExp(`(${name})\\s+IN\\s*\\(\\s*0\\s*,\\s*1\\s*\\)`, 'gi'),
        '$1 IN (FALSE, TRUE)',
      )
  }
  if (/\bGLOB\b|\bunixepoch\s*\(|\brandomblob\s*\(/i.test(expression)) {
    throw new PostgresqlSchemaProjectionError(`unmapped SQLite expression in ${table.id}: ${input}`)
  }
  return expression
}

function renderIndexColumn(table: LogicalTableContract, input: string): string {
  if (/^[A-Za-z_][A-Za-z0-9_]*$/.test(input)) return quote(input)
  return localExpression(table, input)
}

function action(value: string): string {
  const normalized = value.toUpperCase()
  if (!['NO ACTION', 'RESTRICT', 'CASCADE', 'SET NULL', 'SET DEFAULT'].includes(normalized)) {
    throw new PostgresqlSchemaProjectionError(`unsupported foreign-key action ${value}`)
  }
  return normalized
}

function compatibilityStatements(): PostgresqlSchemaStatement[] {
  const bootstrap = (logicalId: string, sql: string): PostgresqlSchemaStatement => ({
    kind: 'bootstrap',
    logicalId,
    sql,
  })
  return [
    bootstrap(
      'application-schema',
      `CREATE SCHEMA IF NOT EXISTS ${quote(POSTGRESQL_APPLICATION_SCHEMA)}`,
    ),
    bootstrap(
      'metadata-schema',
      `CREATE SCHEMA IF NOT EXISTS ${quote(POSTGRESQL_METADATA_SCHEMA)}`,
    ),
    bootstrap(
      'unixepoch',
      `CREATE OR REPLACE FUNCTION ${quote(POSTGRESQL_APPLICATION_SCHEMA)}.unixepoch() RETURNS BIGINT LANGUAGE SQL VOLATILE AS $$ SELECT extract(epoch from clock_timestamp())::bigint $$`,
    ),
    bootstrap(
      'instr',
      `CREATE OR REPLACE FUNCTION ${quote(POSTGRESQL_APPLICATION_SCHEMA)}.instr(value TEXT, needle TEXT) RETURNS BIGINT LANGUAGE SQL IMMUTABLE STRICT AS $$ SELECT strpos(value, needle)::bigint $$`,
    ),
    bootstrap(
      'hex-text',
      `CREATE OR REPLACE FUNCTION ${quote(POSTGRESQL_APPLICATION_SCHEMA)}.hex(value TEXT) RETURNS TEXT LANGUAGE SQL IMMUTABLE STRICT AS $$ SELECT encode(convert_to(value, 'UTF8'), 'hex') $$`,
    ),
    bootstrap(
      'hex-bytea',
      `CREATE OR REPLACE FUNCTION ${quote(POSTGRESQL_APPLICATION_SCHEMA)}.hex(value BYTEA) RETURNS TEXT LANGUAGE SQL IMMUTABLE STRICT AS $$ SELECT encode(value, 'hex') $$`,
    ),
    bootstrap(
      'max-bigint',
      `CREATE OR REPLACE FUNCTION ${quote(POSTGRESQL_APPLICATION_SCHEMA)}.max(left_value BIGINT, right_value BIGINT) RETURNS BIGINT LANGUAGE SQL IMMUTABLE STRICT AS $$ SELECT greatest(left_value, right_value) $$`,
    ),
    bootstrap(
      'json-valid',
      `CREATE OR REPLACE FUNCTION ${quote(POSTGRESQL_APPLICATION_SCHEMA)}.json_valid(value TEXT) RETURNS BOOLEAN LANGUAGE plpgsql IMMUTABLE STRICT AS $$ BEGIN PERFORM value::jsonb; RETURN TRUE; EXCEPTION WHEN others THEN RETURN FALSE; END $$`,
    ),
    bootstrap(
      'json-type',
      `CREATE OR REPLACE FUNCTION ${quote(POSTGRESQL_APPLICATION_SCHEMA)}.json_type(value TEXT, path TEXT) RETURNS TEXT LANGUAGE plpgsql IMMUTABLE STRICT AS $$ DECLARE item jsonb; BEGIN IF path !~ '^\\$\\.[A-Za-z_][A-Za-z0-9_]*$' THEN RETURN NULL; END IF; item := value::jsonb -> substring(path from 3); IF item IS NULL THEN RETURN NULL; END IF; RETURN jsonb_typeof(item); EXCEPTION WHEN others THEN RETURN NULL; END $$`,
    ),
    bootstrap(
      'json-extract',
      `CREATE OR REPLACE FUNCTION ${quote(POSTGRESQL_APPLICATION_SCHEMA)}.json_extract(value TEXT, path TEXT) RETURNS TEXT LANGUAGE plpgsql IMMUTABLE STRICT AS $$ DECLARE item jsonb; BEGIN IF path !~ '^\\$\\.[A-Za-z_][A-Za-z0-9_]*$' THEN RETURN NULL; END IF; item := value::jsonb -> substring(path from 3); IF item IS NULL THEN RETURN NULL; END IF; IF jsonb_typeof(item) = 'string' THEN RETURN item #>> '{}'; END IF; RETURN item::text; EXCEPTION WHEN others THEN RETURN NULL; END $$`,
    ),
  ]
}

function tableStatements(contract: LogicalSchemaContract): PostgresqlSchemaStatement[] {
  return contract.tables
    .filter((table) => table.disposition !== 'ARCHIVE_THEN_OMIT')
    .map((table) => ({
      kind: 'table' as const,
      logicalId: table.id,
      sql: `CREATE TABLE ${qualifiedTable(table.id)} (\n  ${[
        ...table.columns.map(columnSql),
        `CONSTRAINT ${quote(boundedIdentifier(`${table.id}_pkey`))} PRIMARY KEY (${table.primaryKey.map(quote).join(', ')})`,
      ].join(',\n  ')}\n)`,
    }))
}

function constraintStatements(contract: LogicalSchemaContract): PostgresqlSchemaStatement[] {
  const statements: PostgresqlSchemaStatement[] = []
  for (const table of contract.tables.filter(
    (candidate) => candidate.disposition !== 'ARCHIVE_THEN_OMIT',
  )) {
    const indexNames = new Set(table.indexes.map((index) => index.name))
    for (const unique of table.unique.filter((constraint) => !indexNames.has(constraint.name))) {
      statements.push({
        kind: 'constraint',
        logicalId: `${table.id}:unique:${unique.name}`,
        sql: `ALTER TABLE ${qualifiedTable(table.id)} ADD CONSTRAINT ${quote(boundedIdentifier(unique.name))} UNIQUE (${unique.columns.map(quote).join(', ')})`,
      })
    }
    for (const column of table.columns.filter((candidate) => candidate.uniqueName !== null)) {
      statements.push({
        kind: 'constraint',
        logicalId: `${table.id}:unique:${column.uniqueName}`,
        sql: `ALTER TABLE ${qualifiedTable(table.id)} ADD CONSTRAINT ${quote(boundedIdentifier(column.uniqueName!))} UNIQUE (${quote(column.name)})`,
      })
    }
    for (const check of table.checks) {
      if (check.expression === null) continue
      statements.push({
        kind: 'constraint',
        logicalId: `${table.id}:check:${check.name}`,
        sql: `ALTER TABLE ${qualifiedTable(table.id)} ADD CONSTRAINT ${quote(boundedIdentifier(check.name))} CHECK (${localExpression(table, check.expression)})`,
      })
    }
    for (const foreignKey of table.foreignKeys) {
      statements.push({
        kind: 'constraint',
        logicalId: `${table.id}:fk:${foreignKey.name}`,
        sql: `ALTER TABLE ${qualifiedTable(table.id)} ADD CONSTRAINT ${quote(boundedIdentifier(foreignKey.name))} FOREIGN KEY (${foreignKey.columns.map(quote).join(', ')}) REFERENCES ${qualifiedTable(foreignKey.foreignTable)} (${foreignKey.foreignColumns.map(quote).join(', ')}) ON UPDATE ${action(foreignKey.onUpdate)} ON DELETE ${action(foreignKey.onDelete)}`,
      })
    }
  }
  return statements
}

function indexStatements(contract: LogicalSchemaContract): PostgresqlSchemaStatement[] {
  const statements: PostgresqlSchemaStatement[] = []
  for (const table of contract.tables.filter(
    (candidate) => candidate.disposition !== 'ARCHIVE_THEN_OMIT',
  )) {
    for (const index of table.indexes) {
      statements.push({
        kind: 'index',
        logicalId: `${table.id}:index:${index.name}`,
        sql: `CREATE ${index.unique ? 'UNIQUE ' : ''}INDEX ${quote(boundedIdentifier(index.name))} ON ${qualifiedTable(table.id)} (${index.columns.map((column) => renderIndexColumn(table, column)).join(', ')})${index.where === null ? '' : ` WHERE ${localExpression(table, index.where)}`}`,
      })
    }
  }
  return statements
}

function metadataStatements(contract: LogicalSchemaContract): PostgresqlSchemaStatement[] {
  return [
    {
      kind: 'metadata',
      logicalId: 'migration-table',
      sql: `CREATE TABLE ${quote(POSTGRESQL_METADATA_SCHEMA)}.${quote('schema_migrations')} (baseline_id TEXT PRIMARY KEY, contract_digest TEXT NOT NULL, plan_digest TEXT NOT NULL, applied_at BIGINT NOT NULL)`,
    },
    {
      kind: 'metadata',
      logicalId: 'contract-table',
      sql: `CREATE TABLE ${quote(POSTGRESQL_METADATA_SCHEMA)}.${quote('schema_contract')} (singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton), contract_digest TEXT NOT NULL, active_table_count BIGINT NOT NULL, archive_only_table_count BIGINT NOT NULL)`,
    },
    {
      kind: 'metadata',
      logicalId: 'contract-row',
      sql: `INSERT INTO ${quote(POSTGRESQL_METADATA_SCHEMA)}.${quote('schema_contract')} (singleton, contract_digest, active_table_count, archive_only_table_count) VALUES (TRUE, '${contract.digest}', ${contract.activeTableCount}, ${contract.archiveOnlyTableCount})`,
    },
    {
      kind: 'metadata',
      logicalId: 'logical-copy-operations',
      sql: `CREATE TABLE ${quote(POSTGRESQL_METADATA_SCHEMA)}.${quote('logical_copy_operations')} (operation_id TEXT PRIMARY KEY, source_generation_id TEXT NOT NULL, contract_digest TEXT NOT NULL, plan_digest TEXT NOT NULL, stage TEXT NOT NULL CHECK (stage IN ('prepared', 'copying', 'verified', 'activated', 'finalized')), created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL)`,
    },
    {
      kind: 'metadata',
      logicalId: 'logical-copy-chunks',
      sql: `CREATE TABLE ${quote(POSTGRESQL_METADATA_SCHEMA)}.${quote('logical_copy_chunks')} (operation_id TEXT NOT NULL REFERENCES ${quote(POSTGRESQL_METADATA_SCHEMA)}.${quote('logical_copy_operations')} (operation_id) ON DELETE RESTRICT, table_id TEXT NOT NULL, chunk_index BIGINT NOT NULL, chunk_digest TEXT NOT NULL, row_count BIGINT NOT NULL, first_key_json TEXT, last_key_json TEXT, committed_at BIGINT NOT NULL, PRIMARY KEY (operation_id, table_id, chunk_index))`,
    },
    {
      kind: 'metadata',
      logicalId: 'database-generations',
      sql: `CREATE TABLE ${quote(POSTGRESQL_METADATA_SCHEMA)}.${quote('database_generations')} (generation_id TEXT PRIMARY KEY, operation_id TEXT NOT NULL REFERENCES ${quote(POSTGRESQL_METADATA_SCHEMA)}.${quote('logical_copy_operations')} (operation_id) ON DELETE RESTRICT, source_generation_id TEXT NOT NULL, contract_digest TEXT NOT NULL, state TEXT NOT NULL CHECK (state IN ('prepared', 'active', 'retired')), activated_at BIGINT, first_live_write_at BIGINT)`,
    },
  ]
}

export function buildPostgresqlSchemaPlan(
  contract: LogicalSchemaContract = buildLogicalSchemaContract(),
): PostgresqlSchemaPlan {
  const statements = [
    ...compatibilityStatements(),
    ...tableStatements(contract),
    ...indexStatements(contract),
    ...constraintStatements(contract),
    ...metadataStatements(contract),
  ]
  const withoutDigest = {
    version: 1 as const,
    baselineId: POSTGRESQL_BASELINE_ID as typeof POSTGRESQL_BASELINE_ID,
    contractDigest: contract.digest,
    activeTableCount: contract.activeTableCount,
    archiveOnlyTableCount: contract.archiveOnlyTableCount,
    statements,
  }
  return {
    ...withoutDigest,
    digest: `sha256:${createHash('sha256').update(canonicalSchemaJson(withoutDigest)).digest('hex')}`,
  }
}

export function renderPostgresqlBaselineSql(plan: PostgresqlSchemaPlan): string {
  return `${plan.statements
    .map(
      (statement) =>
        `-- ${statement.kind}: ${statement.logicalId}\n${statement.sql.replaceAll(/;\s*$/g, '')};`,
    )
    .join('\n\n')}\n`
}
