// P-5-07 — happy-path e2e: daemon ↑ → login → workflow detail → launch task
// → wait for it to finish → assert outputs panel + node-detail drawer.
//
// The DAG itself is set up via the REST API so the test isn't exposed to
// xyflow drag-and-drop flakiness. The browser path covers what users
// actually click through: /auth, the workflow list, the launcher form, and
// the task detail page.

import { test, expect, type Page } from '@playwright/test'
import { execSync } from 'node:child_process'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

import { startDaemon, type DaemonHandle } from './harness'

interface CreatedFixtures {
  workflowId: string
  workflowName: string
  agentName: string
  repoPath: string
}

let daemon: DaemonHandle
let repoDir: string
let fixtures: CreatedFixtures

test.beforeAll(async () => {
  daemon = await startDaemon()

  // Build a throwaway git repo for the launcher. The daemon clones it into
  // a worktree at task launch time; the stub agent never reads it but the
  // git plumbing in scheduler.ts asserts the worktree exists with a HEAD.
  repoDir = mkdtempSync(join(tmpdir(), 'aw-e2e-repo-'))
  writeFileSync(join(repoDir, 'README.md'), '# e2e fixture repo\n', 'utf-8')
  execSync('git init -b main -q', { cwd: repoDir })
  execSync('git config user.email e2e@example.com', { cwd: repoDir })
  execSync('git config user.name e2e', { cwd: repoDir })
  execSync('git add .', { cwd: repoDir })
  execSync('git commit -qm initial', { cwd: repoDir })

  fixtures = await setupViaApi(daemon, repoDir)
})

test.afterAll(async () => {
  try {
    rmSync(repoDir, { recursive: true, force: true })
  } catch {
    // ignore
  }
  if (daemon !== undefined) await daemon.stop()
})

async function setupViaApi(d: DaemonHandle, repoPath: string): Promise<CreatedFixtures> {
  const headers = {
    Authorization: `Bearer ${d.token}`,
    'Content-Type': 'application/json',
  }
  const agentName = 'e2e-stub-coder'
  const agentRes = await fetch(`${d.baseUrl}/api/agents`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: agentName,
      description: 'e2e stub agent — outputs are produced by stub-opencode.sh',
      outputs: ['answer'],
      readonly: true,
      bodyMd: 'Echo back the topic prompt; the stub binary returns a fixed envelope anyway.',
    }),
  })
  expectOk(agentRes, 'create agent')

  const workflowName = 'e2e-happy-path'
  const workflowRes = await fetch(`${d.baseUrl}/api/workflows`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: workflowName,
      description: 'Generated by Playwright e2e (P-5-07).',
      definition: {
        $schema_version: 1,
        inputs: [{ kind: 'text', key: 'topic', label: 'Topic', required: true }],
        nodes: [
          { id: 'in_1', kind: 'input', inputKey: 'topic', position: { x: 0, y: 0 } },
          {
            id: 'agent_1',
            kind: 'agent-single',
            agentName,
            promptTemplate: 'Explain {{topic}} briefly.',
            position: { x: 320, y: 0 },
          },
          {
            id: 'out_1',
            kind: 'output',
            ports: [{ name: 'answer', bind: { nodeId: 'agent_1', portName: 'answer' } }],
            position: { x: 640, y: 0 },
          },
        ],
        edges: [
          {
            id: 'e_in_agent',
            source: { nodeId: 'in_1', portName: 'topic' },
            target: { nodeId: 'agent_1', portName: 'topic' },
          },
          {
            id: 'e_agent_out',
            source: { nodeId: 'agent_1', portName: 'answer' },
            target: { nodeId: 'out_1', portName: 'answer' },
          },
        ],
      },
    }),
  })
  expectOk(workflowRes, 'create workflow')
  const workflow = (await workflowRes.json()) as { id: string }

  return { workflowId: workflow.id, workflowName, agentName, repoPath }
}

function expectOk(res: Response, what: string): void {
  if (!res.ok) {
    throw new Error(`e2e setup: ${what} failed: HTTP ${res.status}`)
  }
}

async function pollUntilTerminal(
  d: DaemonHandle,
  taskId: string,
  timeoutMs: number,
): Promise<{ status: string }> {
  const terminal = new Set(['done', 'failed', 'canceled', 'interrupted', 'exhausted'])
  const deadline = Date.now() + timeoutMs
  let last: { status: string } = { status: 'pending' }
  while (Date.now() < deadline) {
    const res = await fetch(`${d.baseUrl}/api/tasks/${taskId}`, {
      headers: { Authorization: `Bearer ${d.token}` },
    })
    if (res.ok) {
      last = (await res.json()) as { status: string }
      if (terminal.has(last.status)) return last
    }
    await new Promise((r) => setTimeout(r, 500))
  }
  throw new Error(
    `task ${taskId} did not reach terminal status in ${timeoutMs}ms; last=${last.status}`,
  )
}

async function primeAuthLocalStorage(page: Page, d: DaemonHandle): Promise<void> {
  // Stamp localStorage before the SPA mounts so the auth gate redirects
  // straight through. Same shape as /auth's submit handler writes.
  await page.addInitScript(
    ({ baseUrl, token }) => {
      try {
        window.localStorage.setItem('agent-workflow.baseUrl', baseUrl)
        window.localStorage.setItem('agent-workflow.token', token)
        // Force English so the test selectors line up with en-US strings.
        window.localStorage.setItem('aw-language', 'en-US')
      } catch {
        // ignore — shouldn't fail in chromium
      }
    },
    { baseUrl: d.baseUrl, token: d.token },
  )
}

test('happy path: agents → workflow → launch → task done → outputs visible', async ({ page }) => {
  await primeAuthLocalStorage(page, daemon)

  // 1. Landing — after RFC-032 PR3, `/` renders the task-driven Homepage
  // rather than auto-redirecting to /agents. We explicitly navigate.
  await page.goto(`${daemon.baseUrl}/agents`)
  await expect(page.getByRole('heading', { name: 'Agents', exact: true })).toBeVisible()
  await expect(page.getByText(fixtures.agentName)).toBeVisible()

  // 2. Workflow editor — confirm the row is there, then open it via the link.
  await page.getByRole('link', { name: 'Workflows', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Workflows', exact: true })).toBeVisible()
  const openLink = page
    .getByRole('row', { name: new RegExp(fixtures.workflowName) })
    .getByRole('link', { name: /open/i })
  await openLink.click()
  await expect(page.getByRole('heading', { name: fixtures.workflowName })).toBeVisible()

  // 3. Launcher. Editor's launch trigger is now a <button> (it runs the
  // workflow validator on click and only navigates when ok — see
  // src/routes/workflows.edit.tsx). The role-based lookup must follow.
  await page.getByRole('button', { name: /launch task/i }).click()
  // RFC-165: the editor deep-links into the /tasks/new wizard with the
  // workflow pre-picked, landing on Step 2 (workspace).
  await expect(page.getByTestId('task-wizard')).toBeVisible()

  // Step 2 — the repo row is URL-only; feed the fixture repo as a file:// URL.
  await page.fill('[data-testid="repo-source-url-0"]', pathToFileURL(fixtures.repoPath).href)
  await page.fill('[data-testid="repo-source-ref-0"]', 'main')
  await page.getByTestId('stepper-next').click()

  // Step 3 — task name + declared inputs.
  await page.fill('[data-testid="wizard-task-name"]', 'e2e-launch-task')
  const topicInput = page
    .locator('label.form-field', { hasText: 'Topic (topic)' })
    .locator('input.form-input')
  await expect(topicInput).toBeVisible({ timeout: 10_000 })
  await topicInput.fill('e2e-test')
  await page.getByTestId('stepper-next').click()

  // Step 4 — confirm + launch.
  await page.getByRole('button', { name: 'Start task', exact: true }).click()

  // 4. Task detail page — URL changes to /tasks/<id>.
  await page.waitForURL(/\/tasks\/[A-Z0-9]{26}/i, { timeout: 15_000 })

  // 5. Wait for the task to terminate. Poll the API rather than scraping
  // the DOM so transient states aren't mistaken for the final one.
  const taskUrl = page.url()
  const taskId = taskUrl.match(/\/tasks\/([A-Z0-9]+)/i)![1]
  const finalTask = await pollUntilTerminal(daemon, taskId, 30_000)
  expect(finalTask.status).toBe('done')

  // 6. node_run outputs should include the stub's port=answer value.
  const nodeRunsRes = await fetch(`${daemon.baseUrl}/api/tasks/${taskId}/node-runs`, {
    headers: { Authorization: `Bearer ${daemon.token}` },
  })
  expect(nodeRunsRes.ok).toBeTruthy()
  const nodeRuns = (await nodeRunsRes.json()) as {
    runs: { nodeId: string; status: string }[]
    outputs: { nodeRunId: string; port: string; value: string }[]
  }
  const agentRun = nodeRuns.runs.find((r) => r.nodeId === 'agent_1')
  expect(agentRun?.status).toBe('done')
  const answerOutput = nodeRuns.outputs.find((o) => o.port === 'answer')
  expect(answerOutput?.value).toBe('stub e2e output')

  // 7. The UI eventually mirrors that: status chip + output panel value.
  //
  // The frontend polls /api/tasks/:id/node-runs every 3s and refreshes on
  // WebSocket task-update events. Under CI load the page sometimes lands on
  // /tasks/:id after the daemon has already finished and the WS event
  // arrived; we then depend on the polling fallback, which can leave the
  // outputs panel un-rendered for up to two intervals. Force a fresh fetch
  // by reloading the page now that step 6 confirmed the outputs are in the
  // API — this turns a previously-flaky timing race into a deterministic
  // assertion (RFC-004 CI run 25915917054 caught the prior 1-flaky case).
  await page.reload()
  await expect(page.locator('.status-chip', { hasText: /^done$/i }).first()).toBeVisible({
    timeout: 15_000,
  })
  // RFC-021: outputs now live inside the Outputs tab on the task detail
  // page (default tab is Workflow status). Click the tab before asserting
  // the output card is visible. The tab itself only renders when
  // `collectPorts(workflowSnapshot).length > 0`, so its appearance also
  // doubles as a smoke check for hasOutputs detection.
  await page.locator('.task-detail__tab-bar [role="tab"]', { hasText: /Outputs|输出/ }).click()
  // RFC-072: the Outputs tab is now a two-pane browser; the selected port's
  // value renders in .task-outputs-panel__pre (single declared port → selected
  // by default). Replaces the old per-card .task-output-card__body.
  await expect(
    page.locator('.task-outputs-panel__pre', { hasText: 'stub e2e output' }),
  ).toBeVisible({ timeout: 15_000 })

  // 8. RFC-006 visual contract: every port label is rendered INSIDE the
  // bounding rectangle of its containing .canvas-node. The old strip-of-
  // chips layout pushed labels onto a -6px sidebar that overlapped the
  // node body and bled past its left/right edges; we lock that out here
  // in the task-detail canvas (same WorkflowCanvas as the editor, read-
  // only mode).
  //
  // RFC-021: step 7 left us on the Outputs tab (canvas pane is hidden via
  // [hidden] → display:none). Switch back to Workflow status so the canvas
  // is in the live layout tree before geometry assertions run.
  await page
    .locator('.task-detail__tab-bar [role="tab"]', { hasText: /Workflow status|工作流状态/ })
    .click()
  await expect(page.locator('.canvas-node__port-label').first()).toBeVisible({ timeout: 10_000 })
  const labelFit = await page.evaluate(() => {
    const labels = Array.from(document.querySelectorAll('.canvas-node__port-label'))
    const offenders: { port: string; reason: string }[] = []
    for (const label of labels) {
      const node = label.closest('.canvas-node')
      if (node === null) {
        offenders.push({ port: label.textContent ?? '?', reason: 'no .canvas-node ancestor' })
        continue
      }
      const lr = label.getBoundingClientRect()
      const nr = node.getBoundingClientRect()
      // Allow 1px sub-pixel slack on each side; xyflow's zoom rounding
      // occasionally yields fractional bleed of less than a pixel.
      if (lr.left < nr.left - 1 || lr.right > nr.right + 1) {
        offenders.push({
          port: label.textContent ?? '?',
          reason: `label[${lr.left}..${lr.right}] outside node[${nr.left}..${nr.right}]`,
        })
      }
    }
    return { count: labels.length, offenders }
  })
  expect(labelFit.count).toBeGreaterThan(0)
  expect(labelFit.offenders).toEqual([])
})

// RFC-016 e2e: wrapper-git renders as a visible group container with its
// inner agent node physically contained inside the rect. Distinct from the
// happy-path test above because the existing fixture has no wrapper; we
// create a one-off workflow via the same API surface, open the editor, and
// assert the visual contract.
test('RFC-016: wrapper-git renders as a group container with inner node inside its rect', async ({
  page,
}) => {
  const headers = {
    Authorization: `Bearer ${daemon.token}`,
    'Content-Type': 'application/json',
  }
  const workflowName = 'e2e-wrapper-container'
  const createRes = await fetch(`${daemon.baseUrl}/api/workflows`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: workflowName,
      description: 'RFC-016 e2e — wrapper container visual contract.',
      definition: {
        $schema_version: 2,
        inputs: [{ kind: 'text', key: 'topic', label: 'Topic', required: true }],
        nodes: [
          { id: 'in_1', kind: 'input', inputKey: 'topic', position: { x: 0, y: 0 } },
          {
            id: 'w_git_1',
            kind: 'wrapper-git',
            nodeIds: ['agent_inside'],
            position: { x: 200, y: 100 },
            size: { width: 360, height: 200 },
          },
          {
            id: 'agent_inside',
            kind: 'agent-single',
            agentName: fixtures.agentName,
            promptTemplate: 'Explain {{topic}} briefly.',
            position: { x: 260, y: 160 }, // inside the wrapper rect
          },
          {
            id: 'out_1',
            kind: 'output',
            ports: [{ name: 'answer', bind: { nodeId: 'agent_inside', portName: 'answer' } }],
            position: { x: 700, y: 100 },
          },
        ],
        edges: [
          {
            id: 'e_in_agent',
            source: { nodeId: 'in_1', portName: 'topic' },
            target: { nodeId: 'agent_inside', portName: 'topic' },
          },
          {
            id: 'e_agent_out',
            source: { nodeId: 'agent_inside', portName: 'answer' },
            target: { nodeId: 'out_1', portName: 'answer' },
          },
        ],
      },
    }),
  })
  expectOk(createRes, 'create wrapper workflow')
  const wf = (await createRes.json()) as { id: string }

  // Open the editor directly — read-only canvas in /tasks/:id would also
  // work but we don't need a task run to validate the visual contract.
  await page.addInitScript(
    ({ baseUrl, token }) => {
      window.localStorage.setItem('agent-workflow.baseUrl', baseUrl)
      window.localStorage.setItem('agent-workflow.token', token)
      window.localStorage.setItem('aw-language', 'en-US')
    },
    { baseUrl: daemon.baseUrl, token: daemon.token },
  )
  await page.goto(`${daemon.baseUrl}/workflows/${wf.id}`)

  await expect(page.locator('.canvas-node--wrapper-group').first()).toBeVisible({
    timeout: 10_000,
  })
  await expect(page.locator('.canvas-node--wrapper-group--git').first()).toBeVisible()

  // The inner agent node should be visually contained in the wrapper rect.
  const containment = await page.evaluate(() => {
    const wrap = document.querySelector('.canvas-node--wrapper-group')
    const inner = Array.from(document.querySelectorAll('.canvas-node')).find(
      (n) =>
        !n.classList.contains('canvas-node--wrapper-group') &&
        n.textContent !== null &&
        n.textContent.includes('agent_inside'),
    )
    if (wrap === null || inner === undefined) return { found: false }
    const wr = wrap.getBoundingClientRect()
    const ir = inner.getBoundingClientRect()
    return {
      found: true,
      inside:
        ir.left >= wr.left - 1 &&
        ir.right <= wr.right + 1 &&
        ir.top >= wr.top - 1 &&
        ir.bottom <= wr.bottom + 1,
    }
  })
  expect(containment.found).toBe(true)
  expect(containment.inside).toBe(true)
})

// RFC-024 e2e: launch a task from a Git URL (cloned from a local `file://`
// bare repo). Asserts:
//   - Launcher's Repo source tab can switch to Remote URL
//   - POST /api/tasks with `repoUrl` succeeds; task lands in done
//   - Task detail page shows the redacted URL via the source row
//   - /api/cached-repos lists exactly one entry and DELETE removes it
test('RFC-024: launch task from git URL clones into cache and renders redacted URL', async ({
  page,
}) => {
  // Seed a bare repo + agent + workflow for this run via REST.
  const remoteRoot = mkdtempSync(join(tmpdir(), 'aw-e2e-rfc024-'))
  const working = join(remoteRoot, 'src')
  execSync('git init -b main -q', { cwd: remoteRoot })
  execSync(`mkdir -p "${working}"`, { stdio: 'ignore' })
  writeFileSync(join(remoteRoot, 'README.md'), '# rfc-024 fixture\n')
  execSync('git config user.email e2e@example.com', { cwd: remoteRoot })
  execSync('git config user.name e2e', { cwd: remoteRoot })
  execSync('git add . && git commit -qm init', { cwd: remoteRoot })
  const bare = join(remoteRoot, 'remote.git')
  execSync(`git clone --bare "${remoteRoot}" "${bare}"`, { stdio: 'ignore' })
  const remoteUrl = `file://${bare}`

  const headers = {
    Authorization: `Bearer ${daemon.token}`,
    'Content-Type': 'application/json',
  }
  const agentName = 'rfc024-stub'
  await fetch(`${daemon.baseUrl}/api/agents`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: agentName,
      description: 'rfc-024 e2e stub',
      outputs: ['answer'],
      readonly: true,
      bodyMd: '',
    }),
  })
  const workflowRes = await fetch(`${daemon.baseUrl}/api/workflows`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: 'rfc024-url-launch',
      description: 'RFC-024 e2e',
      definition: {
        $schema_version: 1,
        inputs: [{ kind: 'text', key: 'topic', label: 'Topic', required: true }],
        nodes: [
          { id: 'in_1', kind: 'input', inputKey: 'topic', position: { x: 0, y: 0 } },
          {
            id: 'agent_1',
            kind: 'agent-single',
            agentName,
            promptTemplate: '{{topic}}',
            position: { x: 320, y: 0 },
          },
          {
            id: 'out_1',
            kind: 'output',
            ports: [{ name: 'answer', bind: { nodeId: 'agent_1', portName: 'answer' } }],
            position: { x: 640, y: 0 },
          },
        ],
        edges: [
          {
            id: 'e1',
            source: { nodeId: 'in_1', portName: 'topic' },
            target: { nodeId: 'agent_1', portName: 'topic' },
          },
          {
            id: 'e2',
            source: { nodeId: 'agent_1', portName: 'answer' },
            target: { nodeId: 'out_1', portName: 'answer' },
          },
        ],
      },
    }),
  })
  expectOk(workflowRes, 'create rfc-024 workflow')
  const wf = (await workflowRes.json()) as { id: string }

  await primeAuthLocalStorage(page, daemon)
  // RFC-165: legacy launcher URL redirects into the wizard (Step 2).
  await page.goto(`${daemon.baseUrl}/workflows/${wf.id}/launch`)

  // Step 2 — the row is URL-only; fill the URL field.
  await page.fill('[data-testid="repo-source-url-0"]', remoteUrl)
  await page.getByTestId('stepper-next').click()

  // Step 3 — name + topic.
  await page.fill('[data-testid="wizard-task-name"]', 'e2e-url-task')
  await page
    .locator('label.form-field', { hasText: 'Topic (topic)' })
    .locator('input.form-input')
    .fill('rfc-024-test')
  await page.getByTestId('stepper-next').click()

  // Step 4 — launch.
  await page.getByRole('button', { name: /Start task/ }).click()
  await page.waitForURL(/\/tasks\/[A-Z0-9]{26}/i, { timeout: 30_000 })

  const taskId = page.url().match(/\/tasks\/([A-Z0-9]{26})/i)![1]
  const final = await pollUntilTerminal(daemon, taskId, 60_000)
  expect(final.status).toBe('done')

  // Task detail → Details tab → redacted URL row visible.
  await page.locator('.task-detail__tab-bar [role="tab"]', { hasText: /Details|详细信息/ }).click()
  const urlCell = page.getByTestId('task-detail-repo-url')
  await expect(urlCell).toBeVisible({ timeout: 10_000 })
  // For a `file://` URL there are no creds to redact; the redacted form is
  // identical, so we just check the URL is present.
  await expect(urlCell).toContainText('file://')

  // Cached repos list exposes a single entry for this URL.
  const cachedRes = await fetch(`${daemon.baseUrl}/api/cached-repos`, {
    headers: { Authorization: `Bearer ${daemon.token}` },
  })
  expectOk(cachedRes, 'GET cached-repos')
  const cachedBody = (await cachedRes.json()) as {
    items: Array<{ id: string; url: string; referencingTaskCount: number }>
  }
  const match = cachedBody.items.find((it) => it.url === remoteUrl)
  expect(match).toBeDefined()
  expect(match!.referencingTaskCount).toBeGreaterThanOrEqual(1)

  // DELETE without force → 409 (still referenced). Then DELETE with force → 200.
  const blocked = await fetch(`${daemon.baseUrl}/api/cached-repos/${match!.id}`, {
    method: 'DELETE',
    headers: { Authorization: `Bearer ${daemon.token}` },
  })
  expect(blocked.status).toBe(409)
  const forced = await fetch(`${daemon.baseUrl}/api/cached-repos/${match!.id}?force=1`, {
    method: 'DELETE',
    headers: { Authorization: `Bearer ${daemon.token}` },
  })
  expect(forced.status).toBe(200)

  // Cleanup.
  try {
    rmSync(remoteRoot, { recursive: true, force: true })
  } catch {
    /* noop */
  }
})

// RFC-033 e2e: batch import two bare repos via the /repos page modal.
// Asserts:
//   - Batch import button visible on /repos
//   - Pasting two valid `file://` URLs + one garbage string and clicking
//     Start posts to /api/cached-repos/batch-import and renders the table
//   - The two valid rows complete; the garbage row goes failed
//   - The main /repos table picks up two new cached-repo entries
test('RFC-033: batch import remote repos on /repos page', async ({ page }) => {
  // Two bare remotes — same fixture pattern as the RFC-024 test above.
  const root = mkdtempSync(join(tmpdir(), 'aw-e2e-rfc033-'))
  const urls: string[] = []
  for (let i = 0; i < 2; i++) {
    const working = join(root, `src-${i}`)
    execSync(`mkdir -p "${working}"`, { stdio: 'ignore' })
    execSync('git init -b main -q', { cwd: working })
    writeFileSync(join(working, 'README.md'), `# rfc-033 fixture ${i}\n`)
    execSync('git config user.email e2e@example.com', { cwd: working })
    execSync('git config user.name e2e', { cwd: working })
    execSync('git add . && git commit -qm init', { cwd: working })
    const bare = join(root, `remote-${i}.git`)
    execSync(`git clone --bare "${working}" "${bare}"`, { stdio: 'ignore' })
    urls.push(`file://${bare}`)
  }

  await primeAuthLocalStorage(page, daemon)
  await page.goto(`${daemon.baseUrl}/repos`)

  await page.getByTestId('repos-batch-import-button').click()

  const textarea = page.getByTestId('batch-import-textarea')
  await textarea.fill([...urls, 'not-a-url'].join('\n'))
  await page.getByTestId('batch-import-start').click()

  await page.getByTestId('batch-import-table').waitFor({ state: 'visible' })

  // Poll the snapshot endpoint until the batch completes.
  const batchIdFromLs = await page.evaluate(() =>
    window.localStorage.getItem('repo-import-batch-id'),
  )
  expect(batchIdFromLs).toBeTruthy()
  const headers = { Authorization: `Bearer ${daemon.token}` }
  const deadline = Date.now() + 60_000
  let snap: { state: string; rows: Array<{ status: string; inputUrlRedacted: string }> } | null =
    null
  while (Date.now() < deadline) {
    const r = await fetch(`${daemon.baseUrl}/api/cached-repos/imports/${batchIdFromLs}`, {
      headers,
    })
    if (r.ok) {
      snap = (await r.json()) as typeof snap
      if (snap!.state === 'completed') break
    }
    await new Promise((res) => setTimeout(res, 300))
  }
  expect(snap).not.toBeNull()
  expect(snap!.state).toBe('completed')
  const statuses = snap!.rows.map((r) => r.status).sort()
  expect(statuses).toEqual(['done', 'done', 'failed'])

  // Main /repos table should now list both URLs.
  const cachedRes = await fetch(`${daemon.baseUrl}/api/cached-repos`, { headers })
  expectOk(cachedRes, 'GET cached-repos after batch import')
  const cached = (await cachedRes.json()) as { items: Array<{ id: string; url: string }> }
  for (const u of urls) {
    expect(cached.items.some((it) => it.url === u)).toBe(true)
  }

  // Cleanup cached entries + tmp dir.
  for (const u of urls) {
    const it = cached.items.find((c) => c.url === u)
    if (it !== undefined) {
      await fetch(`${daemon.baseUrl}/api/cached-repos/${it.id}?force=1`, {
        method: 'DELETE',
        headers,
      })
    }
  }
  try {
    rmSync(root, { recursive: true, force: true })
  } catch {
    /* noop */
  }
})

// RFC-022 e2e: dependsOn closure renders as a Dependency tree on the agent
// detail page. We seed three agents A → B → C via REST, open the form for A,
// and assert that the tree renders all three rows (A as root, B + C nested).
// The closure-preview endpoint is also pinged directly to lock its wire
// shape from the browser's vantage point.
test('RFC-022: agent form Dependency tree (preview) renders the full closure', async ({ page }) => {
  const headers = {
    Authorization: `Bearer ${daemon.token}`,
    'Content-Type': 'application/json',
  }
  // Seed leaves first so the save-time guard accepts each row.
  const seed = async (name: string, dependsOn: string[]) => {
    const res = await fetch(`${daemon.baseUrl}/api/agents`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        name,
        description: `rfc-022 e2e ${name}`,
        dependsOn,
        outputs: [],
        readonly: false,
      }),
    })
    expectOk(res, `seed agent ${name}`)
  }
  await seed('rfc022-c', [])
  await seed('rfc022-b', ['rfc022-c'])
  await seed('rfc022-a', ['rfc022-b'])

  await page.addInitScript(
    ({ baseUrl, token }) => {
      window.localStorage.setItem('agent-workflow.baseUrl', baseUrl)
      window.localStorage.setItem('agent-workflow.token', token)
      window.localStorage.setItem('aw-language', 'en-US')
    },
    { baseUrl: daemon.baseUrl, token: daemon.token },
  )
  await page.goto(`${daemon.baseUrl}/agents/rfc022-a`)

  // 200ms debounce → wait for the closure preview to populate. The tree
  // renders a treeitem per closure member (root + dependents recursively).
  await expect(page.getByRole('treeitem', { name: 'rfc022-b' })).toBeVisible({ timeout: 5_000 })
  await expect(page.getByRole('treeitem', { name: 'rfc022-c' })).toBeVisible()
  // Sanity: root row exists too.
  await expect(page.getByRole('treeitem', { name: 'rfc022-a' })).toBeVisible()

  // Direct API check — the closure GET endpoint returns BFS-ordered agents.
  const closureRes = await fetch(`${daemon.baseUrl}/api/agents/rfc022-a/closure`, {
    headers: { Authorization: `Bearer ${daemon.token}` },
  })
  expectOk(closureRes, 'closure GET')
  const body = (await closureRes.json()) as { ok: boolean; agents: Array<{ name: string }> }
  expect(body.ok).toBe(true)
  expect(body.agents.map((a) => a.name)).toEqual(['rfc022-a', 'rfc022-b', 'rfc022-c'])
})

// RFC-027 e2e: NodeDetailDrawer "Session" tab renders the conversation
// flow for the previously-completed agent_1 node from the happy path.
// Verifies AC-1 (tab renamed to Session), AC-2 (attempts picker), AC-3
// (User role label visible), and AC-4 (prompt text becomes the first
// user message). Doesn't exercise subagent nesting (would need the stub
// to emit `task` tool parts + a fake opencode SQLite); the unit suite
// covers that part of the contract.
test('RFC-027: NodeDetailDrawer Session tab renders the agent conversation', async ({ page }) => {
  await primeAuthLocalStorage(page, daemon)

  // Find the most-recently completed happy-path task. The happy-path
  // beforeAll seeded the fixture; the earlier test may not have run in
  // this file order, so launch a fresh task here to guarantee state.
  const headers = {
    Authorization: `Bearer ${daemon.token}`,
    'Content-Type': 'application/json',
  }
  const startRes = await fetch(`${daemon.baseUrl}/api/tasks`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      workflowId: fixtures.workflowId,
      name: 'e2e-fixture-task',
      inputs: { topic: 'rfc-027' },
      repoUrl: pathToFileURL(fixtures.repoPath).href,
      ref: 'main',
    }),
  })
  expectOk(startRes, 'start task for rfc-027')
  const startedTask = (await startRes.json()) as { id: string }
  const finalTask = await pollUntilTerminal(daemon, startedTask.id, 30_000)
  expect(finalTask.status).toBe('done')

  await page.goto(`${daemon.baseUrl}/tasks/${startedTask.id}`)
  await expect(page.locator('.status-chip', { hasText: /^done$/i }).first()).toBeVisible({
    timeout: 15_000,
  })

  // Click the agent_1 canvas node — the only agent in the happy-path
  // workflow — to open the NodeDetailDrawer.
  await expect(page.locator('.canvas-node--agent').first()).toBeVisible({ timeout: 10_000 })
  await page.locator('.canvas-node--agent').first().click()

  // Session tab MUST be present and default-selected. Prompt tab is gone.
  // RFC-035 PR2: `.inspector__tabs` was a sibling-class wart on `.tabs`;
  // it is now expressed as the `.tabs--inspector` modifier on the same
  // primitive.
  // RFC-150: the drawer tab bar is the shared <TabBar> primitive now — tabs
  // carry role="tab" (a11y upgrade), not role="button".
  const tabBar = page.locator('.tabs--inspector')
  await expect(tabBar.getByRole('tab', { name: 'Session', exact: true })).toBeVisible()
  await expect(tabBar.getByRole('tab', { name: 'Prompt', exact: true })).toHaveCount(0)

  // The attempts picker is the Select-based combobox (replaced the
  // earlier chip-row, which itself replaced a native <select>). The
  // trigger is visible without opening; this happy-path task has one
  // attempt — the initial run — so the picked label reads "initial".
  const attemptsTrigger = page.locator('.session-attempts [role="combobox"]')
  await expect(attemptsTrigger).toBeVisible({ timeout: 5_000 })
  await expect(attemptsTrigger).toContainText(/initial/i)

  // The user prompt becomes the first message in the conversation flow —
  // its body should contain the rendered template ("Explain rfc-027 …").
  await expect(page.locator('.session-block--user .session-block__body')).toContainText(
    /Explain rfc-027/i,
    { timeout: 10_000 },
  )

  // Source-code-level assertion in the live build: the drawer's Session
  // tab actually contains a session-flow container (vs an empty fallback).
  await expect(page.locator('.session-flow').first()).toBeVisible()
})

// RFC-029 e2e: NodeDetailDrawer "Session" tab renders the Runtime
// Inventory section at the top, sourced from the per-run inventory.json
// the stub-opencode shim writes when OPENCODE_AW_INVENTORY_OUT is set.
// Verifies AC-1 (section appears in Session tab), AC-2 (Agents row), AC-4
// (MCP status badge color), AC-9 (chips show counts in the summary).
test('RFC-029: Runtime Inventory section renders on the Session tab', async ({ page }) => {
  await primeAuthLocalStorage(page, daemon)

  const headers = {
    Authorization: `Bearer ${daemon.token}`,
    'Content-Type': 'application/json',
  }
  const startRes = await fetch(`${daemon.baseUrl}/api/tasks`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      workflowId: fixtures.workflowId,
      name: 'e2e-fixture-task',
      inputs: { topic: 'rfc-029' },
      repoUrl: pathToFileURL(fixtures.repoPath).href,
      ref: 'main',
    }),
  })
  expectOk(startRes, 'start task for rfc-029')
  const startedTask = (await startRes.json()) as { id: string }
  const finalTask = await pollUntilTerminal(daemon, startedTask.id, 30_000)
  expect(finalTask.status).toBe('done')

  await page.goto(`${daemon.baseUrl}/tasks/${startedTask.id}`)
  await expect(page.locator('.status-chip', { hasText: /^done$/i }).first()).toBeVisible({
    timeout: 15_000,
  })

  await expect(page.locator('.canvas-node--agent').first()).toBeVisible({ timeout: 10_000 })
  await page.locator('.canvas-node--agent').first().click()

  // The inventory section must be present in the Session tab body, with
  // count chips visible even before the user expands it.
  const section = page.locator('[data-testid="runtime-inventory-section"]')
  await expect(section).toBeVisible({ timeout: 10_000 })
  await expect(page.locator('[data-testid="inventory-chips"]')).toBeVisible({
    timeout: 10_000,
  })

  // Expand the section. <details> is keyboard-toggleable via click on the
  // summary; use a click rather than .open property to mimic the user.
  await section.locator('summary').click()

  // Stub inventory has one agent + one skill + two mcps + one plugin.
  await expect(section).toContainText('e2e-stub-coder')
  await expect(section).toContainText('fixture-skill')
  await expect(section).toContainText('fixture-mcp-ok')
  await expect(section).toContainText('fixture-mcp-warn')
  // RFC-035 PR1: StatusBadge now renders the unified <StatusChip>, so the
  // semantic class anchor is `status-chip--warn` / `status-chip--success`.
  await expect(section.locator('.status-chip--warn').first()).toBeVisible()
  await expect(section.locator('.status-chip--success').first()).toBeVisible()
})
