// P-5-07 — happy-path e2e: daemon ↑ → login → workflow detail → launch task
// → wait for it to finish → assert outputs panel + node-detail drawer.
//
// The DAG itself is set up via the REST API so the test isn't exposed to
// xyflow drag-and-drop flakiness. The browser path covers what users
// actually click through: /auth, the workflow list, the launcher form, and
// the task detail page.

import { test, expect, type Page } from '@playwright/test'
import { execSync } from 'node:child_process'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { startDaemon, type DaemonHandle } from './harness'

interface CreatedFixtures {
  workflowId: string
  workflowName: string
  agentName: string
  repoPath: string
}

let daemon: DaemonHandle
let repoDir: string
let fixtures: CreatedFixtures

test.beforeAll(async () => {
  daemon = await startDaemon()

  // Build a throwaway git repo for the launcher. The daemon clones it into
  // a worktree at task launch time; the stub agent never reads it but the
  // git plumbing in scheduler.ts asserts the worktree exists with a HEAD.
  repoDir = mkdtempSync(join(tmpdir(), 'aw-e2e-repo-'))
  writeFileSync(join(repoDir, 'README.md'), '# e2e fixture repo\n', 'utf-8')
  execSync('git init -b main -q', { cwd: repoDir })
  execSync('git config user.email e2e@example.com', { cwd: repoDir })
  execSync('git config user.name e2e', { cwd: repoDir })
  execSync('git add .', { cwd: repoDir })
  execSync('git commit -qm initial', { cwd: repoDir })

  fixtures = await setupViaApi(daemon, repoDir)
})

test.afterAll(async () => {
  try {
    rmSync(repoDir, { recursive: true, force: true })
  } catch {
    // ignore
  }
  if (daemon !== undefined) await daemon.stop()
})

async function setupViaApi(d: DaemonHandle, repoPath: string): Promise<CreatedFixtures> {
  const headers = {
    Authorization: `Bearer ${d.token}`,
    'Content-Type': 'application/json',
  }
  const agentName = 'e2e-stub-coder'
  const agentRes = await fetch(`${d.baseUrl}/api/agents`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: agentName,
      description: 'e2e stub agent — outputs are produced by stub-opencode.sh',
      outputs: ['answer'],
      readonly: true,
      bodyMd: 'Echo back the topic prompt; the stub binary returns a fixed envelope anyway.',
    }),
  })
  expectOk(agentRes, 'create agent')

  const workflowName = 'e2e-happy-path'
  const workflowRes = await fetch(`${d.baseUrl}/api/workflows`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: workflowName,
      description: 'Generated by Playwright e2e (P-5-07).',
      definition: {
        $schema_version: 1,
        inputs: [{ kind: 'text', key: 'topic', label: 'Topic', required: true }],
        nodes: [
          { id: 'in_1', kind: 'input', inputKey: 'topic', position: { x: 0, y: 0 } },
          {
            id: 'agent_1',
            kind: 'agent-single',
            agentName,
            promptTemplate: 'Explain {{topic}} briefly.',
            position: { x: 320, y: 0 },
          },
          {
            id: 'out_1',
            kind: 'output',
            ports: [{ name: 'answer', bind: { nodeId: 'agent_1', portName: 'answer' } }],
            position: { x: 640, y: 0 },
          },
        ],
        edges: [
          {
            id: 'e_in_agent',
            source: { nodeId: 'in_1', portName: 'topic' },
            target: { nodeId: 'agent_1', portName: 'topic' },
          },
          {
            id: 'e_agent_out',
            source: { nodeId: 'agent_1', portName: 'answer' },
            target: { nodeId: 'out_1', portName: 'answer' },
          },
        ],
      },
    }),
  })
  expectOk(workflowRes, 'create workflow')
  const workflow = (await workflowRes.json()) as { id: string }

  const recentRes = await fetch(`${d.baseUrl}/api/repos/recent`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ path: repoPath }),
  })
  expectOk(recentRes, 'register recent repo')

  return { workflowId: workflow.id, workflowName, agentName, repoPath }
}

function expectOk(res: Response, what: string): void {
  if (!res.ok) {
    throw new Error(`e2e setup: ${what} failed: HTTP ${res.status}`)
  }
}

async function pollUntilTerminal(
  d: DaemonHandle,
  taskId: string,
  timeoutMs: number,
): Promise<{ status: string }> {
  const terminal = new Set(['done', 'failed', 'canceled', 'interrupted', 'exhausted'])
  const deadline = Date.now() + timeoutMs
  let last: { status: string } = { status: 'pending' }
  while (Date.now() < deadline) {
    const res = await fetch(`${d.baseUrl}/api/tasks/${taskId}`, {
      headers: { Authorization: `Bearer ${d.token}` },
    })
    if (res.ok) {
      last = (await res.json()) as { status: string }
      if (terminal.has(last.status)) return last
    }
    await new Promise((r) => setTimeout(r, 500))
  }
  throw new Error(
    `task ${taskId} did not reach terminal status in ${timeoutMs}ms; last=${last.status}`,
  )
}

async function primeAuthLocalStorage(page: Page, d: DaemonHandle): Promise<void> {
  // Stamp localStorage before the SPA mounts so the auth gate redirects
  // straight through. Same shape as /auth's submit handler writes.
  await page.addInitScript(
    ({ baseUrl, token }) => {
      try {
        window.localStorage.setItem('agent-workflow.baseUrl', baseUrl)
        window.localStorage.setItem('agent-workflow.token', token)
        // Force English so the test selectors line up with en-US strings.
        window.localStorage.setItem('aw-language', 'en-US')
      } catch {
        // ignore — shouldn't fail in chromium
      }
    },
    { baseUrl: d.baseUrl, token: d.token },
  )
}

test('happy path: agents → workflow → launch → task done → outputs visible', async ({ page }) => {
  await primeAuthLocalStorage(page, daemon)

  // 1. Landing — pre-seeded localStorage routes us straight to /agents.
  await page.goto(`${daemon.baseUrl}/`)
  await expect(page.getByRole('heading', { name: 'Agents', exact: true })).toBeVisible()
  await expect(page.getByText(fixtures.agentName)).toBeVisible()

  // 2. Workflow editor — confirm the row is there, then open it via the link.
  await page.getByRole('link', { name: 'Workflows', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Workflows', exact: true })).toBeVisible()
  const openLink = page
    .getByRole('row', { name: new RegExp(fixtures.workflowName) })
    .getByRole('link', { name: /open/i })
  await openLink.click()
  await expect(page.getByRole('heading', { name: fixtures.workflowName })).toBeVisible()

  // 3. Launcher.
  await page.getByRole('link', { name: /launch task/i }).click()
  await expect(
    page.getByRole('heading', { name: `Launch: ${fixtures.workflowName}` }),
  ).toBeVisible()

  // The auto-pick effect should have seeded repoPath + baseBranch from the
  // recent-repo we registered (main detected via `git init -b main`). The
  // Field label rendered for the input includes the asterisk for required
  // fields, so match with a regex instead of exact.
  const topicInput = page
    .locator('label.form-field', { hasText: 'Topic (topic)' })
    .locator('input.form-input')
  await expect(topicInput).toBeVisible({ timeout: 10_000 })
  await topicInput.fill('e2e-test')

  // baseBranch select may take a moment to swap in once /api/repos/refs
  // resolves. If it's a <select>, ensure 'main' is selected.
  const branchSelect = page.locator('select').nth(1) // [0]=repo, [1]=branch when present
  await expect(branchSelect).toBeVisible({ timeout: 10_000 })
  await branchSelect.selectOption('main')

  await page.getByRole('button', { name: 'Start task', exact: true }).click()

  // 4. Task detail page — URL changes to /tasks/<id>.
  await page.waitForURL(/\/tasks\/[A-Z0-9]+/i, { timeout: 15_000 })

  // 5. Wait for the task to terminate. Poll the API rather than scraping
  // the DOM so transient states aren't mistaken for the final one.
  const taskUrl = page.url()
  const taskId = taskUrl.match(/\/tasks\/([A-Z0-9]+)/i)![1]
  const finalTask = await pollUntilTerminal(daemon, taskId, 30_000)
  expect(finalTask.status).toBe('done')

  // 6. node_run outputs should include the stub's port=answer value.
  const nodeRunsRes = await fetch(`${daemon.baseUrl}/api/tasks/${taskId}/node-runs`, {
    headers: { Authorization: `Bearer ${daemon.token}` },
  })
  expect(nodeRunsRes.ok).toBeTruthy()
  const nodeRuns = (await nodeRunsRes.json()) as {
    runs: { nodeId: string; status: string }[]
    outputs: { nodeRunId: string; port: string; value: string }[]
  }
  const agentRun = nodeRuns.runs.find((r) => r.nodeId === 'agent_1')
  expect(agentRun?.status).toBe('done')
  const answerOutput = nodeRuns.outputs.find((o) => o.port === 'answer')
  expect(answerOutput?.value).toBe('stub e2e output')

  // 7. The UI eventually mirrors that: status chip + output panel value.
  //
  // The frontend polls /api/tasks/:id/node-runs every 3s and refreshes on
  // WebSocket task-update events. Under CI load the page sometimes lands on
  // /tasks/:id after the daemon has already finished and the WS event
  // arrived; we then depend on the polling fallback, which can leave the
  // outputs panel un-rendered for up to two intervals. Force a fresh fetch
  // by reloading the page now that step 6 confirmed the outputs are in the
  // API — this turns a previously-flaky timing race into a deterministic
  // assertion (RFC-004 CI run 25915917054 caught the prior 1-flaky case).
  await page.reload()
  await expect(page.locator('.status-chip', { hasText: /^done$/ }).first()).toBeVisible({
    timeout: 15_000,
  })
  // RFC-021: outputs now live inside the Outputs tab on the task detail
  // page (default tab is Workflow status). Click the tab before asserting
  // the output card is visible. The tab itself only renders when
  // `collectPorts(workflowSnapshot).length > 0`, so its appearance also
  // doubles as a smoke check for hasOutputs detection.
  await page
    .locator('.task-detail__tab-bar [role="tab"]', { hasText: /Outputs|输出/ })
    .click()
  await expect(page.locator('.task-output-card__body', { hasText: 'stub e2e output' })).toBeVisible(
    { timeout: 15_000 },
  )

  // 8. RFC-006 visual contract: every port label is rendered INSIDE the
  // bounding rectangle of its containing .canvas-node. The old strip-of-
  // chips layout pushed labels onto a -6px sidebar that overlapped the
  // node body and bled past its left/right edges; we lock that out here
  // in the task-detail canvas (same WorkflowCanvas as the editor, read-
  // only mode).
  //
  // RFC-021: step 7 left us on the Outputs tab (canvas pane is hidden via
  // [hidden] → display:none). Switch back to Workflow status so the canvas
  // is in the live layout tree before geometry assertions run.
  await page
    .locator('.task-detail__tab-bar [role="tab"]', { hasText: /Workflow status|工作流状态/ })
    .click()
  await expect(page.locator('.canvas-node__port-label').first()).toBeVisible({ timeout: 10_000 })
  const labelFit = await page.evaluate(() => {
    const labels = Array.from(document.querySelectorAll('.canvas-node__port-label'))
    const offenders: { port: string; reason: string }[] = []
    for (const label of labels) {
      const node = label.closest('.canvas-node')
      if (node === null) {
        offenders.push({ port: label.textContent ?? '?', reason: 'no .canvas-node ancestor' })
        continue
      }
      const lr = label.getBoundingClientRect()
      const nr = node.getBoundingClientRect()
      // Allow 1px sub-pixel slack on each side; xyflow's zoom rounding
      // occasionally yields fractional bleed of less than a pixel.
      if (lr.left < nr.left - 1 || lr.right > nr.right + 1) {
        offenders.push({
          port: label.textContent ?? '?',
          reason: `label[${lr.left}..${lr.right}] outside node[${nr.left}..${nr.right}]`,
        })
      }
    }
    return { count: labels.length, offenders }
  })
  expect(labelFit.count).toBeGreaterThan(0)
  expect(labelFit.offenders).toEqual([])
})

// RFC-016 e2e: wrapper-git renders as a visible group container with its
// inner agent node physically contained inside the rect. Distinct from the
// happy-path test above because the existing fixture has no wrapper; we
// create a one-off workflow via the same API surface, open the editor, and
// assert the visual contract.
test('RFC-016: wrapper-git renders as a group container with inner node inside its rect', async ({
  page,
}) => {
  const headers = {
    Authorization: `Bearer ${daemon.token}`,
    'Content-Type': 'application/json',
  }
  const workflowName = 'e2e-wrapper-container'
  const createRes = await fetch(`${daemon.baseUrl}/api/workflows`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: workflowName,
      description: 'RFC-016 e2e — wrapper container visual contract.',
      definition: {
        $schema_version: 2,
        inputs: [{ kind: 'text', key: 'topic', label: 'Topic', required: true }],
        nodes: [
          { id: 'in_1', kind: 'input', inputKey: 'topic', position: { x: 0, y: 0 } },
          {
            id: 'w_git_1',
            kind: 'wrapper-git',
            nodeIds: ['agent_inside'],
            position: { x: 200, y: 100 },
            size: { width: 360, height: 200 },
          },
          {
            id: 'agent_inside',
            kind: 'agent-single',
            agentName: fixtures.agentName,
            promptTemplate: 'Explain {{topic}} briefly.',
            position: { x: 260, y: 160 }, // inside the wrapper rect
          },
          {
            id: 'out_1',
            kind: 'output',
            ports: [{ name: 'answer', bind: { nodeId: 'agent_inside', portName: 'answer' } }],
            position: { x: 700, y: 100 },
          },
        ],
        edges: [
          {
            id: 'e_in_agent',
            source: { nodeId: 'in_1', portName: 'topic' },
            target: { nodeId: 'agent_inside', portName: 'topic' },
          },
          {
            id: 'e_agent_out',
            source: { nodeId: 'agent_inside', portName: 'answer' },
            target: { nodeId: 'out_1', portName: 'answer' },
          },
        ],
      },
    }),
  })
  expectOk(createRes, 'create wrapper workflow')
  const wf = (await createRes.json()) as { id: string }

  // Open the editor directly — read-only canvas in /tasks/:id would also
  // work but we don't need a task run to validate the visual contract.
  await page.addInitScript(
    ({ baseUrl, token }) => {
      window.localStorage.setItem('agent-workflow.baseUrl', baseUrl)
      window.localStorage.setItem('agent-workflow.token', token)
      window.localStorage.setItem('aw-language', 'en-US')
    },
    { baseUrl: daemon.baseUrl, token: daemon.token },
  )
  await page.goto(`${daemon.baseUrl}/workflows/${wf.id}`)

  await expect(page.locator('.canvas-node--wrapper-group').first()).toBeVisible({
    timeout: 10_000,
  })
  await expect(page.locator('.canvas-node--wrapper-group--git').first()).toBeVisible()

  // The inner agent node should be visually contained in the wrapper rect.
  const containment = await page.evaluate(() => {
    const wrap = document.querySelector('.canvas-node--wrapper-group')
    const inner = Array.from(document.querySelectorAll('.canvas-node')).find(
      (n) =>
        !n.classList.contains('canvas-node--wrapper-group') &&
        n.textContent !== null &&
        n.textContent.includes('agent_inside'),
    )
    if (wrap === null || inner === undefined) return { found: false }
    const wr = wrap.getBoundingClientRect()
    const ir = inner.getBoundingClientRect()
    return {
      found: true,
      inside:
        ir.left >= wr.left - 1 &&
        ir.right <= wr.right + 1 &&
        ir.top >= wr.top - 1 &&
        ir.bottom <= wr.bottom + 1,
    }
  })
  expect(containment.found).toBe(true)
  expect(containment.inside).toBe(true)
})
