// RFC-005 PR-E T36 — full review-cycle e2e.
//
// Drives a workflow with a review node through reject → iterate → approve.
// API-driven (not UI-clicking): the UI surfaces are already covered by
// component tests (Reviews list / detail, CommentPopover, MarkdownView,
// DiffView). What this spec proves is the end-to-end wire: real daemon +
// scheduler + DB + WS rebroadcast, exercised by a real opencode stub.
//
// The stub binary in e2e/fixtures/stub-opencode.sh emits a fixed envelope
//   <port name="answer">stub e2e output</port>
// so every regen produces the same body. That's enough to walk the state
// machine and assert task transitions: awaiting_review → running → ...
//
// What's intentionally NOT covered here (already unit-tested):
//   - Anchor disambiguation / occurrenceIndex recomputation
//   - DiffView granularity rendering
//   - Draft IndexedDB persistence
//   - Mermaid / PlantUML rendering
//   - Workflow-level review nodes inside multi-process or loop wrappers
//     (deferred to PR-B T14 / T15 follow-ups)

import { test, expect } from '@playwright/test'
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

import { startDaemon, type DaemonHandle } from './harness'
import { initGitRepo } from './command'

interface CreatedFixtures {
  workflowId: string
  workflowName: string
  agentName: string
  repoPath: string
}

let daemon: DaemonHandle
let repoDir: string
let fixtures: CreatedFixtures

test.beforeAll(async () => {
  daemon = await startDaemon()

  repoDir = mkdtempSync(join(tmpdir(), 'aw-e2e-review-repo-'))
  writeFileSync(join(repoDir, 'README.md'), '# review e2e fixture\n', 'utf-8')
  initGitRepo(repoDir)

  fixtures = await setupViaApi(daemon, repoDir)
})

test.afterAll(async () => {
  try {
    rmSync(repoDir, { recursive: true, force: true })
  } catch {
    /* ignore */
  }
  if (daemon !== undefined) await daemon.stop()
})

async function setupViaApi(d: DaemonHandle, repoPath: string): Promise<CreatedFixtures> {
  const headers = {
    Authorization: `Bearer ${d.token}`,
    'Content-Type': 'application/json',
  }
  const agentName = 'e2e-review-stub'
  const agentRes = await fetch(`${d.baseUrl}/api/agents`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: agentName,
      description: 'e2e review stub — emits a fixed markdown body',
      outputs: ['answer'],
      outputKinds: { answer: 'markdown' },
      readonly: true,
      bodyMd: 'Stub agent for review e2e.',
    }),
  })
  expectOk(agentRes, 'create agent')

  const workflowName = 'e2e-review-cycle'
  const workflowRes = await fetch(`${d.baseUrl}/api/workflows`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      name: workflowName,
      description: 'Generated by Playwright e2e (RFC-005 PR-E T36).',
      definition: {
        $schema_version: 2,
        inputs: [{ kind: 'text', key: 'topic', label: 'Topic', required: true }],
        nodes: [
          { id: 'in_1', kind: 'input', inputKey: 'topic', position: { x: 0, y: 0 } },
          {
            id: 'agent_1',
            kind: 'agent-single',
            agentName,
            promptTemplate: 'Write design for {{topic}}.',
            position: { x: 320, y: 0 },
          },
          {
            id: 'review_1',
            kind: 'review',
            title: 'design review',
            description: '',
            inputSource: { nodeId: 'agent_1', portName: 'answer' },
            rerunnableOnReject: [],
            rerunnableOnIterate: [],
            rollbackFilesOnReject: false,
            rollbackFilesOnIterate: false,
            position: { x: 640, y: 0 },
          },
          {
            id: 'out_1',
            kind: 'output',
            ports: [{ name: 'doc', bind: { nodeId: 'review_1', portName: 'approved_doc' } }],
            position: { x: 960, y: 0 },
          },
        ],
        edges: [
          {
            id: 'e_in_agent',
            source: { nodeId: 'in_1', portName: 'topic' },
            target: { nodeId: 'agent_1', portName: 'topic' },
          },
          {
            id: 'e_agent_review',
            source: { nodeId: 'agent_1', portName: 'answer' },
            target: { nodeId: 'review_1', portName: '__review_input__' },
          },
          {
            id: 'e_review_out',
            source: { nodeId: 'review_1', portName: 'approved_doc' },
            target: { nodeId: 'out_1', portName: 'doc' },
          },
        ],
      },
    }),
  })
  expectOk(workflowRes, 'create workflow')
  const workflow = (await workflowRes.json()) as { id: string }

  return { workflowId: workflow.id, workflowName, agentName, repoPath }
}

function expectOk(res: Response, what: string): void {
  if (!res.ok) {
    throw new Error(`e2e setup: ${what} failed: HTTP ${res.status}`)
  }
}

interface TaskRow {
  status: string
}

interface ReviewSummaryRow {
  nodeRunId: string
  taskId: string
  reviewIteration: number
  awaitingReview: boolean
}

async function pollTaskStatus(
  d: DaemonHandle,
  taskId: string,
  predicate: (t: TaskRow) => boolean,
  timeoutMs: number,
): Promise<TaskRow> {
  const deadline = Date.now() + timeoutMs
  let last: TaskRow = { status: 'pending' }
  while (Date.now() < deadline) {
    const res = await fetch(`${d.baseUrl}/api/tasks/${taskId}`, {
      headers: { Authorization: `Bearer ${d.token}` },
    })
    if (res.ok) {
      last = (await res.json()) as TaskRow
      if (predicate(last)) return last
    }
    await new Promise((r) => setTimeout(r, 300))
  }
  throw new Error(`pollTaskStatus: timeout — last=${JSON.stringify(last)}`)
}

/**
 * Polls `/api/reviews?status=pending` until a row for `taskId` shows up with
 * `reviewIteration === targetIteration` and `awaitingReview === true`.
 * Used to walk through the reject → iterate → approve cycle — the task row
 * itself doesn't expose `reviewIteration` (lives on node_runs), so we use
 * the summary list as the cycle signal.
 */
async function waitForPendingReviewAt(
  d: DaemonHandle,
  taskId: string,
  targetIteration: number,
  timeoutMs: number,
): Promise<ReviewSummaryRow> {
  const deadline = Date.now() + timeoutMs
  let last: ReviewSummaryRow | null = null
  while (Date.now() < deadline) {
    const res = await fetch(`${d.baseUrl}/api/reviews?status=pending`, {
      headers: { Authorization: `Bearer ${d.token}` },
    })
    if (res.ok) {
      const summaries = (await res.json()) as ReviewSummaryRow[]
      const row = summaries.find((r) => r.taskId === taskId)
      if (row !== undefined) {
        last = row
        if (row.awaitingReview && row.reviewIteration === targetIteration) return row
      }
    }
    await new Promise((r) => setTimeout(r, 300))
  }
  throw new Error(
    `waitForPendingReviewAt: timeout target=${targetIteration} lastSeen=${JSON.stringify(last)}`,
  )
}

async function submitDecision(
  d: DaemonHandle,
  nodeRunId: string,
  decision: 'approved' | 'rejected' | 'iterated',
  reviewIteration: number,
  rejectReason?: string,
): Promise<void> {
  const res = await fetch(`${d.baseUrl}/api/reviews/${nodeRunId}/decision`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${d.token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ decision, reviewIteration, rejectReason }),
  })
  if (!res.ok) {
    throw new Error(
      `decision ${decision} (iter=${reviewIteration}) failed: HTTP ${res.status} ${await res.text()}`,
    )
  }
}

test('review cycle: awaiting → reject → awaiting → iterate → awaiting → approve → done', async () => {
  // 1. Launch task.
  const headers = {
    Authorization: `Bearer ${daemon.token}`,
    'Content-Type': 'application/json',
  }
  const launchRes = await fetch(`${daemon.baseUrl}/api/tasks`, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      workflowId: fixtures.workflowId,
      name: 'e2e-fixture-task',
      repoUrl: pathToFileURL(fixtures.repoPath).href,
      ref: 'main',
      inputs: { topic: 'order_status enum' },
    }),
  })
  expectOk(launchRes, 'launch task')
  const launched = (await launchRes.json()) as { id: string }
  const taskId = launched.id

  // 2. Wait for first pending review at iteration 0.
  const first = await waitForPendingReviewAt(daemon, taskId, 0, 30_000)
  expect(first.reviewIteration).toBe(0)

  // 3. Reject.
  await submitDecision(
    daemon,
    first.nodeRunId,
    'rejected',
    0,
    'please redo the failure-modes section',
  )

  // 4. Wait for second pending review at iteration 1.
  const second = await waitForPendingReviewAt(daemon, taskId, 1, 30_000)
  expect(second.reviewIteration).toBe(1)
  // Same node_run is reused across decisions — reviewIteration just bumps.
  expect(second.nodeRunId).toBe(first.nodeRunId)

  // 5. Iterate.
  await submitDecision(daemon, second.nodeRunId, 'iterated', 1)

  // 6. Wait for third pending review at iteration 2.
  const third = await waitForPendingReviewAt(daemon, taskId, 2, 30_000)
  expect(third.reviewIteration).toBe(2)

  // 7. Approve.
  await submitDecision(daemon, third.nodeRunId, 'approved', 2)

  // 8. Wait for terminal done.
  const final = await pollTaskStatus(daemon, taskId, (t) => t.status === 'done', 30_000)
  expect(final.status).toBe('done')

  // 9. The review node persists per-decision markdown via doc_versions
  // (NOT via node_run_outputs — the review service writes body files under
  // ~/.agent-workflow/runs/... and surfaces them through the reviews API).
  // The same review node_run is reused across all three decisions.
  const reviewNodeRunId = third.nodeRunId
  const versionsRes = await fetch(`${daemon.baseUrl}/api/reviews/${reviewNodeRunId}/versions`, {
    headers: { Authorization: `Bearer ${daemon.token}` },
  })
  expectOk(versionsRes, 'list doc versions')
  const versions = (await versionsRes.json()) as {
    id: string
    reviewIteration: number
    decision: string | null
  }[]
  // Final decisions: 0 = rejected, 1 = iterated, 2 = approved.
  const byIter = new Map(versions.map((v) => [v.reviewIteration, v.decision]))
  expect(byIter.get(0)).toBe('rejected')
  expect(byIter.get(1)).toBe('iterated')
  expect(byIter.get(2)).toBe('approved')

  // 10. The approved version's body must carry the stub's emitted markdown
  // (proves the upstream port → doc_version capture path works end-to-end).
  const approvedVersion = versions.find((v) => v.decision === 'approved')
  expect(approvedVersion).toBeDefined()
  const bodyRes = await fetch(
    `${daemon.baseUrl}/api/reviews/${reviewNodeRunId}/versions/${approvedVersion?.id}`,
    { headers: { Authorization: `Bearer ${daemon.token}` } },
  )
  expectOk(bodyRes, 'fetch approved doc body')
  const bodyJson = (await bodyRes.json()) as { body: string }
  expect(bodyJson.body).toContain('stub e2e output')
})
