-- table: task_execution_observation_sources
CREATE TABLE "agent_workflow"."task_execution_observation_sources" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "task_id" TEXT COLLATE "C" NOT NULL,
  "node_run_id" TEXT COLLATE "C" NOT NULL,
  "evidence_json" TEXT COLLATE "C" NOT NULL,
  "pending" BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT "task_execution_observation_sources_pkey" PRIMARY KEY ("id")
);

-- index: task_execution_observation_sources:index:idx_task_observation_pending
CREATE INDEX "idx_task_observation_pending" ON "agent_workflow"."task_execution_observation_sources" ("pending", "node_run_id", "id");

-- index: task_execution_observation_sources:index:idx_task_observation_node
CREATE INDEX "idx_task_observation_node" ON "agent_workflow"."task_execution_observation_sources" ("node_run_id", "id");

-- constraint: task_execution_observation_sources:fk:task_execution_observation_sources_task_id_tasks_id_fk
ALTER TABLE "agent_workflow"."task_execution_observation_sources" ADD CONSTRAINT "task_execution_observation_sources_task_id_tasks_id_fk" FOREIGN KEY ("task_id") REFERENCES "agent_workflow"."tasks" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- constraint: task_execution_observation_sources:fk:task_execution_observation_sources_node_run_id_node_runs_id_fk
ALTER TABLE "agent_workflow"."task_execution_observation_sources" ADD CONSTRAINT "task_execution_observation_sources_node_run_id_node_runs_id_fk" FOREIGN KEY ("node_run_id") REFERENCES "agent_workflow"."node_runs" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;

-- metadata: advance-contract-row
UPDATE "agent_workflow_meta"."schema_contract" SET contract_digest = 'sha256:f25b12861dee6ead97e6f066776794739217086c2d38f21474dd2015f539b1cb', active_table_count = 193, archive_only_table_count = 6 WHERE singleton = TRUE AND contract_digest = 'sha256:799edd05285d773e07ad9d704a90b0756df6604b892df220dd02a3cec8b95fd0' RETURNING contract_digest;
