// Shared types and schemas between frontend and backend.

export const SHARED_PACKAGE_VERSION = '0.0.0'

export * from './schemas/agent'
export * from './schemas/apiError'
export * from './schemas/cachedRepo'
export * from './schemas/clarify'
export * from './schemas/config'
export * from './schemas/oidcProvider'
export * from './schemas/permission'
export * from './schemas/repo'
export * from './schemas/review'
export * from './schemas/runtime'
export * from './schemas/mcp'
export * from './schemas/mcpProbe'
export * from './schemas/memory'
export * from './schemas/plugin'
export * from './schemas/repoBatchImport'
export * from './schemas/skill'
export * from './schemas/task'
export * from './schemas/taskCollab'
export * from './schemas/taskFeedback'
export * from './schemas/user'
export * from './schemas/workflow'
export * from './schemas/sessionView'
export * from './schemas/ws'
export * from './sessionView'
export * from './inventory'
export * from './clarify'
export * from './clarify-aging'
export * from './git-url'
export * from './prompt'
export * from './agent-md'
export * from './skill-md'
export * from './skill-zip'
export * from './outputKinds'
export * from './lifecycle'
export * from './lifecycle-alerts'
export * from './diagnose-repair'
export * from './node-kind-behavior'
// RFC-060 PR-E: removed `./sharding` (was RFC-055 agent-multi sharding strategy
// helpers — agent-multi NodeKind has been removed in favor of wrapper-fanout).
export * from './kindParser'
export * from './shardingRegistry'
export * from './signalPromptGuard'
export * from './wrapperFanout'
// RFC-062 §2 — workflow edge contracts (SYSTEM_PORT_NAMES + filterDataEdges
// + isFeedbackEdge). Public so every consumer of workflow.edges can
// explicitly choose between data-only or feedback-only views.
export * from './workflow-edges'
// RFC-061 PR-A: event-sourced execution model — types only in PR-A; PR-B
// fills in the concrete handler implementations.
export * from './events'
export * from './handlers'
export * from './promptFromEvents'
