// RFC-349 compatibility facade. SQLite lifecycle mechanisms live in Task
// Execution infrastructure; provider-neutral callers consume composed
// TaskExecutionPersistence participants instead of importing database types.
export {
  ConcurrentMergeStateTransition,
  ConcurrentNodeRunTransition,
  ConcurrentTaskTransition,
  TERMINAL_TASK_STATUSES,
  abandonSupersededMergeStates,
  assertNodeRunSourceTerminationAdmission,
  cancelOpenNodeRuns,
  isTerminalTaskStatus,
  registerTerminalWorkspacePrunePolicy,
  resolveTerminalWorkspacePruneDecision,
  setNodeRunStatus,
  setNodeRunStatusTx,
  setTaskStatus,
  transitionMergeState,
  transitionNodeRunStatus,
  transitionNodeRunStatusTx,
  transitionTaskStatusByEvent,
  trySetTaskStatus,
  tryTransitionMergeState,
  type HumanGateTaskTransition,
  type MergeStateUpdateExtra,
  type NodeRunStatusUpdateExtra,
  type TaskStatusUpdateExtra,
  type TerminalWorkspacePruneDecision,
  type TerminalWorkspacePrunePolicy,
  type WorkspacePruneCause,
} from '@/platform/persistence/sqlite/taskLifecycle'
