// Standalone compatibility export; installation and generation effects are RC local mechanisms.
export {
  type InstallResult,
  PLUGIN_GENERATION_MANIFEST,
  type PluginGenerationManifest,
  PluginInstallFailedError,
  PluginInstallTimeoutError,
  NpmUnavailableError,
  PluginFileNotFoundError,
  inferSourceKind,
  probeNpmBinary,
  resetNpmProbeCacheForTests,
  plannedGenerationDir,
  installPlugin,
  fileSpecToHostPath,
  checkForUpdate,
  readGenerationManifestForCachedPath,
  cleanupInstallGeneration,
  garbageCollectPluginGenerations,
  resolveNpmCommandForHost,
  resolveNpmCommand,
} from '@/modules/resource-catalog/infrastructure/local/filePluginInstallation'
