// RFC-370 compatibility address; the complete native implementation has one owner.
export {
  INTERPRETER_SPEC,
  WINDOWS_INTERPRETER_CANDIDATES,
  INTERPRETER_PROBE_TIMEOUT_MS,
  gitBashCandidatesFromGitPath,
  gitBashFromGitPath,
  resolveScriptInterpreter,
  describeInterpreterResolution,
  interpreterCandidatePaths,
  assembleScriptEnv,
  runScriptProcess,
  classifyScriptOutcome,
  SCRIPT_DEFAULT_OUTPUT_PORT,
  SCRIPT_ENV_FILE_PREFIX,
  readScriptDependencies,
  resolveScriptReadonly,
  type ResolvedInterpreter,
  type ScriptEnvAssembly,
  type ScriptRunRequest,
  type ScriptRunOutcome,
} from '@/modules/task-execution/infrastructure/local/scriptRun'
