-- RFC-061 PR-B T10 - drop the legacy clarify_rounds table.
--
-- Original intent: drop all 7 legacy execution-model tables. The first
-- attempt at this migration omitted drizzle statement-breakpoint markers
-- between the DROPs, so the bun-sqlite migrator only executed the first
-- DROP and silently no-op'd the rest. Databases that already ran 0034
-- therefore have clarify_rounds dropped + the other 6 tables intact.
--
-- This file is the corrected version: clarify_rounds is the only table
-- the migration ever actually dropped, so that is all we declare here.
-- The remaining 6 tables (node_runs, node_run_events, node_run_outputs,
-- clarify_sessions, cross_clarify_sessions, doc_versions) still back 13
-- legacy consumer services that have not yet been migrated to the new
-- events + projection model; dropping them now would runtime-fail those
-- services. See design/RFC-061-execution-event-sourced/plan.md PR-D for
-- the deferred cleanup follow-up.
DROP TABLE IF EXISTS clarify_rounds;
